### ISSUE TITLE
Gilded Bike horn Wrong sound

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#10066]
## Description
Gilded Bike horn sounds like a piano

**Comment by Zumorica** [comment]
Needs reproduction steps, I tested this due to a report a few days ago and I couldn't replicate it.

**Comment by DoctorBeard** [comment]
Here's how I could replicate it at the time I mentioned it on Discord:
1. Launch server and client (in my case both from VS2022)
2. Launch a second client via runclient.bat
3. Connect with both client (used the same user on both)
4. Spawn a gilded bikehorn on either client (pAI will have the same issue, anything that uses something from space-station-14.sf2)
5. Take it on either client and use the instrument to open the UI
6. Click "Play MIDI file" in the UI and select any MIDI file on the PC, I tested this with multiple files from various sources and all the had problem. I haven't tested if this also happens with MIDI input or just files
7. On the client you're playing it on it will have the correct sound (program 1, bank 1 for bike horn)
8. On the other client it will use default sounds

I also found that while the file is playing, using the console to call dirty on the instrument entity fixes it on the second client. Walking out of range of the instrument and then back into range also fixed it sometimes but I'm assuming that also just caused the entity to get synced again, just like calling dirty.

I still have the recordings I made of it when it happend to me for all they're worth since it really just shows that it does seem to happen for some people, even if can't be reliably reproduced

https://user-images.githubusercontent.com/163145/181125085-8a136cf4-a210-4a2f-8747-43a1322f1176.mp4

https://user-images.githubusercontent.com/163145/181125105-4d61ae3f-6c09-4d85-9c1c-1b7cd7e8a669.mp4

https://user-images.githubusercontent.com/163145/181125115-3bf6a031-07fa-4d69-b7a9-660eacfb4e82.mp4


.

**Comment by Zumorica** [comment]
Say, do any of you use a custom soundfont perhaps?

**Comment by EmoGarbage404** [comment]
If this works with gilded horn, this should theoretically also work with euphonium, as it also uses a custom soundfont.

**Comment by DoctorBeard** [comment]
> Say, do any of you use a custom soundfont perhaps?

I wouldn't even know how. Tested with a fresh clone of master and if I have a custom soundfont on Windows 10 then I frankly don't know where it came from but I can't rule it out either.

**Comment by Kromabae** [comment]
i dunno how to reproduce it since all i did at round start was to pick up the gilded bike horn and started playing
and sounded like a piano

**Comment by retequizzle** [comment]
i can confirm that on master, the gilded bike horn was playing as a piano for me as well

i do not use custom sound fonts of any kind, the instrument was being played by someone else as well
