### ISSUE TITLE
Lasers go through walls but get stopped by windows

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#1014]
I'm not sure what happened but it seems like something got mixed up with the laser raycast collision flags.

**Comment by ComicIronic** [comment]
I may have done this accidentally as part of the flag name changes.

**Comment by 20kdc** [comment]
It might not be specific to lasers. The "Opaque" collision group in general appears to be non-functional (affected #961, I worked around it by switching to Impassable for the moment)

**Comment by ComicIronic** [comment]
I think non-functional is the wrong term. The Opaque group appears to be *inverted*, in that things marked Opaque are actually transparent and vice versa.

**Comment by ComicIronic** [comment]
I can't confirm that lasers ever worked correctly, but the issue appears to be twofold

  1. Lasers are marked with the wrong collision mask. They currently have `Impassable | MobImpassable`, which is why they hit windows, since windows are (obviously) not passable. They should have the `Opaque` mask.
  2. Ray collisions happen in a non-deterministic order, but most rays (including lasers) stop after the "first" collision. The code seems to assume that "first" means "closest", when in reality it seems to mean "whatever `IPhysBody` was chosen first". This means that lasers will sometimes go through walls (and other things) to hit something *behind them*, just because that entity was checked first for collisions.

Changing the ray mask on my machine has revealed another issue:

  3. Lasers will not be rendered if they don't collide with anything. This means shooting a laser out the station window into space has no visual effect, since the laser is only drawn if it hits something. That should be fixed.

**Comment by ComicIronic** [comment]
The reason this has been noticed now may be due to @InquisitivePenguin 's physics changes, but it's very hard to say. The new physics engine doesn't actually seem to be at fault here.

**Comment by InquisitivePenguin** [comment]
The second point that @ComicIronic mentioned could very well be the reason for this issue. I've been meaning to do a deep-dive into how our broadphase collision detection works internally, probably refactoring it and fixing problems along the way.
