### ISSUE TITLE
Forcefeeding broke

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#10178]
## Description

It shows the other person that you are trying to forcefeed but nothing happens
**Reproduction**

Try to force feed
Nothing happens
**Screenshots**

**Additional context**

**Comment by fooberticus** [comment]
I'm not able to replicate this bug locally.

Steps I followed:

* Spawn into station
* Respawn, so I have a clone to feed (verified different UIDs between me and my clone)
* Spawn some toxic drugs, feed to my clone. Events fire as expected. Admin logs show the force feeding event correctly.
* Spawn health analyzer to confirm my clone is poisoned. Clone is indeed poisoned.

Can you retest this, and if you're able to replicate it can you provide the exact steps you took with which items etc?

**Comment by ElectroJr** [comment]
I think the issue might be that force-feeding has a shorter interaction range than the majority of other interactions, and there's no clear indication that you're not close enough. The interaction outline being green probably leads people to assume they should be close enough.

Assuming this is the problem, and there isn't some bug, the fix for this is probably to either make force-feeding/drinking generate a pop-up when they are out of range, or updating the interaction-outline to have variable maximum distance based on the held & targeted entity.

I'm leaning towards the latter, seeing as eventually it would probably be required for other interactions as well.

**Comment by DogZeroX** [comment]
Yeah that's the issue. The range of interaction is short and there was no feedback that it was failing, and players aren't normally at kissing range to do stuff.

**Comment by Emisse** [comment]
i am...,
