### ISSUE TITLE
Mobs start spinning randomly

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#10177]
## Description

If you have joined a game lately, you will see how sometimes a mob is just spinning for seemingly no reason, at a different speed.
**Reproduction**

I got no hecking clue
**Screenshots**

https://user-images.githubusercontent.com/43253663/181996563-90752f9f-aa16-4b6b-a7b4-1ca9d9021b1e.mp4

**Additional context**

**Comment by Kayek14** [comment]
this has been getting more prevalent lately it seems and the chances of it happening seem to go up as the round goes on longer. it can be fixed by opening up physics VV and adjusting their angular velocity to 0. Somehow player's angular velocity is getting set to weird numbers. Ive seen some as high as 60+

**Comment by Stealthbomber16** [comment]
https://user-images.githubusercontent.com/100171035/184580740-2ecf213d-f929-4c3d-8e49-4d3057cb53ad.mp4

**Comment by mirrorcult** [comment]
this is still happening. occasionally people will just have 90-95 angular velocity

**Comment by mirrorcult** [comment]
seemed to happen with people that aren't moving (i.e. crit or cuffed)
