### ISSUE TITLE
You can trigger airlocks by walking parallel to/away from them.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#1024]
Probably best illustrated with a [video](https://changelog.ss13.moe/static/simplescreenrecorder-2020-05-28_13.06.58.mp4)

**Comment by ComicIronic** [comment]
This is speculative, but: what happens if you hit something in the physics frame where your velocity drops to 0? I believe you would end up intersecting with it and not "colliding" with it, because the physics system ignores objects at rest.

That might explain the ability to walk into an airlock without opening it, but then walk away and open it.
