### ISSUE TITLE
ExtinguisherCabinet insert sound not play

### ISSUE THREAD

**Issue by Morb0** [space-wizards/space-station-14#10247]
## Description

Only the sound of the slot eject is played. I set breakpoint at `Insert` method that play sound and it was called only on server.
https://github.com/space-wizards/space-station-14/blob/14d361a57fbfa4b821681a5c85e8ff282fbd9694/Content.Shared/Containers/ItemSlot/ItemSlotsSystem.cs#L211-L220

**Reproduction**

- Open wallmounted fire extinguisher cabinet
- Eject fire extinguisher from cabinet
- Eject sound was played
- Insert fire extinguisher to cabinet
- No insert sound was played

**Screenshots**

**Additional context**

It look similar to this #9160

**Comment by ElectroJr** [comment]
The issue here is because the client mispredicts. The item cabinet has a whitelist that requires a `FireExtinguisherComponent`, which is server-exclusive, so the client assumes it cannot be inserted and no client-side audio gets played.

So either that just needs to be moved to shared (and I see no reason why it wasn't already), or the whitelist has to be replaced with a tag.
