### ISSUE TITLE
Unwrenched machines have no collisions

### ISSUE THREAD

**Issue by unusualcrow** [space-wizards/space-station-14#1027]
You can unwrench a machine and push it through a wall.

**Comment by ComicIronic** [comment]
This seems to be an oversight of the layer/mask definitions, not anything to do with wrenching/unwrenching machines. It's only noticeable on vending machines and computers when unwrenched because they don't collide with walls otherwise.

Specifically, vending machines and computers have no mask. Walls also have no mask. This means they don't collide, even though they're on the same layer.
