### ISSUE TITLE
Mr.Chang vending machine wrong texture

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#10370]
its showing up as a shady cig machine instead of mr.chang texture

**Comment by thekaio123** [comment]
this needs attention

**Comment by EmoGarbage404** [comment]
i have not a goddamn clue how this happened. I looked into it and it's some wizard shit.

**Comment by DoctorBeard** [comment]
The reason for this actually pretty simple. If you look in chang.yml, the inventory prototype for the vending machine, it's currently set to `spriteName: cigs`. The vending machine inventory prototypes override the sprite of the vending machine that way. To fix this immediately you'd just change that to `spriteName: changs`, but it's fixed in my vending machine cleanup PR as well because I removed that override mechanism from the inventory prototypes entirely. It's never actually used in any meaningful way and only leads to weird inconsistent behavior like this.

**Comment by Peptide90** [comment]
> i have not a goddamn clue how this happened. I looked into it and it's some wizard shit.

Yeah it seems to be a new issue because it used to work. I noticed it yesterday.

**Comment by DoctorBeard** [comment]
> Yeah it seems to be a new issue because it used to work. I noticed it yesterday.

From the looks of it chang.yml had the wrong spriteName configured ever since it was added but the vending machine visualizer was updated to actually do the sprite replacing a little under a month ago. That'll be when this started happening.
