### ISSUE TITLE
Change storage inventory to only remove when a hand is free

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#1061]
This is something to discuss. Should clicking on items in storage inventories like backpacks take them out and drop the on the ground if your hands are full? I'd prefer if it didn't take things out if hands are full so that I don't accidentally drop things on the ground.

**Comment by ComicIronic** [comment]
Yeah, it definitely shouldn't do that, particularly because it makes no sense - if your hands are full, how are you getting something out of storage?

I don't know what the SS13 behaviour is - I think it calls `AttackBy` on the object in storage with the object in hand, which we may or may not want. Otherwise, trying to swap what you're holding with what's in storage might be a sensible default as well.

**Comment by ShadowCommander** [comment]
In SS13, it only allows you to take an item out if your active hand is empty, so it created the need for a lot of hand management. I feel like it'd be better to make it take out of the backpack into the active hand or if not any available hand, but not drop the item on the ground.

**Comment by Jackw2As** [comment]
swapping the current item in the hand makes the most sense to me because its what the player is trying todo. However it should only work if your able to put your item in your hand in the container. Otherwise it should let the player know they can't do that. Perhaps with some kind of beep sound.
