### ISSUE TITLE
Better eye damage filter

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#10738]
See #10728 and #10717

The current shader is **way** too mild.
It should be an inconvenience to the player, but not cause discomfort or hurt/strain to look at after a prolonged period of time.
It could be some kind of blur, but not one like the original eye damage filter. Alternatively, some people like PJB or Emisse suggested having "blotches" that obscure part of your vision.

**Comment by PJB3005** [comment]
> It could be some kind of blur, but not one like the original eye damage filter. 

No, it cannot be a blur effect. A permanent blur effect on your vision is what causes the eye strain, no matter the form.

**Comment by moonheart08** [comment]
A partial solution would probably be "the original shader, but the 3m radius circle around the player is unaffected"

**Comment by Zumorica** [comment]
Maybe covering the screen with 'fog' or white noise?

**Comment by Visne** [comment]
I would prefer a temporary gaussian blur around your player just after sustaining eye damage, to make it really clear that you are fucking up your eyes and to have a similar effect to a flashbang, because in real life you will also be much more blinded just after sustaining eye damage than later. Then, permanently a vignette could be applied which slowly encroaches towards your player as eye damage increases. Perhaps the screen could also get more black and white as you get more eye damage.

**Comment by EmoGarbage404** [comment]
Blurs are awful for a few reasons
1. Blurs cause eye strain and should never be used for long term or permanent effects
2. Blurs look fucking ugly with pixel art
3. Blurs arent a mechanical disadvantage unless combined with other effects.

**Comment by Visne** [comment]
> Blurs cause eye strain and should never be used for long term or permanent effects

Not if the center of the screen is not blurred. As far as I know, the eye strain comes from your eyes not being able to find something to focus on.

> Blurs look fucking ugly with pixel art

They do? Can you give a few examples?

> Blurs arent a mechanical disadvantage unless combined with other effects.

It stops you from seeing detail at a further range, I don't see how that is not a disadvantage (but maybe I don't fully understand what you mean with mechanical advantage).
