### ISSUE TITLE
Server should notify players when a new round is starting

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#10780]
## Description
I recall an early discussion of how the server should message discord with something like `@New Round Ping | GAME: New round starting on <map>`, and something about how it should be done in the launcher. I lost it though, how about we discuss on Github instead?

**Comment by Visne** [comment]
Use WebSockets to connect all people looking at the hub to the servers. The servers then provide live player amounts and send a notification when a new round is starting (to players that want this).

While WebSockets are extremely cheap, they still cost resources, so if there are ever over 10k people looking at the hub at the same time, it might be too much. Would have to test how much resources that takes first though, because I think even 10k might be easy to handle.

**Comment by Pangogie** [comment]
Server pings when a round ends, indicating that a new round is about to start.
