### ISSUE TITLE
Dead snake still has animated tongue

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10848]
## Description
Dead snake still has animated tongue. Duh!

**Reproduction**
- Kill a snake
- Watch the dead snake

**Screenshots**
![dead_snake](https://user-images.githubusercontent.com/108953437/186501392-df377663-00ac-49a1-978d-d03b5b809bb8.png)

**Comment by biometricPsychography** [comment]
https://github.com/space-wizards/space-station-14/blob/c9f43f364679596e673dbbe79c35946a4f350759/Resources/Prototypes/Entities/Mobs/NPCs/animals.yml#L1236-L1241

It looks like @FoLoKe commented out the death visual because it didn't look good. 

The death state results in the death animation looping infinitely which, yeah, doesn't look good. 

Someone could create a death sprite that is static as a quck fix. I could possibly work something cruddy up that would be serviceable. I'm thinking just giving the snake "X"s for eyes. But the commenting talking about differentiating between dying and dead seems like it would be the ideal outcome. Then we could have death animations. (I'm assuming that hasn't been implemented yet as I'm just starting to familiarize myself with the codebase.)
