### ISSUE TITLE
Fuel tanks will still explode even if they are empty.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#10924]
## Description
If a empty fuel tank is hit with a lit welder it will still explode.

**Reproduction**
1. Find a fuel tank.
2. Empty the fuel tank.
3. Hit the fuel tank with a welder.

**Additional context**
Oddly enough, you cant refill a welder off of a empty fuel tank but you can still explode it.
Not sure if any form of explosion will cause the empty tank to explode or only if a welder will, I only tested it with a lit welder.

**Comment by Kamushy** [comment]
Makes sense, there is still fuel residue, it works like this in real life

**Comment by Stealthbomber16** [comment]
bug replicated irl!!

**Comment by Carbonhell** [comment]
Instead of simply hardcoding a check for empty fuel tanks, I believe the correct way to go about this is by relaying heat applied to the tank, to the solution. Then, by specifying a temperature condition, if the welding fuel reagent reaches a certain high temperature it reacts and causes the explosion.

This would be more generic and it'd work for different containers as well, not only welding tanks.
