### ISSUE TITLE
Clientside container exception when nuking Saltern

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#10935]
## Description

```
[ERRO] root: Failed to apply comp state: entity=12170, comp=Robust.Shared.Containers.ContainerManagerComponent
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Expecting entity ChemMaster 4000 machine board (10798, ChemMasterMachineCircuitboard) to be present in two containers. New: machine_board in machine frame (12170, MachineFrame). Old: machine_board in Chem
Master 4000 (5057, chem_master)
```

**Reproduction**

1) `forcemap saltern`
2) `restartroundnow`
3) `nukearm 5`
4) crash ?

**Screenshots**

**Additional context**

**Comment by ElectroJr** [comment]
AFAICT this is just an issue where an entity gets moved from container A to container B, but the state for the owner of container B is applied before A. So the assert just needs to be updated, because what's happening is allowed to and expected to happen in some situations. But the container code also needs to be changed to handle that scenario.
