### ISSUE TITLE
Turrets are way too loud

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11071]
## Description
A turret going full auto is way too loud, completely drowns out other sounds even from across the room. I play with the game at ~50% volume, I weep for those who have the game sound cranked up too high.

**Additional context**
These were the shotgun turrets.
Lets try not to bust any headsets.

**Comment by metalgearsloth** [comment]
Is this a general gun problem? They're all the same volume.

**Comment by Kayek14** [comment]
Hmm perhaps, but guns usually only shoot a limited number of times. The turret in question leading to the creation of this issue was firing shotgun shots full auto. That might have been the reason for it sounding so loud.

**Comment by retequizzle** [comment]
can confirm, I was playing with shotgun turrets and they're loud only because of how fast the fire rate was (i cranked it to 15)

standard turrets are a lot quieter just on the premise that they're shooting .25 caseless compared to shotgun shells. default turrets should be fine, this is more indicative of being reasonable with admeme alterations rather than an issue with turret design/sound itself

**Comment by Kayek14** [comment]
This issue only seems to apply to a very specific admeme circumstance and does not seem to be a problem.
