### ISSUE TITLE
Pinpointer dont work

### ISSUE THREAD

**Issue by estacaoespacialpirata** [space-wizards/space-station-14#11132]
## Description
Pinpointer dont work

**Reproduction**
spawn a pinpointer, activate it, it dosen't work.

**Comment by Macoron** [comment]
@ElectroJr it looks like recent robust update broke pinpointer visualizer.
https://github.com/space-wizards/RobustToolbox/pull/3233

Here what happens:
1. Pinpointer got dirty on server
2. Send info by pinpointer component state
3. Client pinponter system receive component state
4. Tries to change it appearance on the client
5. But `_timing.ApplyingState` is true
6. So it skips all changes

Tbh, pinpointer client system should be appearance system and don't use component state. But it can probably broke some other visualizers.

**Comment by ElectroJr** [comment]
There is one issue with the engine PR, where `_timing.ApplyingState` should be updated to `_timing.ApplyingState && component.NetsyncEnabled`, but the problem here is that the client-side system is setting data on a networked component. Either the appearance data has to be set in server/shared code, or the appearance component needs to not be networked (which would work once the engine check is updated to consider `NetsyncEnabled`).
