### ISSUE TITLE
Telecomms

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1117]
Related to #952 
Radios and stuff for communicating across the station or while in spess.

**Comment by Bright0** [comment]
For communicating across the station I'd say we should grab the intercom system from ss13 and just make it compatible with the identity system/PDA comms system we want. I imagine you could plug in your ID to an intercom and request to link up with a target intercom which will see your ID and choose to respond, then hear your voiceprint when speaking through it. Instead of broadcasting to a common channel by default intercoms could also be the way people see/read announcements like a proper space station instead of getting brain blasted the info.

**Comment by PJB3005** [comment]
That sounds extremely overcomplicated and just going with a dead simple system seems preferable.

**Comment by Bright0** [comment]
Sorry, I was thinking too far ahead cuz I'm retarded. Should radios pop a message over your head or send a message to the chat box?

**Comment by RemieRichards** [comment]
@Bright0 both.
1: the message in the chat for people who can't currently see you, who have radios on the right channel
2. the message over your head for the people who CAN currently see you, since just as in SS13, you should also "say it outloud"

people who get 2. should also get 1., but not vice versa.

**Comment by F77F** [comment]
what else is needed before this is closed? does https://github.com/space-wizards/space-station-14/pull/2023 not close this?

**Comment by Zumorica** [comment]
I'd say this can be closed, ye.
