### ISSUE TITLE
Condensing gasses into chemicals should be possible 

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#11319]
Though probably not vice-versa without careful balance work.

This means Oxygen, Nitrogen, Plasma (this is somewhat important so maybe make it not condense by normal means), Water Vapor, Nitrous Oxide, Tritium, and CO2 should be convertible to chems via some machinery.

**Comment by Elijahrane** [comment]
Could we standardize mols <-> u? Maybe including molar mass?

**Comment by Cheackraze** [comment]
> Could we standardize mols <-> u? Maybe involving molar mass?

pv=nrt. How much volume is a u? going roughly off the size and containers in game already, a shot glass is 10u, so 1u would be about 5ml

**Comment by moonheart08** [comment]
I tried actual math and it was pretty useless, so arbitrary contrived solution: 1mol = 1u.

**Comment by Cheackraze** [comment]
it would depend on pv=nrt for real life. For instance, in 1atm, liquid oxygen 1mol = 28 ml, and boils at -183c.

though we really don't handle boiling/freezing of gasses right now, they just exist at those temps and pressures as a gas eternally, so you could just blame spess magic and pick some arbitrary values.

Requiring the gases to be at certain temps for the machine to convert them might be engaging gameplay however. especially since most of the gasses atmos deals with have boiling points in the -190c range. It could require atmos to get cans of gasses at specific temps. i.e. oxygen, nitrogen, co2 around -200c to get base oxygen, nitrogen and carbon chems. more exotic chemicals could use miasma or plasma cooled below -200c with the help of frezon to get radium, sulfur, uranium, or others.

my ultimate question would be, the condenser would be something that requires pipes and gas inputs then I assume? a single machine would then have a max of 4 pipe inputs/outputs ideally so fitting all 7-9 gasses in seems like an issue

**Comment by Partmedia** [comment]
One hackish way to do this would just be to introduce a machine that condenses some portion of gases that flow into it.

I think implementing condensation would be better. I'd do this by giving each pipenet node container a "condensate" solution container. Then, based on energy, gases, and pressures in the container, move gas from the air pipenet nodes to the solutions and vice versa. I'd probably opt *not* to implement fluid flow, i.e. condensate stays in the pipenet it formed in and doesn't flow through other devices. The only additional "machine" you'd need is a tap to extract the condensate from a pipenet.

Responding to suggestions in the comment above:

- The ideal gas law is for ideal gases, not liquids. $PV = nRT$ doesn't apply. The physically accurate thing to do would be to work through molar mass of the liquid (which is different from molar mass of a gas), as someone pointed out above. This would be a constant for each liquid you either look up or make up.
- My suggestion would give you a condensate mixture of all the gases condensed at whatever temperature you've managed to get the pipe to. It would be up to you to separate the liquid gases ~~*cough* chem master *cough*~~. Real cryogenic plants use a molecular sieve followed by fractional distillation to separate liquid gases.
- There's a complex system of equations for determining the equilibrium fraction of condensed vs. vapor phase gas. At high pressures enough pressures, even room (or higher-temperature) gas can be forced into liquid form. This is what keeps the pressure vessel of a boiling water reactor from exploding, for example. Fortunately, I already have a code version of the solved equations for water vapor ~~for a nuclear-reactor AME replacement~~ from an earlier project that could be extended to other gases.

**Comment by Partmedia** [comment]
Sure, a flag to disable condensation should be trivial to add, and also help with debugging if things go wrong.

That said, freezing out the external pipes could be an interesting mechanic. Have you wondered why real spacecraft are essentially dead if their internal heaters fail? (it actually has more to do with all the electronics freezing out, but we'd still end up in the same situation where the spacecraft/station is dead)

**Comment by theashtronaut** [comment]
Yeah, I talked myself into the idea being potentially cool. Like I said it would be something worth playtesting to see if it's actually good or not!

**Comment by Putnam3145** [comment]
I have 0.2u/mol on [Citadel's implementation of chem gases](https://github.com/Citadel-Station-13/Citadel-Station-13/blob/e5c562b4bcc48a755252f65278b292435ecf72bf/code/modules/reagents/chemistry/reagents.dm#L83), mostly because 120 moles is actually quite a lot (throw a full large beaker of hot water and you've more than doubled the pressure in that tile, at 1u/mol).

**Comment by Partmedia** [comment]
Here's a video of freezing a pipe such that the gas inside it condenses into liquid inside the pipe. Gas analyzer can't analyze liquid inside the pipe, so the gas "disappears". Machine to drain the liquid from the pipe coming soon:

https://user-images.githubusercontent.com/3229565/223955278-9c81b169-377b-4c77-a68f-e6ec1cca1f09.mp4
