### ISSUE TITLE
Windows/Menus are not closed when disconnecting

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#1132]
When the user disconnects or the server closes some windows are not closed.

Some windows that don't close:
- Tutorial
- Sandbox Panel
- Vending Machine
- APC
- Airlock Control

Some windows that close:
- Escape Menu
- Inventory
- Construction

Expected Behaviour: All windows should close when going back to the main menu

Whoops: already issued in #963

**Comment by SweptWasTaken** [comment]
Duplicate issue of [this](https://github.com/space-wizards/space-station-14/issues/963).

Also [this](https://github.com/space-wizards/space-station-14/issues/399) and [this](https://github.com/space-wizards/space-station-14/issues/616).

Will leave this one open and close mine since this is a little more comprehensive.

**Comment by exp111** [comment]
The Construction menu gets closed, but the button is still toggled on. Maybe reset those on connect?
