### ISSUE TITLE
Remove the chem dispenser for good.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#11345]
## PREREQUISITES
- [x] https://github.com/space-wizards/space-station-14/issues/11316
- [ ] https://github.com/space-wizards/space-station-14/issues/11317
- [x] https://github.com/space-wizards/space-station-14/issues/11320
- [x] https://github.com/space-wizards/space-station-14/issues/11321
- [x] https://github.com/space-wizards/space-station-14/issues/11319
- [x] https://github.com/space-wizards/space-station-14/issues/11339

## idk mixing chems manually is kinda bad
A "dispenser" should remain an option but it shouldn't produce chems at all. Simple.

**Comment by Illiux** [comment]
I feel like it's probably better to get rid of the dispenser and try to fix ergonomics of mixing chems manually some way. Reducing the dependence on machines opens the system up more to other roles.

**Comment by S1ss3l** [comment]
We could try to balance the map to have thing like O, C & H source supplied by atmos, like condenser of some sort already installed in chem. You could also have a large base reserve of P, sugar, Cl and Na to kick start the production, especially in LRP. That would make sustainable renewable source of those element still needed while allowing chem to produce early reserve of med too.
One thing that could be interesting too would be to allow plant based medicine. Like extracting chemical from plant, it would be cheaper/quicker to make than proper medicine and less effective too.
Also also we need surgery.

**Comment by mirrorcult** [comment]
> One thing that could be interesting too would be to allow plant based medicine. Like extracting chemical from plant, it would be cheaper/quicker to make than proper medicine and less effective too. Also also we need surgery.

we already have this sorta with poppy/lingzhi/galaxythistle etc. its pretty good as a concept and I think will become a lot more important

**Comment by S1ss3l** [comment]
That would require expanding the botany department in some map though. I didn't play much but from what I recall there are certain map that are a bit short in the number of hydroponics bed to both supply kitchen and chem if this is implemented.

**Comment by PilgrimViis** [comment]
As mentioned above, chemists already have troubles of producing drugs right now. Imagine if chemists should also be gathering resources from cargo, Atmos and botany to make the basic drugs, it would be a complete disaster. I think now it's working perfectly fine. You can make basic drugs, but if you want to do advanced one you will need to ask botanists to grow things (e.g. Stellibinin) and ask cargo to gather resources (e.g. Uranium, plasma). I think it's good to go in that direction. Basic drug's components available instantly, advanced drugs should be created with help from other departments.

**Comment by QuietlyWhisper** [comment]
I've seen chem dispencers in ss13 have a limited amount of units they could give before they ran out and needed to be resupplied by cargo or something like that... would be great to produce medicine early game before needing sources from cargo/botany/whatever... maybe have the dispensers be able to be refilled? If youre removing the machine entirely... that might mean medical needs a rework overall... when it gets busy in medical, even with a steady supply of meds it can get bad

**Comment by QuietlyWhisper** [comment]
If you mean to say they have limited chems like vending machines but with units, that need to be restocked, I'd very much like that personally

**Comment by QuietlyWhisper** [comment]
Cargo still needs better ways to get money though, theyre still very limited currently without help from atmos or botany

**Comment by Slava0135** [comment]
> I feel like it's probably better to get rid of the dispenser and try to fix ergonomics of mixing chems manually some way. Reducing the dependence on machines opens the system up more to other roles.

I think medicine need to be more potent, because right now you need 100s units of chems. So you pretty much have to use large beakers.

And what if chem dispenser with chems inside breaks? It will be 1000s units of liquids spilled and what if they react? (potassium + water from tank = insane boom)

Note on pills - you can put 50u in one. Then you can put 9 in a pill can. Which is 450u in total (beaker is only 50u, and bottle is pathetic 30u for the same size, i think it needs a buff). Pill size should be 10u in my opinion (with more potent chems it will be ok)

**Comment by deltanedas** [comment]
related to potency, we need stronger brute meds
10u of bicaridine would be laughable
dylo has stellibinin/siderlac, what about bicar?

**Comment by CaptainSqrBeard** [comment]
<details>
<summary>me crying</summary>
YES I want to walk in cargo to order some chems and wait half of the round. I wanna suffer from a lack of any chems for no reason. Let me WALK more than actually BREW! Make my role completely dependent to cargo, salvagers, botany and atmos. I wanna see people suffer from brute because chemist still waiting carbon to make bicardine. I wanna see how cargo being destroyed by horde of zombies and realize that no one now can give me resources to make romerol. This would be totally fun especially after we removed free bottles and made them hard to fill in chem master.
</details>

Why we just not make dispenser with power cell that will slowly regenerate its power for creating reagents? This must solve the problem. Also it makes dispenser actually upgradeable.

I see no reason why chemists must fully depend to a lot of departments. This is not fun. Everyone will suffer if chemist will be unable to brew anything because random department can't work or ignore him. Not to mention low-pop rounds where some departments may be empty.

In my opinion features from milestone can be good for ghetto chemistry and chemistry itself but chem dispenser must stay and just be limited.

**Comment by deltanedas** [comment]
> after we removed free bottles and made them hard to fill in chem master. 

don't bother with chem master for bottles, just pour and label

**Comment by deltanedas** [comment]
> Why we just not make dispenser with power cell that will slowly regenerate its power for creating reagents? This must solve the problem. Also it makes dispenser actually upgradeable.

yeah would be interesting if power was actually used so tier 4 capacitor = you can crank out meth like theres no tomorrow but default = no more schizos making 200 25u bicar pills 4 mins in

**Comment by Partmedia** [comment]
This is available on Mining Station 14. You have to fill the chem dispenser with chemicals you order from cargo before it dispenses anything.
![image](https://user-images.githubusercontent.com/3229565/223575671-44109ee6-db77-40ca-ac74-1c5ef53d1a88.png)
