### ISSUE TITLE
ILand is broken.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1141]
Steps to reproduce:
1. Spawn dice.
2. Throw dice against a floor and notice it doesn't roll.
3. Throw dice against a wall, airlock, closet, etc and notice it does roll.

Land interaction is only being raised when colliding with something, making ILand useless in cases like this.

**Comment by RemieRichards** [comment]
Needs triggering in `ThrowController.StopThrow()`

This call to `LandInteraction()` here: https://github.com/space-wizards/space-station-14/blob/18ce80a43c0c27542ca466647a1ce8af67809c68/Content.Server/GameObjects/Components/Projectiles/ThrownItemComponent.cs#L59
Can be removed then too because of the `StopThrow()` call above it.

**Comment by Zumorica** [comment]
That's pretty much how to solve this issue! Sadly, `ThrowController` is in `Content.Shared` so this might require either moving `ThrowController` to `Content.Server`, or moving `ILand` to `Content.Shared`.

**Comment by Zumorica** [comment]
An alternative might be invoking an event on `ThrowController` which calls `LandInteraction()` server-side.

**Comment by RemieRichards** [comment]
Hmm... why does it need to be in shared? it seems to only be used server-side anyway.

So kind of future-proofed "also do throwing on the client"?

**Comment by Zumorica** [comment]
> So kind of future-proofed "also do throwing on the client"?

Seems so. Maybe the people who've worked more closely with the new physics engine have an explanation for this

**Comment by DrSmugleaf** [comment]
Fixed by bc24a852f901bef23c739b9316dadd0e865f35c5
