### ISSUE TITLE
Plastic flaps no longer let in crates

### ISSUE THREAD

**Issue by KiwiApteryx** [space-wizards/space-station-14#11672]
## Description
Plastic flaps are no longer letting any half sized items go under them, making cargo a bit more annoying.

**Reproduction**
attempt to put a crate under plastic flaps, it no worke.

**Screenshots**
![6debe73c8a1be6fdecd823c39f30334a](https://user-images.githubusercontent.com/114881792/193515500-927b1e00-4e58-4128-b798-6d205533da95.png)

**Comment by themias** [comment]
I've done some testing, and the issue seems to be with the blast doors, rather than the flaps.
Their collision seems to be turned back on when the conveyer belt is activated. I think it may be related to this change: [#3529](https://github.com/space-wizards/RobustToolbox/pull/3259) 
Someone smarter than me would need to take a look at the potential fix for it.

An in-game workaround is to either close/reopen the blast door after the belt is activated, or just turn the belt on before opening the door.
