### ISSUE TITLE
Constructing machines creates a duplicate board when completed

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#11733]
## Description
So apparently when constructing a machine (only tested with chem dispenser and master so far) you get the boards back when you finish constructing the machine. This is probably already reported on but i figured i would drop one just in case....

**Reproduction**
1. start building a machine
2. put all components in
3. screwdrive to finish
4. machine finishes but gives you the board back
5. ummm.gif

**Comment by Vordenburg** [comment]
Git bisect led me to commit c5552034012848457e008598a54540fb7726ed9e as the potential origin of this issue, which did not build, but the next commit cb2d2b426b32b05716b957f653f10434bce2e51 did, and that commit has this issue, whereas commit 3b763192b024ecebffa9850d986cd8b7584508b0 did not. As of this writing, master at commit a0eb543176327ccaab9bbf50714c724dcc3508e6 no longer has this issue, and the earliest commit before that which I can find that builds which has this issue is 0048dc59197ef27fb0443a7837818449c45e9122.

@metalgearsloth  Was this due to the container tweaks performed in RobustToolbox? It seems they've been reverted recently.

**Comment by EmoGarbage404** [comment]
this was fixed, probably with the various container bugfixes.
