### ISSUE TITLE
You can see APCs, lights, etc behind walls

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#1238]
![image](https://user-images.githubusercontent.com/52793290/86066775-00729e00-ba6b-11ea-84ec-fc62df704494.png)

In SS13, this doesn't occur because as you know they aren't placed directly on the walls, as they are on placed on the adjacent tile then pixel shifted.

This is all probably intended but strange shit could happen in the future when you see someone building wallmounts behind a wall.

**Comment by GlassEclipse** [comment]
With my newfound opengl autism knowledge I wanted to try and tackle this but I'm not sure there's an easy solution given how the bbs are:
![Screenshot 2020-11-14 18 03 30](https://user-images.githubusercontent.com/32942106/99159639-db8e6880-26a3-11eb-961c-8ae5bbda31d8.png)
Any thoughts on the matter? With our perspective walls I thought maybe one way to fix it would be to cut off FOV based on the perspective instead of based on the tile, but that seems rather complex and error-prone.
![86066775-00729e00-ba6b-11ea-84ec-fc62df704494](https://user-images.githubusercontent.com/32942106/99159680-58b9dd80-26a4-11eb-9f4a-b64e42d353a1.png)

**Comment by moonheart08** [comment]
Something to note is that while lights are rotated, APCs are not, they're interactable from all 4 sides of the wall at any time.

**Comment by juliangiebel** [comment]
Is this even still an issue?

**Comment by Emisse** [comment]
no
