### ISSUE TITLE
Maps with non-default atmos and/or parallax (nukie planet, ...) broke

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#12634]
## Description

**Screenshots**

![image](https://user-images.githubusercontent.com/60792108/202283450-a0b23d1c-0e7e-4063-bd36-d1e40178b650.png)
nuke op planet is space now

probably related to maploader changes

also affects glacier on nyano

**Comment by metalgearsloth** [comment]
nukieplanet was saved as a grid.

**Comment by Cheackraze** [comment]
> nukieplanet was saved as a grid.

Probably my fault but when I asked how I should save it I was told savegrid, how does it need to be saved, as a map?

**Comment by metalgearsloth** [comment]
> > nukieplanet was saved as a grid.
> 
> Probably my fault but when I asked how I should save it I was told savegrid, how does it need to be saved, as a map?

yeah. When I told you grid I was thinking of infiltrator.

At least this doesn't break master anymore.

**Comment by Vordenburg** [comment]
@metalgearsloth  This appears to be because SwapRootNode in RobustToolbox's MapLoaderSystem is replacing the saved entity that had the Map component with Parallax and MapAtmosphere, with an entirely new entity lacking all of this.

It's following the code path starting here: https://github.com/space-wizards/RobustToolbox/blob/4e0deb2e423c9d100141dada33c8bf88038802d1/Robust.Server/GameObjects/EntitySystems/MapLoaderSystem.cs#L490

**Comment by metalgearsloth** [comment]
@Vordenburg that's intentional.

Fixed in #12650
