### ISSUE TITLE
Pill canisters don't fit in coats

### ISSUE THREAD

**Issue by Rapidgame7** [space-wizards/space-station-14#12901]
## Description
Pill canisters weigh 5.
Lab coats have a space of 10.
Pill canisters refuse to enter coats due to "Insufficient capacity".

**Reproduction**
- Get coat
- Get pill canister
- Click coat with canister
- Opposite of profit

**Screenshots**
![image](https://user-images.githubusercontent.com/14862618/205837282-069d2f27-a61b-4eae-b22b-ddba5fed131b.png)

**Comment by Theomund** [comment]
I was able to reproduce this issue, and I did a little investigation into it by using a debugger. It seems that this block of code is responsible for this behavior:

https://github.com/space-wizards/space-station-14/blob/920bad3dc631e66fe7a1bd164fc4f0aba0101d9d/Content.Server/Storage/EntitySystems/StorageSystem.cs#L556-L561

In this case, the pill canister has a maximum storage capacity of 12. On the other hand, the lab coat's storage component has a maximum storage capacity of 10. Due to the pill canister having a greater maximum storage capacity, the server refuses to store it inside the lab coat.

I'm currently investigating a way to resolve this.

**Comment by QuietlyWhisper** [comment]
It seems like any container with a larger capacity will not fit in a smaller capacity container with how storage currently works. It's to prevent infinite storage by placing multiple containers inside of eachother if I remember correctly!
Theres two ways you can resolve this that I can think of;
1. Raise pill bottle weight to 12 and have it not fit in coats at all, at the additional cost of taking up more space in bags.
2. Lower pill bottle capacity to 10, which will likely mess up chemists who like to mass produce pills, but will allow them to fit in coats (likely two of them if I'm right!).

**Comment by QuietlyWhisper** [comment]
It seems like any container with a larger capacity will not fit in a smaller capacity container with how storage currently works. It's to prevent infinite storage by placing multiple containers inside of eachother if I remember correctly!
Theres two ways you can resolve this that I can think of;
1. Raise pill bottle weight to 12 and have it not fit in coats at all, at the additional cost of taking up more space in bags.
2. Lower pill bottle capacity to 10, which will likely mess up chemists who like to mass produce pills, but will allow them to fit in coats (likely two of them if I'm right!).

**Comment by Theomund** [comment]
> 2. Lower pill bottle capacity to 10, which will likely mess up chemists who like to mass produce pills, but will allow them to fit in coats (likely two of them if I'm right!).

Unfortunately that would not work because the maximum storage capacity of the pill canister would be the same as the lab coat. It would fail the "greater than or equal" check shown in the above snippet.

**Comment by Theomund** [comment]
> 1. Raise pill bottle weight to 12 and have it not fit in coats at all, at the additional cost of taking up more space in bags.

I don't think we would want this change. If I remember correctly, you were able to stick pill canisters into lab coats without a problem in Space Station 13.

**Comment by Emisse** [comment]
we did this because of nested storage being extremely powerful and abused early on, although i do think pill canisters should be able to fit in coats probably

**Comment by QuietlyWhisper** [comment]
Seems like the best option would be to change the evaluation to just "greater than"
Otherwise we're looking at <10 capacity pill bottles...
Would this effect anything? The nested storage exploit should only happen if you have enough space to place another container inside it? I'm unsure if "or equal to" is needed-

**Comment by Theomund** [comment]
> Seems like the best option would be to change the evaluation to just "greater than" Otherwise we're looking at <10 capacity pill bottles... Would this effect anything? The nested storage exploit should only happen if you have enough space to place another container inside it? I'm unsure if "or equal to" is needed-

I believe that the "equal to" part is needed, otherwise you would be able to stick a pill bottle inside another pill bottle (if there wasn't a whitelist/blacklist), since they both would have the same maximum storage capacity.

Having less pill capacity might be our best option. [According to their wiki](https://tgstation13.org/wiki/Medical_items), the TG community seems to have settled on 7 pills or patches per pill bottle container. This isn't to say that we should adopt their capacity number, but it could be a good starting off point for a discussion.

**Comment by Emisse** [comment]
simplest solution to me sounds like making some sort of opt out for the nested storage test incase something like this arises in the future with something else

**Comment by QuietlyWhisper** [comment]
Might be safe about it and have "small" and "large" pill canisters, small being the portable size with 5-9 pills or whatever, for doctors and whatnot to carry in coats/belts/etc, where large could store a lot more (10-20?) but have the same weight as their capacity, making players avoid carrying them? (I'm pretty sure not many people like carrying the survival kit they spawn with!)
It would be helpful for the mass produce chemists and allow cleaner chemist front counters perhaps?
And in terms of small canisters, chemists wouldn't have to worry about having no canisters to use, as the doctors would prefer the efficent canisters!

Sucks we can't just set the capacity to 10 and be done with it. Nested storage can be very bad.

Either way it seems we're going to be dropping the standard canister capacity to resolve the bug. I just figured another option for packing and sorting pills would be nice while allowing doctors to keep the standard canisters!

**Comment by QuietlyWhisper** [comment]
Submitting this until someone more capable can make a check opt out.
#13220

**Comment by Theomund** [comment]
I believe this issue can be closed. It was resolved by the merge of #13220.
