### ISSUE TITLE
Singularity generator does not work

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#13117]
## Description

Particle accelerator does not produce a singularity at any setting, despite particles hitting the singularity generator.

**Reproduction**

Wrench down singularity generator in front of particle accelerator.
Turn on particle accelerator.

**Screenshots**

**Additional context**

Emitters should be powered by heavy voltage wires.

**Comment by EmoGarbage404** [comment]
Emitters are powered by MV.

**Comment by Cheackraze** [comment]
The PA requires HV already, the PA computer requires LV, and the emitters require MV, o think this is the perfect amount of complexity.  Making the emitters require HV means you don't need to run a separate line to them and can just piggyback off from the collector wiring, where we should be aiming to make the singularity more complex to deal with instead of simpler, so I disagree with that change

**Comment by GoodWheatley** [comment]
Pretty sure what this guy is trying to actually say is that the singulo generator isn’t actually generating a singulo when the PA shoots it.

**Comment by moonheart08** [comment]
> They are indeed powered by MV, but I wrote they should be powered by HV. In my opinion.

That's unrelated to the issue so..
Not being changed.
