### ISSUE TITLE
Carpotoxin has incorrect discription when examined.

### ISSUE THREAD

**Issue by C2Gamser** [space-wizards/space-station-14#13142]
## Description

Carpotoxin, when in a beaker and shift clicked/examined shows up as "reagent-physical-desc-exotic-smelling" which is incorrect.
**Reproduction**

Put carpotoxin in a beaker and shift click/examine it, it should be incorrect.
**Screenshots**

WHEN EXAMINED:
![image](https://user-images.githubusercontent.com/121264000/209231697-13f710ad-af2f-46b4-961d-b84e4694d5e8.png)
WHAT IT ACTUALLY IS:
![image](https://user-images.githubusercontent.com/121264000/209231789-9df0eac1-dd7d-4dfa-8579-9ed57bd5619b.png)
**Additional context**

Found while playing on the server www.nyanotrasen.moe

**Comment by Theomund** [comment]
This should be an easy fix. The reason why it's displaying like that is because there's no entry in [`Resources/Locale/en-US/reagents/meta/physical-desc.ftl`](https://github.com/space-wizards/space-station-14/blob/920bad3dc631e66fe7a1bd164fc4f0aba0101d9d/Resources/Locale/en-US/reagents/meta/physical-desc.ftl) for that locale string.

I will attempt to fix this sometime today.

**Comment by Theomund** [comment]
This issue can be closed. It was resolved by the merging of #13211.
