### ISSUE TITLE
All pop-up text seem to have increased in size

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#13175]
## Description

**Reproduction**

**Screenshots**

![image](https://user-images.githubusercontent.com/43253663/209451933-9acf47b8-355c-4a6d-b415-7cf98bc5a723.png)

**Comment by ShadowCommander** [comment]
Seems to be intentional unless your UI scale is 100%.  #13169

**Comment by DogZeroX** [comment]
It's at 75%, I'd say this looks rather wacky and too big.

**Comment by EmoGarbage404** [comment]
It looks pretty normal to me tbh

**Comment by dmnct** [comment]
Popup text was abnormally small when using large UI, because it stopped scaling. I just ran a quick comparison and the size seems normal to me at all sizes, this is what (I assume it's intended to) look like
![image](https://user-images.githubusercontent.com/35878406/209464248-c3287f71-b934-4597-8cfe-899df0081141.png)

your image does seem to be closest to (my) 200% UI Scale text size. Are your speech bubbles on the same scale?
