### ISSUE TITLE
Status effect prediction is completely broken again

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#13295]
## Description

![image](https://user-images.githubusercontent.com/19853115/210288464-213b908e-e14a-4c8a-8056-0d4ecde66fbf.png)

**Reproduction**

**Screenshots**

**Additional context**

**Comment by ElectroJr** [comment]
If this is just the one-tick stutter thing, AFAIK this is probably just the issue with collision start/stop mispredicts and not status effects, E.g., I haven't noticed any mispredicts after giving soap entities a slip-on-use-interaction and directly triggering a slip. The stutter only happens when relying on collision start/stop events.

**Comment by mirrorcult** [comment]
i had a similar mispredict occur with other status effects but didnt get video

**Comment by Reaverblade** [comment]
Got bad ui statuses while being a pAI and, after ghosting, the statuses persisted.
Made a bug report and got linked to this issue.
Pictures following of bad ui statuses:
![Bad status as pAI closeup 2023-01-02 15-52-40](https://user-images.githubusercontent.com/3865130/210668853-3fec59d4-3c37-4755-a964-544bef60f116.png)
![bad status as ghost after pAI 2023-01-02 16-11-35](https://user-images.githubusercontent.com/3865130/210668858-2a7a665a-3b67-452d-a506-1d68f327b307.png)

**Comment by mirrorcult** [comment]
i think i was wrong or it was fixed
