### ISSUE TITLE
CC BY license is unsupported even though it's one of the most common CC licenses

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#13464]
## Description

**Reproduction**

1. Look at https://creativecommons.org/licenses/
2. Pick the very first license with the least restrictions because you are nice.
3. [$.license] 'CC-BY-4.0' is not one of ['CC-BY-SA-3.0', 'CC-BY-SA-4.0', 'CC-BY-NC-3.0', 'CC-BY-NC-4.0', 'CC-BY-NC-SA-3.0', 'CC-BY-NC-SA-4.0', 'CC0-1.0']

**Comment by Jezithyr** [comment]
Creative Commons is not designed for software and as such it does not wave liabilities or warranty for software use. Did you read the license? https://github.com/space-wizards/space-station-14/blob/master/LICENSE.TXT Specifically the last paragraph which is pretty damn important:

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

**Comment by Jezithyr** [comment]
Disregard previous comment! This was about RSI's I misunderstood this as about the whole project licensing. My bad 😓

**Comment by ElectroJr** [comment]
space-wizards/RobustToolbox/pull/3667 should've fixed this, unless there's a third separate list of licences hidden somewhere

**Comment by Elijahrane** [comment]
I just need to update I guess
