### ISSUE TITLE
Voice Mask is not working again.

### ISSUE THREAD

**Issue by rhailrake** [space-wizards/space-station-14#13508]
## Description

Voice Mask is not working again.

**Reproduction**

Wear a voice mask and try to change your name.

**Comment by Mirino97** [comment]
Hello!

Thank you for your issue report!
In future reports, could you please add more info? Both your description and reproduction steps lack any information about actual issues you experienced.

I tested everything locally and concluded that there are no bugs with voice changer masks.
I can set my name and change it at will, and it changes my local voice.

They're a little weird right now because they ONLY change your local voice, but does NOT change your voice over the radio, since the radio's name is based off of your ID. If you're ever buying the voice mask again, you can buy an agent ID to help you fake your voice locally AND over radio.

Also, I've decided to change the description of the voice mask in the uplink to explain this ID thing, and also lower it's TC cost by 1. I think that'll help a little.
