### ISSUE TITLE
Fax machine can send entire books

### ISSUE THREAD

**Issue by Vaaankas** [space-wizards/space-station-14#13755]
**Reproduction**

Put a book into a fax machine
Hit send
A book appears out of the destination fax machine

**Comment by mirrorcult** [comment]
part of me wants to just say its intended because its really funny

**Comment by eoineoineoin** [comment]
So, this is my fault; when faxing a paper I deliberately kept the style of the paper, so that players could distinguish between received documents, and a book is just a paper component with a different sprite.

I did note it when submitting #13494 and didn't think it was too bad. It's also kinda funny and can be chalked up to space fax machine magic (doubly-so on account of #13758.)

If people do want to fix it, I can put something simple in? Or maybe there's room to go down the "more complexity" route, by allowing books to consist of multiple pages and all the page-turning action that entails?

**Comment by Visne** [comment]
> part of me wants to just say its intended because its really funny

I agree, only problem is that it allows you to infinitely duplicate books for free. If that's not a problem then I would want to keep this "feature" as well, because it is indeed pretty funny

**Comment by DogZeroX** [comment]
Feature
