### ISSUE TITLE
Frezon reaction is extremely unbalanced

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#14310]
## Description

Due to the mechanics of the frezon generation reaction, it is trivial to generate significant amounts of frezon without significant time or resource investment. I was able to create a frezon setup that generated over 100 mols per gas analyzer update. I'm not sure how often those update, or if they're real time, but I watched for a bit to ensure it wasn't just a random one off increase of 100+ mols. I did this entirely within pipes and, though I didn't time myself, the setup was completed relatively early in the round. In the end, despite multiple distractions during the round and the setup stalling because I ran out of empty canisters, I was able to create around 500k credits worth of frezon for cargo to sell. The round was not excessively long, hopefully it's clear how this is an immense balance issue.

While the code executes as written so this is arguably "intended behavior" by some definition of "intended", all code does. I doubt that the way this behavior can be used was indented or considered when the code was written and reviewed.

**Additional context**

This was previously reported as #14287 however further investigation has revealed that this is related to the frezon reaction, not rounding errors.

#14288 provides temporary mitigation for this by preventing it from affecting the economy, but a more permanent fix is likely needed.

**Comment by ElectroJr** [comment]
FWIW, the docstring for `FrezonProductionReaction` contradicts its current behaviour. It states that it uses `... nitrogen as a catalyst that also acts as a stopper if too much is present`, however it currently just requires a minimum amount of N2, instead of acting as a stopper. Given that N2 is produced as a waste byproduct, making excess waste block the reaction altogether would probably make it harder to easily produce? 

So one way of balancing it is to just make the function behave as described, and maybe also factoring the current nitrogen ratio into the efficiency calculation, so that you would actually have to maintain the nitrogen ratio at the right level?

**Comment by mirrorcult** [comment]
there is something implemented wrong here but i would need to find my original notes

**Comment by Partmedia** [comment]
I would vote for (and volunteer to implement) a simple fixed stoichiometric ratio requirement, e.g.

³H + A O₂ → B (frezon) + C N₂

Where *A*, *B*, and *C* are numbers we pick out of a hat, from which we re-determine the molar mass of frezon to make the law of mass conservation work out.

The effect in the comment of nitrogen acting "as a stopper if too much is present" kind of exists in the real world as concentration-dependent second order effects in the sense that if you have too much of "not the reactant" in the input, the actual reactants will take forever to find each other and hence slow down the reaction. This is not at odds with being stoichiometrically consistent, e.g. you could multiply `FrezonProductionConversionRate` by `(initialOxy + initialTrit)/initialN2` to make it slow down.

**Comment by mirrorcult** [comment]
this got basically fixed
