### ISSUE TITLE
Nuke should require anchoring away from edges

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#15026]
Nukies already have it easy but the fact they can just put the nuke on solars where they:
A) have jetpack advantage
B) have atmos advantage
C) had turret advantage (thank god that changed)

is silly. It should need to be well away from edges to be armable. If they just build a boundary outside the station then that's fine as it's still a nerf. This also takes away from metal used to build an armoured bunker around it.

**Comment by HoidC** [comment]
im just saying but the game was *far* better when they had to use vault nuke not the station one

**Comment by Just-Sim** [comment]
This was actually gonna be my first PR but I'm still analyzing the SS14 code to understand what is being called, from where and how. What I have in mind is using the same system SS14 uses for detecting when a set of grids is disconnected from the station and make it have zero gravity and applying it to the nukies' win condition (As of right now, neutral is literally just the end of an elif with no defined values)

Putting the nuke on solars should give the crew an option to cut off the nuke from the station and potentially even push it far away, giving crew a neutral victory, the bomb detonates but it didn't blow up the station (It has happened before in game). 

However this raises the issue that crew could just cut away squares around the nuke or the nukies plant it in a spaced room and it would count as a neutral instead of a Syndie MajW, so there also has to be a system in place that, before the nuke detonates, checks around in a 5 tile radius. Is it not attached to the station? Is it floating in space? Is there zero grav? If all three are correct, neutral W.

Right now this is all just theory though. I'm just a poor python coder.
