### ISSUE TITLE
more doafters brokey

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15139]
## Description
1. deconstructing walls breaks if you click again while welding
2. spamming drink cancels which is very annoying
3. cancelling prying apc prevents apc from being pried ever again

**Comment by Tunguso4ka** [comment]
4. Cant deconstruct barricade if you fail to the first time.  
https://user-images.githubusercontent.com/71643624/229858290-b42b7cfc-07a8-4f7e-bc08-f8d51684d391.mp4

**Comment by Tunguso4ka** [comment]
4. Cant deconstruct barricade after you fail to do it the first time.

https://user-images.githubusercontent.com/71643624/229859924-430fd8e5-fd35-4c9d-a876-f05519e375ef.mp4
(smh video attached as a link the first time)

**Comment by ElectroJr** [comment]
1, 3, & 4 are all the same bug, and should be fixed by #15144.

2 is intentional, even if it might be annoying for people who got used to spamming DoAfter interactions. It's meant to make it easy to cancel DoAfters, whereas previously you would just have to throw your drink to the floor to stop an accidental sip.

If you're spamming it for the sake of trying to start the next DoAfter as quickly as possible, that will probably be fixed by adding support for automatically repeating DoAfters.
