### ISSUE TITLE
solar is way too powerful now

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15155]
## Description
since they no longer block eachother it basically has artifically much more panels compared to before
maps like fland can run completely off just 3/4 solar wings

**Reproduction**
1. set up solars
2. turn off ame and unanchor smeses
3. solars can fully provide for station since theres still the same number of them but they work much better

**Screenshots**
![16:43:29](https://user-images.githubusercontent.com/39013340/230133329-b4a433f8-1b00-4490-a264-0dd8b66b4f43.png)

**Comment by Peptide90** [comment]
Maximum supply is 1500 multiplied by coverage.

Fland has approx 473 solar panels from a cursory map file search. That gives a potential total production of 709.5kW which is likely more than the station needs in most cases.

I'd propose knocking solars down to at most 1kW so in this example you're still getting approx 473kW which should be more than enough to run a station in most instances. 4 solar arrays should be enough to power most of a station so there's no issues here. 

Otherwise we need to do a check on all the stations to see what they draw and how many panels they need so there's a balance between being adequately covered, not overproducing solely on solars and actually encouraging engineering to setup engines or expand solar arrays, rather than spending 5 mins at round start just connecting solars then clocking off for the shift.
