### ISSUE TITLE
Metamorphic glass entity name mispredicts

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#15365]
Apparently it flickers to another name and mispredicts every time you drink.

**Comment by minism** [comment]
I tested this with wine, it swaps to "Wine glass" for one frame each drink and then back to "Metamorphic glass".  Doesn't seem to be a network prediction thing since even with 200ms fake lag its only a one frame flash.

I'm assuming the intended behavior is that it says "Metamorphic glass" always then?  Or, should it say "Wine glass"?

**Comment by EmoGarbage404** [comment]
> I wonder if what's happening is that the Metadata component is being recreated for some reason every time you drink.

it might be updating it every time the solution changes (when you drink) and, in the process, resetting it to the default, causing the mispredict

**Comment by metalgearsloth** [comment]
Solutions aren't networked which I imagine may be related.

**Comment by minism** [comment]
I put a log in where `metadata.EntityName` is set, and i get "Wine glass" every time I take a drink, it isn't set to empty string until the glass is finished.   But viewvariables shows "Metamorphic glass" for metadata.EntityName, which makes me the fields are being reset through a different codepath (network update?)

I'm completely new to this codebase though
