### ISSUE TITLE
The overlay for being unconscious moves with the camera

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#1572]
If you have any form of camera shake the overlay of being unconscious/blinded moves with the camera, while it should instead stay on-top of the character.

**Comment by GlassEclipse** [comment]
What camera shake are you referring to?

**Comment by Qustinnus** [comment]
` any form of camera shake`

**Comment by GlassEclipse** [comment]
I am unaware that we even had any camera shake.

**Comment by brndd** [comment]
There's some when random events fire, at least for the power off event.

**Comment by Qustinnus** [comment]
I know explosions have some

**Comment by GlassEclipse** [comment]
I see what you mean. The overlay will always target the center of the screen, but screenshake makes it so that your character is no longer on the center of the screen.
I can fix this by passing in the characters screenposition as a param, but I make some changes in my overlay PR at https://github.com/space-wizards/RobustToolbox/pull/1387 that affect passing in params. So I will wait for PJB to merge that before fixing this.
