### ISSUE TITLE
Action bar no longer has numbers in their slots.

### ISSUE THREAD

**Issue by KaiShibaa** [space-wizards/space-station-14#15743]
![image](https://user-images.githubusercontent.com/100050424/234051839-f38c4972-cbaf-4a5f-ba87-69a6a4bf8fd6.png)

As shown, the action bar is missing numbers.

**Comment by Skyedra** [comment]
FYI I was looking through trying to pinpoint what might have broken it (and thus how to fix it), and so far it seems like it happened somewhere between:
* [Update submodule to 0.101.1.0](https://github.com/space-wizards/space-station-14/commit/1320bedd8e6bfda12a6139446011f341ae9758ce) - no numbers
* [Thermomachines code cleaning + some QoL](https://github.com/space-wizards/space-station-14/commit/fd973be10ca5039916779ebbf8f0b45fb7b198b7) - has numbers

So possibly broke somewhere in these ~six changes -- but since there was a build breakage in there, harder to narrow down farther.

**Comment by lzk228** [comment]
fixed
