### ISSUE TITLE
arrivals system needs to not dump players/also reorient them

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#16336]
currently arrivals dumps players if they afk on shuttle, this is problem because die it should just take them back
probably should be changed to remove the component on traversal to station grid
could also make it auto orient camera on this move?

**Comment by KaiShibaa** [comment]
To add to this,

Some people are exploiting this by stealing any kind of suit that protects them from space and instead of gaining access or breaking out in some way via tools, emag or explosives they instead use the arrivals shuttle to go into space as it dumps them out when it leaves. Essentially granting them the ability to bypass the aforementioned methods of going out in space.

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/16417 and https://github.com/space-wizards/space-station-14/pull/16414
