### ISSUE TITLE
animals can use uplink implant

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#16900]
## Description

they can buy items and extract tc
**Reproduction**

1. inject yourself uplink implant
2. insert tc to implant
3. take out implant
4. inject implant in mouse
5. mouse can buy penguin grenader
**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
mouseops

**Comment by deltanedas** [comment]
not checking whitelist before implanting (afaik only dna scrambler has a whitelist)

how i see it should have a whitelist first on the implanter and second on the implant.
implanter should be body and dna scrambler remain humanoidappearance

from there admeme implanters that implant into anything provided the implant allows it, and maybe restricting uplink implant to anything with hands since a mouse telepathically spawning gear is a bit silly

**Comment by deltanedas** [comment]
also there was a hardcoded whitelist it was just for mobstate not body, so pai could use it as it has mobstate
will improve this

**Comment by lzk228** [comment]
god bless deltanedas
