### ISSUE TITLE
Carp on uplink seems a bit too stronk

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16932]
e.g.
- Nukies spam it
- Make carp instant death trap

It's just a matter of whether people want to abuse it or not rn.

**Comment by deltanedas** [comment]
accuracy nerf would make fishtraps basically useless
not sure how it would do against tactical fish spawning

**Comment by Stealthbomber16** [comment]
can confirm as a carp abuser this shit is blatantly overpowered but i also am unsure of how to fix it

carp are fundamentally a defensive, trap tool. they lose a 1v1 to anyone with armor or a gun, so the way to use them is to either spam them and let them loose in a crowded area (i.e. shuttle) or funnel people into them one at a time (trap disposals)

the real problem isn't a single carp, its large groups of carp. ideally you come up with a solution that doesnt hurt the individual carp (especially since the carp is used in multiple areas) but hurts carp trap spamming. carps either should apply carp immunity frames or a stacking buff that reduces the damage dealt by other carps.

but i will say that carps being used as a trap kill mechanism isnt any less effective than, say, a grinder (back when those worked) or a fire killroom, or especially suffocation.

**Comment by liltenhead** [comment]
Yeah mass carp stacks have become more common. Being able to splash water on yourself lets you make a huge stack all on one spot, and they'll basically just instakill anything they bite. Maybe purchase limits would be a good fix.

**Comment by deltanedas** [comment]
no more fishops close :(

**Comment by UbaserB** [comment]
People dont use carps as much anymore, for nukies its guns and for syndicates they use actually useful tools

**Comment by UbaserB** [comment]
why did you have to close it the moment i was typing

**Comment by EmoGarbage404** [comment]
> People dont use carps as much anymore, for nukies its guns and for syndicates they use actually useful tools

wasn't this already resolved by removing them from nuke uplink
