### ISSUE TITLE
Maybe standarize armories not being exposed to space

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17602]
## Description

I remember a conversation time ago that armory shouldn't be exposed to space, making it too easy to break in. It would require more planning than just "break armory, steal all guns"
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Arendian** [comment]
Out of the current mid-high pop rotation maps we have the following  layouts:
Only two have an armory with a wall directly to space(Kettle, Origin) . 
Four have at least one room/corridor/empty area between the wall to space and the wall to the armory(Aspid, Box, Marathon, Meta).
Two have an armory in the middle of the station(Bagel, Fland).
So I think there already is quite a variety of armory layouts on the current maps in rotation, maybe  Box, Marathon and Meta can get a double layered reinforced wall as actual armory wall instead of their current one layer(See Aspid's armory). This would require operatives to break through three walls instead of two before being able to grab all the armory goodies.

**Comment by keronshb** [comment]
I think a degree of the SS13 ridiculousness comes from how hilariously designed some of these stations are. "Yeah let's make the vault, armory and engine all space facing).

It feels too much of a hugbox to make these things more safeguarded.

**Comment by Matz05** [comment]
Yeah, I like stations being questionably designed in a variety of different ways, making different gambits practical on different maps.
