### ISSUE TITLE
Foam/Smoke should be reworked or removed

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#17676]
there has never not been a time where its not horrifically bugged/abused. the system needs to be ripped out and redone or just not reimplemented. I think it is worse for the game with it in it.

**Comment by metalgearsloth** [comment]
KILL

**Comment by Kayek14** [comment]
Please kill it with Fire! We have plenty of examples of it being taken way out of its intended use.
Use foams with most drugs? OD yourself and die.
Use foams with poisons? Extra die

Foam is just about only used by traitors who abuse its power and kill, or those using it to duplicate chemicals that otherwise should not be duplicated.


See below for more examples.
[17455]
[16944]

**Comment by Matz05** [comment]
I agree that the current implementation of foam/smoke is probably worse than none, as far as effects upon game strategy go, and it's distorting efforts to balance other mechanics that touch chemicals. It might be worthwhile to disable the reactions until better (non-duplicating) ones can be implemented. Sad to see such a conceptually fun mechanic go, but if it causes this many problems it's worth removing temporarily.

**Comment by Myakot** [comment]
Kill it with fire! I'm tired persuading people against using chem duping through ipecac.

**Comment by Arendian** [comment]
I made an attempt at fixing the duping through vomiting in this PR: https://github.com/space-wizards/space-station-14/pull/17697

Also the puddle/spreader refactor is the one that broke it I think.
Video from a build a few days before the spreader refactor:

https://github.com/space-wizards/space-station-14/assets/137322659/0d18ef77-c3dc-4d91-b8be-dfae2616c2b7

**Comment by Aisu9** [comment]
> I made an attempt at fixing the duping through vomiting in this PR: #17697
> 
> Also the puddle/spreader refactor is the one that broke it I think. Video from a build a few days before the spreader refactor:
> Smoke.mp4

this is not fixing anything... because you don't need much anyway to make foam grenades. because when you breath in foam you instantly fill your bloodstream with that little 1u of medicine/poison (remember the bloodstream hold 250u and you metabolise whatever is in) . you'll still be able to remove permanently anyone with a little quantity of poison or medicine

**Comment by Arendian** [comment]
The PR is to fix people making infinite omnizine or stimulants not to fix the smoke putting stuff in the chem stream

**Comment by Aisu9** [comment]
This PR is about to reworking Foam/Smoke so you can't exploit it to make infinite Medicine/Poison and instantly killing people or making them unkillable.
You should know that smoke/foam doesn't need much of the core component to make it infinite... like you don't need 50u of X to make it a foam that you can exploit, you can just make pocket foam with 1u of the stuff and BOOM your bloodstream (that can hold 250u) is instantly filled with the stuff (doesn't matter if you used 500u or 1u or chemical, your bloodstream will still be filled with the stuff)

**Comment by LankLTE** [comment]
> This PR is about to reworking Foam/Smoke so you can't exploit it to make infinite Medicine/Poison and instantly killing people or making them unkillable. 

That's what the issue is about. #17697 (what they were referencing) was about fixing vomiting.

**Comment by Aisu9** [comment]
> > This PR is about to reworking Foam/Smoke so you can't exploit it to make infinite Medicine/Poison and instantly killing people or making them unkillable.
> 
> That's what the issue is about. #17697 (what they were referencing) was about fixing vomiting.

yeah... your not fixing the issue that smoke/foam inject instantly with 250u of that 1u omnizine foam grenade you made

**Comment by Aisu9** [comment]
this PR is about fixing 2 things about Smoke/Foam:
First : Fixing the instant 250u injection from whatever quantity of chems is in the grenade in the bloodstream
Second : Fixing Chemical infinite duplication

**Comment by Arendian** [comment]
The foam/smoke multiplies by roughly 20x if you stand in it for 10 seconds, so if you smoke 15u omnizine it will fill your chem stream to 250 if you stand in it for the full 10 seconds(so you need at least 125u of a reagent in the smoke to fill you up to the max in one second). If you puke this out you would only get 25u back. So a full "puke cycle" would only yield you 12.5 of the chemical you want to duplicate, which is not a lot for the amount of time it takes. If that's still seen as too much I could just lower the amount of chemicals in the puke to even lower than 10%. 

I do agree with you that a big part is still not fixed by said PR, and fixing part 1 would make it not needed at all. It's only an attempt by me to lower the amount of things you can exploit with the current iteration in the hopes of it not completely getting removed by lowering the symptoms.
Sorry for derailing a bit,  any more talk about my PR should probably be done in the comments of said PR instead of here

**Comment by GoodWheatley** [comment]
Closed by #17693
