### ISSUE TITLE
Fire alarms cannot be used in spaced areas

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#17852]
## Description
The entire point of the wallmount fire alarms is to prevent spacing softlocks, yet they literally cannot be opened when spacing is present. This makes them completely useless outside of stopping people chasing you.

**Additional context**
I believe this was intentional behavior caused by one of the recent firelock changes, but I can't find the PR.

**Comment by Emisse** [comment]
society

**Comment by dmnct** [comment]
I thought you can only hand-open firelocks that are pressurised on both sides in order to prevent people from rapidly making every single hull breach significantly worse. The wall buttons would do this even more effectively, if they could, since they would open not just one but all sides of the breach to the adjacent firelock sectors

**Comment by Flareguy** [comment]
> I thought you can only hand-open firelocks that are pressurised on both sides in order to prevent people from rapidly making every single hull breach significantly worse. The wall buttons would do this even more effectively, if they could, since they would open not just one but all sides of the breach to the adjacent firelock sectors

Spacing is gradual, so this shouldn't be that much of an issue. In SS13, it'll open for like 2 seconds, and then immediately close since it detects spacing, which is usually just barely enough time for you to get out.

You probably shouldn't be able to open spaced firelocks with just your hands though, that could definitely be abused incredibly easily.

**Comment by dmnct** [comment]
Atmospheric loss is less instant currently, but this was not always so, and might not always be. I don't think we should treat the opening up of entire spaced compartments lightly. That said, it might be a good change to allow spaced firelocks to be hand opened from a spaced side only (I don't think they can currently check this). This would expose less adjacent areas and potentially for a shorter time, since you could immediately move through and close it again, rather than have to reach the airlock first from the wall button

**Comment by Flareguy** [comment]
Fixed by #22584
