### ISSUE TITLE
mosins are apparently considered "maint loot"

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#17970]
why are mosins in the lootpool

#17883 is the only thing i can see that was recent enough to cause this, we just went through and removed a lot of lethals from salvage because of how common they were less than two weeks ago + guns should not be maint loot i do not know why that has to be explained

**Comment by Emisse** [comment]
they are supposed to be uber duber rare

**Comment by Mirino97** [comment]
I second this.
It makes zero sense to me that Mosins were added simply because "they're really rare".
At that point, why not allow every single other gun then?

My concern is that the prospect of a "super duper rare gun" is absolutely enough for metagamers to rush maint loot even harder, even if, as described in the PR, the gun is a "meme gun". 
My second concern is that this could give the impression that certain guns are allowed (i.e not contraband) since they're found in maints, which makes the distinction of "contraband" even more muddier than before.

We've already had at least one round, as reported in admin chat, where at least 2 or 3 Mosins spawned naturally in maints.

I also don't understand the rationale behind the initial PR, but that's a discussion for another issue.

**Comment by EmoGarbage404** [comment]
the intent is that contraband is expanded to more broadly include items like this. Currently there is issues where items that are clearly contraband aren't considered so because they come from "valid" sources (uplink, etc). The PR was an attempt to make these contraband items more generally accessible to that security has more of a reason to take them in these extenuating circumstances.

**Comment by Equivocateur** [comment]
If you're malding over that funny lizard round it was me who bought 20 mosins and started putting them in lockers

**Comment by Equivocateur** [comment]
> My second concern is that this could give the impression that certain guns are allowed (i.e not contraband) since they're found in maints, which makes the distinction of "contraband" even more muddier than before.

The idea is to not get a person sent into perma for dumb shit, its still a gun - therefore contra, plus items retain their "syndicate" in name or desc after I've been bullied by emo and CE for this. They stay contra but do not indicate that this person is valid for perma/execution.

**Comment by Mirino97** [comment]
> 

Ah, I see.
I still don't think this is the way to go.
By adding guns to maint loot you set the precedent that "guns are okay" as maint loot, which would contradict a previous understanding that was made that maint loot should not have effective killing weapons (I might be misremembering this, I'll look it up later, don't quote me on this rn)

Not only that, but "sec perma'ing unvalids" is not a mechanically enforced issue, but an admin enforced one. I.E if people are being unfairly perma'd, we change the culture, not the game.

Imo, adding syndicate loot to maintenance will not have the effect you desire. It'll only bring more issues with self-antags, disruptive in-game behavior and maint goblins.
But the initial PR was already merged, so talking about it rn doesn't make much sense. We'll see how it plays out.

**Comment by Equivocateur** [comment]
> effective killing weapons

> mosin

huh

> It'll only bring more issues with self-antags, disruptive in-game behavior and maint goblins.

The PR was merged and published like uhh 2, almost 3 days ago and I've yet to see a tider actually robusting anyone with a mosin or a susbox efficiently. And by the wording of "It'll only bring" the admin team has yet to see that too.

**Comment by Mirino97** [comment]
> The admin team has yet to see that too.
Idk, there have been a few discussions about this in admin chat, and feelings are divided. I haven't adminned in a bit so I can't state for sure, but if there's truth in what's been reported, there have been a few problematic situations.

And while the mosin is still the worst gun in existence in the game, it's still a weapon that can kill relatively easily, and shouldn't be found in maints. Perhaps "effective" was not the best descriptor tho, I'll give you that.

**Comment by Equivocateur** [comment]
> it's still a weapon that can kill relatively easily, and shouldn't be found in maints

When was the last time you had a genuine firefight with a mosin in hand

**Comment by Mirino97** [comment]
Personally? Never. I would never purchase the mosin intentionally.

Still not a reason to have them in maint loot tho, imo. Would've made much more sense if it was crafted weapons... keeps in with the idea of "maint trash", innit?

**Comment by Equivocateur** [comment]
> Would've made much more sense if it was crafted weapons

Bet, PR'ing makeshift laser gun in the maint loot pool next thursday

**Comment by Mirino97** [comment]
There's no reason to be antagonistic, I thought we were just having a conversation?

**Comment by Equivocateur** [comment]
Not trying to be, apologies if I passed off as rude in that reply. Anyhow the reason behind that PR was to give security a hint to be less bloodthirsty in regards to contraband.

Solving security being complete metagaming shits (the actual problem) would require the double of the admin staff that wizden has now due to amount of sniffing required to properly catch those who are not the worst offenders. This does just fine as a start.

**Comment by deltanedas** [comment]
a weapon being maint loot doesnt mean you cant be arrested for it
its still a gun so sec is right to take it from you but thats it. unless they have reason to believe you are a syndie, they shouldnt go taking your pda and other meta shit

**Comment by Equivocateur** [comment]
> they shouldnt go taking your pda and other meta shit

The exquisite security officer G.M. checking your shoes, your black gloves, your headset and your implants because you stole a sec gas mask:

**Comment by Mirino97** [comment]
Ah, we cool, my bad then.

Sure, I guess we'll just agree to disagree and see what happens

**Comment by retequizzle** [comment]
> Not trying to be, apologies if I passed off as rude in that reply. Anyhow the reason behind that PR was to give security a hint to be less bloodthirsty in regards to contraband.
> 
for someone not trying to be rude you've been doing a good job of it

> Solving security being complete metagaming shits (the actual problem) would require the double of the admin staff that wizden has now due to amount of sniffing required to properly catch those who are not the worst offenders. This does just fine as a start.
> 
> Mosin is already bad so it can be called a makeshift weapon, since actual makeshift weapons (spears) are genuinely way better than the gun.

guns should not be maint loot, simple as. i'd have at least met you halfway on the explanation if you STARTED with makeshift weaponry (we do have makeshift guns, which i'm sure you noticed while going through and seeing what all was available to begin with) but throwing mosins in, even as an exceptionally rare drop is a bit much.

**Comment by UbaserB** [comment]
im gonna.. close this ancient issue cause clearly we've decided on keeping epic syndie loot in maints
