### ISSUE TITLE
Food Damage Indicator

### ISSUE THREAD

**Issue by Geekyhobo** [space-wizards/space-station-14#18032]
## Description

There should be a way for med to see if a person is taking food damage, so they don't just heal them forever as they take damage.
or food damage should stop when the person is dead

**Comment by EmoGarbage404** [comment]
1. food damage does stop when a person is dead
2. the indicator is the red icon on the side of the starving player's screen as well as the slowdown

**Comment by LankLTE** [comment]
>     2. the indicator is the red icon on the side of the starving player's screen as well as the slowdown

For an indicator, they presumably meant for an outside party. If someone goes into med, the doctors have no way to tell for certain if the patient starving unless they're told.

**Comment by mirrorcult** [comment]
then ask the patient if they're starving

**Comment by deltanedas** [comment]
what if the patients crit (ick ock!!!!!!!!!!)

**Comment by EmoGarbage404** [comment]
> what if the patients crit (ick ock!!!!!!!!!!)

should've eaten burger

**Comment by mirrorcult** [comment]
uncrit them and then ask them

**Comment by LankLTE** [comment]
> uncrit them and then ask them

yeah i agree, just figured it was worth clarifying

**Comment by hord-brayden** [comment]
I've had 3 patients in 2 shifts who've come in and they were starving into crit, over and over. O2 is very clear when there's an issue - and I'd argue even thirst due to the slowdown. At least there's something. 

Being colorblind, I legitimately can't tell the burger icons coloration between famished and starving. Aside from needing to hover over it occasionally or keeping track of the red visual cues around the screen. Even making it flash would be ideal. Just my $0.02.

**Comment by Kayek14** [comment]
Health analyzer could be coded to show the patient's hunger/thirst level as well. I believe there is already levels of hunger and thirst in the respective components. Would be nice is the analyzer would show their status. (Starving, parched, overfed, thirsty, etc..)

**Comment by GoodWheatley** [comment]
you should just ask if they’re starving
