### ISSUE TITLE
Nukie AA Before Landing

### ISSUE THREAD

**Issue by Alekshhh** [space-wizards/space-station-14#18374]
Nukies can essentially get AA by microwaving the agent's ID and adding access to their ID each time. This is obviously broken.
EDIT I meant to say syndicate ID not agent

**Comment by EmoGarbage404** [comment]
does microwaving an agent ID not have a random chance to brick it like other IDs?

**Comment by Alekshhh** [comment]
it does so it is luck based, but still

**Comment by Ilya246** [comment]
you'd need to buy multiple agent IDs to do this (also, commander and agent do not start with agent IDs), might as well just buy emag which has more uses

**Comment by lzk228** [comment]
feature

**Comment by asperger-sind** [comment]
The optimal way to do this is to take the syndicate IDs from the commander and medic, copy over access from them onto every agent ID, and then microwave these copying access over every time.

Since there is only a 15% chance the ID is going to be destroyed upon microwaving it, you can use it about 6.67 times on average before it turns to burnt garbage. You have 2 syndicate IDs so you're going to be getting 13 extra accesses for every nukie roundstart on average, and since there is no reason to not do it you just kinda win.

You can also gamble with agent IDs but that's risky because of the 15% chance to kill an ID.

**Comment by Alekshhh** [comment]
I forgot that they're called syndicate IDs honestly my bad
but still, they're trash you can use to get free access. I'm not sure if nukies should be able to do that, but then again it's not that big of a benefit either.
then again why does agent and commander even start with a syndie ID while the rest get an agent ID? that seems silly

**Comment by asperger-sind** [comment]
> why does agent and commander even start with a syndie ID while the rest get an agent ID? that seems silly

probably because the syndie announcement console requires syndie access and only the syndie consoles have it, i think agent and commander should just get agent id and agent id should have syndicate access by default

**Comment by Alekshhh** [comment]
yeah that seems reasonable

**Comment by Emisse** [comment]
feature

**Comment by EmoGarbage404** [comment]
if it's really a huge issue, just make the chance to brick the ID a bit higher.

**Comment by deltanedas** [comment]
instead of 20 mins making unused pills now its 20 mins getting aa

**Comment by Myakot** [comment]
> instead of 20 mins making unused pills now its 20 mins getting aa

it was 20 minutes doing both, now just one.

**Comment by deltanedas** [comment]
rwj ops :trollface:

**Comment by Equivocateur** [comment]
Nuclear Operatives generally have only 2 id cards to play with - that of agent and commander, who usually buy an agent id (because sillycate id is somehow not an agent id).

Microwaving an ID can give the same access over again.

> if it's really a huge issue, just make the chance to brick the ID a bit higher.
Bricked ID's just get a single random access after wiping everything, it's 25%.
Burned ID's are 15%. I'd say a 40% chance of a negative outcome on microwaving is sufficient as is.

**Comment by Alekshhh** [comment]
guess them getting 12 extra access is fine, so I'll be closing it
