### ISSUE TITLE
Hardsuit Armor vs Normal Armor

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#18725]
## Description
As of now, certain hardsuits like the security hardsuit and HoS hardsuit outclass their starting armor in nearly everyway. For example, the HoS hardsuit is nearly as good as the blood-red. Hardsuits across the board also possess very high explosion resistance making them favorable in many scenarios. 

Sure, losing some speed is bad, and interestingly syndicate's actually have tough choice to make. The web vest makes you very tanky to bullets, but weak to explosions and can't survive space. As of now it seems like security is nudged towards always wearing their suits. They have ranged stuns in the form of disablers and rubber bullets, and can tank explosions while in their suits.

I guess what I'm trying to discuss is should hardsuits be tankier than normal armor due to their speed loss? Or should hardsuits lose resistances due to their spacing and explosion resistance. Or even further should they have little to no resistance due to their space capability. 

(Also the sec hardsuit makes you slow enough to not slip so that's a different discussion but still one worth bringing up)

![armor vest](https://github.com/space-wizards/space-station-14/assets/104418166/0354a784-4dfd-4420-a06e-d76a31824369)
![sec hardsuit](https://github.com/space-wizards/space-station-14/assets/104418166/b4594ea5-9b9e-46f5-8310-7f7f0c13ad3d)
![trench](https://github.com/space-wizards/space-station-14/assets/104418166/5cd8b90c-4f32-4515-9d26-7ba8dc6f31dc)
![blood](https://github.com/space-wizards/space-station-14/assets/104418166/069d894b-1429-4786-914f-f52ac222db0c)
![hosss](https://github.com/space-wizards/space-station-14/assets/104418166/32cfdb5b-c610-459c-b034-e75a7d572db4)

**Comment by asperger-sind** [comment]
With how weak spacing damage is, and to note, I think it's fine how weak spacing damage is right now; it's more fun gameplay, I think it's fine if hardsuits have armor on-par or slightly better than armor that doesn't allow for EVA provided there is a movement speed price.

**Comment by LankLTE** [comment]
Honestly I think Sec's hardsuits are fine. The slowdown makes them awful enough (it's one of the slowest hardsuits in the game) in combat to where I hardly see them worn unless needed. Maybe the resistances could be toned down a bit but I wouldn't say it's a huge priority.

**Comment by Flareguy** [comment]
I don't think the standard Security hardsuit needs a nerf. The slowdown is painful enough to honestly warrant sometimes just flat-out tanking the spacing damage if it exists. I usually end up doing this myself, so I can't actually speak on exact balancing with the sec hardsuit...
...but with that being said, speed is a GIGANTIC factor in combat, so the resistances probably aren't going to be of too much help unless you're on the defensive. If you try to use it as better armor, you will probably just get gunned down by a traitor and be unable to escape due to your speed.

**Comment by liltenhead** [comment]
It is worth mentioning every member of security has access to roundstart ranged disables. Security also gets access to bullets better than the syndicates use by a large margin. Slow speed means you can't slip, which is another tool syndicate members lose. Nukies with their duffle bags are nearly as slow as a sec officer.

**Comment by JoeHammad1844** [comment]
> Honestly I think Sec's hardsuits are fine. The slowdown makes them awful enough (it's one of the slowest hardsuits in the game) in combat to where I hardly see them worn unless needed. Maybe the resistances could be toned down a bit but I wouldn't say it's a huge priority.

I concur

**Comment by JoeHammad1844** [comment]
> Security also gets access to bullets that are much better than the syndicates.
maybe this could be solved by putting high velocity rounds in the C-20R bundle?

**Comment by HoidC** [comment]
sec hardsuit absolutely doesn’t need a nerf it’s useful in very few situations (which is fine, it’s niche and that’s good)

in no regular scenarios without spacing should you ever wear something that makes you slow because you’re more likely to get shot/punched/stunned/blown up due to being an easier target 

seccies that wear hardsuits 24/7 are easy targets 

HOS’ hardsuit also has resistances, sure, but also a big slowdown which again makes them easy to kill

**Comment by JoeHammad1844** [comment]
I think maybe the sec hardsuits explosion resistance could be toned down and get some heat resistance

**Comment by JoeHammad1844** [comment]
also, on goonstation, you could strap armor vests to bio and EVA suits (which gives me an idea for a 'cleaners' centcom affiliated antag that have armored, space resistant biosuits and wield flamethrowers) maybe we could give that a try here?

**Comment by hord-brayden** [comment]
I’ve recently pondered this, so this is kismet there’s an active discussion about it. I don’t think the HoS suit should be worse than a blood red. There’s only one HoS hard suit, in a tightly controlled area, only accessible by arguably 2 of the busiest people on the station - and cap had other options.

Thematically, a head of security - the one person - in charge of the safety/security of 90+ souls, and one of NTs money making space stations (which seem to be prone to zombie outbreaks, insurgents, and operative attacks) should have some decent protection. At minimum, on par with what they’re fighting against. 

Realistically though, suits are mostly worn because nukies space everything. If you don’t have a suit, you’ll probably die from exposure quicker than bullets or swords. Also, vests in my mind should be the armor bearing aspect of protection, not suits. The web, armor, and sec vests should have plates in them, worn on the belt slot, that provide protection. Just my $0.02.

**Comment by liltenhead** [comment]
Spacing doesn't really do that much damage. Most species got around 100 seconds of survival time, not including their space pen. Even rooms getting spaced is slow and buys you time which is hard to calculate precisely.

**Comment by hord-brayden** [comment]
True, I suppose what should be said is; there is a large amount of time, in my experience, where I don't know where adversaries physically are at on the station. Forcing me to begin hunting/evading/positioning, when fighting. Typically, those areas most-likely spaced. From what I've seen, tiders do jump into those area without suits, but only to loot and try to make a play. 

I think if we made armor options tankier or a better option than suits, I would expect people to still gravitate towards the suits. Whether that's a function of skill (or lack thereof) or having a more well-rounded array of protection I couldn't honestly say. Let me pose  toyou this question: Typically would you see more individuals opting for a specialized armor to protect against 1 specific type of damage (bulletproof sec vest), or a generalized set (standard sec vest)? I don't have an answer myself, and this isn't rhetorical. Genuinely curious

**Comment by liltenhead** [comment]
Overall seems like general opinion is that armor is fine as is.
