### ISSUE TITLE
Self Singuloose

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#18825]
## Description
Singulo and PA are managing to sunguloose without any player interference.

**Reproduction**
Set up singulo as normal and set to 1 and wait, seems like it is a trickle build up of energy untill it breaches the level threshold that is larger than the standard containment zone. Was witnessed on Levi 30561

**Screenshots**
![singuloosed2](https://github.com/space-wizards/space-station-14/assets/47093363/28709156-d140-4524-8c4d-2004244bc752)

**Additional context**
Several times has happened now on Lizard and Levi and been aHelped. 
There are also several other PA issues:
- On round start the port and starboard PA emitters dont work and require rebuild, Like this issue: #18543
This could also be a duplicate of that issue too: #18255
![image](https://github.com/space-wizards/space-station-14/assets/47093363/09ec2b4a-0a9c-41bb-879f-a69779d3d1ed)
- Round start barratry is unable to work after being completed. Could be same issues as to build from scratch here: #18511

**Comment by Equivocateur** [comment]
#16896 no worky.

Are there any hidden implications of just capping maximum level the singularity can get from a level 1 Particle Accelerator?

**Comment by Equivocateur** [comment]
> The drain rate is correct. Something else changed.

![image](https://github.com/space-wizards/space-station-14/assets/109166122/7f3fa808-6743-4769-9f8e-22dea3d79ff6)
The entire singularity folder didnt change. Neither did the PA code since [39f272f](https://github.com/liltenhead/space-station-14/commit/39f272fa5c63623813fb98d48eacf78b77035283).

I think it doesnt drain fast enough as the PA just feeds it into becoming Tier 4 and breaching containment like a boss.

**Comment by liltenhead** [comment]
I've been watching the singularity have issues for months, this isn't a drain issue. Something is causing certain PA shots to give 2-3x more energy than normal and the drain rate can't possibly keep up. IT could probably be Band-Aid fixed again by increasing the drain rate further but I have zero ability to fix the actual problem. There was an ECS change #17075 which came after my small tweak.

**Comment by deltanedas** [comment]
what if you got a lot less energy from low shots meaning to get good power youd need to control the pa:
- gives engi something to do after 5 mins in
- makes >1 power not immediately sabotage
- more depth to singulo
- keeping on 1 singulose proof

**Comment by MjrLandWhale** [comment]
@liltenhead after reviewing the code for PA and singulo I have to agree it doesn't appear to be a drain issue. They use slightly different methods for timekeeping, but since it's all on the same GameTiming system it shouldn't matter, unless there is an issue with how singularity drain is calculating time between updates (explained a bit below)
@Equivocateur 
The PA fires a 3 wide beam every 6 seconds. On level 1, each parr contains 10 "energy" for the singularity. That's 30 energy / 6 seconds, or 5 energy/second.
A level 3 singularity has an energy drain of 6. When the singularity updatea/dissipates energy, it multiplies that drain value by the number of seconds since last update. This means it SHOULD always drain 6 energy/second.

Interestingly, this means a level 3 singularity is unsustainable. A correctly functioning system will bounce between levels 2 and 3. Either Lilten is correct and we need to look at how the PA is firing, or there is an issue with the time calculation for drain.

I need more data/examples, but it happened again on Leviathan 30584. It's interesting to note that in both instances it takes roughly 10 minutes from singularity start to self-loosing. Regardless, I would probably say this issue needs to be acknowledged/prioritized given it has consistent round-ending capability.

**Comment by MjrLandWhale** [comment]
> what if you got a lot less energy from low shots meaning to get good power youd need to control the pa:
> 
> * gives engi something to do after 5 mins in
> * makes >1 power not immediately sabotage
> * more depth to singulo
> * keeping on 1 singulose proof

I think adding depth/complexity to singulo is a long-term, and the current implementation comments pretty clearly state a lot of the numbers are hard coded or band-aids to allow the system to minimally be usable in game. 

The problem is that the code right now SHOULD BE singuloose proof on level 1. Changing how the system works without knowing why it isn't working right now is a recipe for disaster.

**Comment by liltenhead** [comment]
#18856 Should fix all of this and add slight depth to preventing sabotage.
