### ISSUE TITLE
Possible oversight with Syndies+Nukies game mode'?

### ISSUE THREAD

**Issue by AjexRose** [space-wizards/space-station-14#19074]
## Description

Not sure if intentional or not, but when the game mode is nukies+syndies, the game mode ends when all nukies are dead, screwing over any syndicate agents who didnt complete their objectives. 
**Reproduction**

1. Get nukies+syndie game mode
2. Kill all nukies.
3. Results. 
**Screenshots**

**Additional context**

**Comment by crazybrain23** [comment]
What do you propose to happen instead? 
If the round end didn't happen, would people assume the nukies are still alive? Would it confirm there's also syndicates on the station?

**Comment by deltanedas** [comment]
should probably have an automatic announcement saying all nuclear operatives died then let players decide to continue the round or leave

**Comment by EmoGarbage404** [comment]
i think the gamemode combining both of them just wasn't very well thought out. As it stands, syndies will lose almost every single objective that isn't a kill objective because the shuttle doesn't come. Besides murdering random targets, they have 0 incentive to work with operatives at all. It was clear the combination didn't take into consideration that the majority of the objectives would be quite literally impossible to complete under most circumstances.

**Comment by GoodWheatley** [comment]
> i think the gamemode combining both of them just wasn't very well thought out. As it stands, syndies will lose almost every single objective that isn't a kill objective because the shuttle doesn't come. Besides murdering random targets, they have 0 incentive to work with operatives at all. It was clear the combination didn't take into consideration that the majority of the objectives would be quite literally impossible to complete under most circumstances.

wouldn't all of the problems be solved by just removing the code that makes the round end when all the operatives die

**Comment by Interrobang01** [comment]
> wouldn't all of the probjegrjduvd

The default for the end round on nukie extinction variable in the nukeops gamemode component is true, maybe setting it to false will do the trick. Otherwise it's probably set somewhere else.

If there's some elusive problem with getting rid of the arbitrary spontaneous fun-ender system then maybe replace it with an automatic shuttle call.

**Comment by Ilya246** [comment]
i'm for making the round not end on nukie death even on nukie rounds

**Comment by metalgearsloth** [comment]
The mode shouldn't be having its own stuff implemented, this is just a shortcut to avoid working on dynamic / turning on survival.

**Comment by Ilya246** [comment]
> The mode shouldn't be having its own stuff implemented, this is just a shortcut to avoid working on dynamic / turning on survival.

yes, that's partially why i said it should autocall shuttle as opposed to ending round even on normal nukie rounds

**Comment by Ilya246** [comment]
actually, i think having it always do nothing on nukie death would be better, as that'd stop the crew from instantly being able to know when they're safe from nukeops, would allow interesting stealth plays by operatives left alive after the rest of the team is dead

**Comment by metalgearsloth** [comment]
> > The mode shouldn't be having its own stuff implemented, this is just a shortcut to avoid working on dynamic / turning on survival.
> 
> yes, that's partially why i said it should autocall shuttle or do nothing as opposed to ending round even on normal nukie rounds

On a nukies rounds there's 0 benefit to extending it another 10 minutes after all the nukies died compared to just ending instantly.

**Comment by EmoGarbage404** [comment]
we removed it lel
