### ISSUE TITLE
Recycler no longer recycles items passing trough it.

### ISSUE THREAD

**Issue by NancokPS2** [space-wizards/space-station-14#19157]
## Description
The recycler (usually found in disposals) no longer recycles items fed into it by conveyor belt. Inserting items by hand still works.  
Tested with several items, included those that SHOULD be recycled (broken lights, broken plates, burnt smokes, etc)

**Reproduction**
Turn on a conveyor belt (pointing to the recycler) and the recycler.  
Drop an item in the conveyor, it simply "falls under the recycler".

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/55665720/5d6cd7b8-2f8a-459e-be7a-85fa9b9105db)

**Additional context**
Possibly due to this commit: #18892

**Comment by deltanedas** [comment]
i dont think the blacklist matters since you can put nuke disk/someones pda in a survival box then nyoom

**Comment by Volotomite** [comment]
Yes. I've been looking into this issue, and this update caused recycler to completely die:
https://github.com/space-wizards/space-station-14/blame/6d8635156f1e284f70db4f33b522493d9b810b4b/Content.Shared/Materials/SharedMaterialReclaimerSystem.cs#L123

I suppose the idea was to empty container when it enters recycler, however this method doesn't do that.
TryRemoveFromContainer removes entity by uid from its container. But since any entity that goes into grinder isn't in container - this call always fails and returns false. So, if I'm not mistaking - this part of code should totally be removed

> i dont think the blacklist matters since you can put nuke disk/someones pda in a survival box then nyoom

Now, assuming that initial idea was to empty all object containers - that would automatically fix blacklist issue you specified, since box would drop it items before being gone.

However, I wasn't able to find a nice way to get all containers from item uid and empty them.
It appears to me that this methods should be useful to retrieve all containers from uid:
https://github.com/space-wizards/RobustToolbox/blame/d164148ce2f8d41a7e0c577afec8d55c916f5bc7/Robust.Shared/Containers/SharedContainerSystem.cs#L149

And this one to empty one container:
https://github.com/space-wizards/RobustToolbox/blame/d164148ce2f8d41a7e0c577afec8d55c916f5bc7/Robust.Shared/Containers/SharedContainerSystem.cs#L388

So I guess one way to go is to get all containers from uid, iterate and empty them.
However iterating this stuff gave me lots of errors and I'm not sure what I was doing wrong

**Comment by EmoGarbage404** [comment]
eugh i know what this is and i'll get to it in a day or two

**Comment by NancokPS2** [comment]
This jani enjoyer is grateful

**Comment by deltanedas** [comment]
this got fixed
