### ISSUE TITLE
Closing the bolt on a gun attaches a bullet to you

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#19176]
## Description

title, any gun that spawns with an open bolt seems to cause this, from security roundstart pistols, to mapped guns.

**Reproduction**

spawn any open bolt weapon, close the bolt. there is now a bullet stuck inside your sprite.

**Screenshots**

https://cdn.discordapp.com/attachments/811324338099585036/1141048169627668550/Base_Profile_2023.08.15_-_12.35.58.06.DVR_Trim.mp4

(message link)
https://discord.com/channels/310555209753690112/770682801607278632/1141048810685079562

**Additional context**

**Comment by Volotomite** [comment]
It's not exactly issue about newly spawned guns, I'll correct:

The issue is that if gun already has round inside chamber, then closing bolt will feed new round - which is forcing round in bolt to pop out from gun. If you'll remove mag and close bolt - round will stay in chamber, since no bullets are being fed.

**Comment by Volotomite** [comment]
I see two ways to resolve this:
1. Never remove bullet when closing bolt and skip round feeding if bullet is in chamber
2. Make gun jam when trying to feed round when one is already is there (that would be more realistic, but probably annoying as hell)

**Comment by QuietlyWhisper** [comment]
Alternatively the guns could start without a bullet in the chamber

**Comment by Errant-4** [comment]
Related to #19165
