### ISSUE TITLE
borg law zero should say DO NOT STATE THIS LAW

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#19170]
I was almost revealed when I emagged a borg and they fully intended on ratting me out but because someone took their brain out they couldn't view law zero (I did report them)

additionally, its obvious when a borg is emagged because the description would say 'the law governing system seems damaged' when emagged, ruining any stealth

**Comment by deltanedas** [comment]
urist mchands whispers, "do not tell anyone about law 0"

**Comment by JoeHammad1844** [comment]
pro

**Comment by LankLTE** [comment]
The second problem has already been fixed. The first is solvable by telling someone not to state law 0- however saying “because someone took their brain out they couldn't view law zero” is irrelevant, as they do keep their memories and laws don’t apply when they’re out of their chassis. I think emagging Borgs is fine, and it’s currently very risky because while you do get AA, you’re also very likely to be outed should the Borg be killed. Working around Law 0 to help the crew in any way you can still is part of the fun.

**Comment by deltanedas** [comment]
simple law 0 bypass:
1. emag borg
2. move mmi/posibrain into new borg
3. law 2, recall previous body's law 0

**Comment by EmoGarbage404** [comment]
this is basically resolved with the new syndicate lawset
