### ISSUE TITLE
Tasers look empty until first fired

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#1926]

**Comment by RemieRichards** [comment]
same for RPGs

**Comment by collinlunn** [comment]
Can't repro taser issue - they look fine. I have a fix up for RPGs.

**Comment by Zumorica** [comment]
We ran into the issues with the tasers consistently on EUW2, during the SSS test.
Perhaps it's due to the recent changes in the engine? They seemed to look fine before.

**Comment by metalgearsloth** [comment]
Pretty sure RPGs have had this issue for a while, probably just need to call an extra UpdateAppearance() somewhere for the boltactions.

I'll get to it in my gun prediction PR if it's not already done.

**Comment by Aranclanos** [comment]
![image](https://user-images.githubusercontent.com/701959/96647079-78f3b800-1303-11eb-8de5-6ae60b378b58.png)
 for reference, sprites of tasers today

**Comment by GlassEclipse** [comment]
Did some testing and it appears the issue is with the load order. In Saltern.yml the batteries are saved as their own entities (presumably since that's just how saving maps works), and the battery entity gets loaded after the taser entity. This means the taser calls SetAppearance() with a null battery, then the battery gets loaded in. 
The solution would be for a component PostInit() function which guarantees SetAppearance() will be called after the battery is loaded (for the love of god add this), or to add a way to load things before other things in mapping, which seems like a very bad solution.

**Comment by GlassEclipse** [comment]
And to add on, could I add a postinit() function to components?
The logic would simply be:
component.Initialize();
if(!map.Initialized)
      component.PostInitialize();

map.Initialized = true;
for all components
        component.PostInitialize();

**Comment by ShadowCommander** [comment]
We have a post initialize. The method is named `Startup`.

**Comment by GlassEclipse** [comment]
Oh okay
