### ISSUE TITLE
Gun bolts are too micro intensive and unintuitive

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#19284]
## Description

Disclaimer: I may be misunderstanding how guns work now, but if I'm having problems as a veteran player then I dread to think what newer players are experiencing.

Reloading a pistol now requires interaction through a right-click menu to toggle bolts. A seemingly simple action that IRL takes barely any effort, in SS14 it takes precision mouse movement, navigating a menu and selecting the correct button.

**Reproduction**

1. Shoot magazine-fed pistol until empty
2. Load a new magazine
3. Can't shoot until player interacts with right click item menu and finds "toggle bolt"

Notice how step 3. is not needed when executing precision strikes with a knife, our characters can manage to automatically guide their hands to perform aggression in melee without us needing to perform similar motions with our hardware.

**Screenshots**

**Additional context**

I'm not sure if realism is the goal with these user unfriendly interface features, or whether it's balance by obfuscation or some other reasoning I'm missing.

Perhaps a shortcut button to toggle bolts would fix this artificially created problem.

**Comment by Errant-4** [comment]
You can toggle the bolt by hovering over the gun in your hand with the mouse and pressing interact (E)

**Comment by LankLTE** [comment]
You should really be able to just hit E to bolt and unbolt, or even just Z (I don’t know what it does currently, but it used to be cycle so I’m not sure why it isn’t now). That’d help a lot, on top of the ammo counter having a “bolt open / closed” title to make it keep clear

**Comment by Errant-4** [comment]
E is specifically a context sensitive control, interacting with what the mouse points at. If holding a gun hijacked it, it would be a betrayal of the User Interface.
I guess the issue here is that there was no free button for "use item" left since the 2 that exist (default Z and alt+Z) are already overloaded with wield, cycle and eject magazine. Z is still Cycle, but it does nothing if the bolt is open. As a QoL improvement this could be changed to close the bolt, and then subsequent presses would cycle as normal. If you ever had to open the bolt you would still need to use E or right click, but that's probably a much less common scenario

**Comment by SpeltIncorrectyl** [comment]
> You should really be able to just hit E to bolt and unbolt, or even just Z (I don’t know what it does currently, but it used to be cycle so I’m not sure why it isn’t now). That’d help a lot, on top of the ammo counter having a “bolt open / closed” title to make it keep clear

I think closing the bolt with Z if it is open is a good solution.
