### ISSUE TITLE
Soap Can't Go Into Crates/Lockers

### ISSUE THREAD

**Issue by Alekshhh** [space-wizards/space-station-14#19301]
honestly surprised this was never documented given how long its been a thing

**Comment by Titian3** [comment]
Hey im trying to get this to replicate and can't get it to, i've done another check at round start on regular server and it seems to work but stopped in the later stages of a previous round, worth a shot asking but any clues for when it goes bust?

**Comment by Titian3** [comment]
Never mind I have a replication now. :)

**Comment by deltanedas** [comment]
it depends on the stations rotation, sometimes the aabb is small enough to fit?

**Comment by Titian3** [comment]
> it depends on the stations rotation, sometimes the aabb is small enough to fit?

Looks that way when im steping through its the aabb that almost seems random every startup.
So this one will fit:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/bcc2daad-a023-46a9-b43c-d5af843abef6)
But on another restart this one does not:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/aca72380-a7fb-40ba-b509-0acb1f3e2742)
Max is 1 for the container in this situation for a crate.

**Comment by deltanedas** [comment]
yes station rotation is random so by extension the map aabb is random

**Comment by Titian3** [comment]
> yes station rotation is random so by extension the map aabb is random

Thanks! this helped me get on the right direction!

So the problem is depending on the initial conditions of the station rotation or the rotation of the soap/spear the aabb X and Y size exceeds the max size of the crate sometimes but is usually less than 0.1 over.

I've got a proper fix for it but might need some advice from you, @metalgearsloth (looks like they did the aabb code from commit history) or someone else on best approach. 

My ideas to skin the cat were:

1. Make the crate a fraction bigger.
2. Make the soap and spear a fraction smaller.
3. Instead of getting the current aabb, calculate the most optimal aabb by doing a simulated rotation and get the most optimal  box size back. essentially emulating the player rotating the object to the best angle to allow it to fit.

I was trying to avoid 1 and 2 as they seemed hacky.
I have the 3rd option already coded but looks like the change should go in RobustToolbox, so just want to get some feedback before putting a PR up.

I've done some tests already with the new method and looks like it works and fixes the issue.
Some examples with a soap:
Size with initial rotation from station and initial rotation of soap spawn.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/5600cab4-66d5-438c-b0f2-75a79493732e)
Sizewith new smallest aabb calculation with same rotation:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/5c167ffa-640b-4102-990b-d6e50bb2a6ed)
New rotation by throwing it, default aabb calculation on its current angle:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/d291138c-e676-4dcd-a8f8-8fa09b8b065e)
That same thrown rotation but with new smallest aabb calculation:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/3bf0344e-4aff-4790-99ad-d62eecf31a90)

**Comment by deltanedas** [comment]
i think the proper solution is having the aabb axis be defined relative to the grid if they are on one, it also affected dehydrated space carp in lockers

**Comment by Titian3** [comment]
If its relative to the grid it would still have the same bug and potentially exceed the size requirement depending on the initial station rotation and the current orientation of the object, eg if you throw it, it is in a different angle and the bounding box on one side would exceed the max storage value. Maybe ill just pop the two PR's up and I can close em back off if they are no good.

**Comment by deltanedas** [comment]
if you place with q it has no rotation

**Comment by iacore** [comment]
just don't use aabb. Use the sprite size

**Comment by metalgearsloth** [comment]
> don't use aabb. Use the sprite size

server has 0 knowledge of sprites.

**Comment by iacore** [comment]
here it seems like it uses World Transform.

![image](https://github.com/space-wizards/space-station-14/assets/74560659/e5f478a3-e313-4c11-a647-e59dcf861005)


if we don't rotate it by world transform, then the result AABB should be "smallest"?
