### ISSUE TITLE
Advanced mop no longer functional

### ISSUE THREAD

**Issue by Appenzaller** [space-wizards/space-station-14#19483]
## Description
It appears the advanced mop no longer produces water. It effectively behaves like a regular mop now.

**Reproduction**
Hold advanced mop, wait, become sad.

**Additional context**
Have tried putting in reagents to replace with water, have tried not putting in reagents at all, it just seems that it no longer generates water by itself at all. visually it does seem like it may replace reagents with 'dry mop' instead, so it almost seems inverted.

**Comment by Alekshhh** [comment]
cleanbot is also affected by this, since they probably use the same code

**Comment by chromiumboy** [comment]
Did some digging, it's because the Volume field in Solution.cs isn't being set. Since its equal to zero, it causes a while loop to exit at line 38 of SolutionRegenerationSystem. If you manually set the Volume field e.g.

```
if (regen.Generated.Volume == 0)
{
    foreach (var reagent in regen.Generated.Contents)
    {
        regen.Generated.Volume += reagent.Quantity;
    }
}
```

then it starts working again. Not sure where the timing of the initialization of Volume is being mucked up though

**Comment by chromiumboy** [comment]
OK, I think I have a fix for this, I'll post the PR later
