### ISSUE TITLE
Pulling issues

### ISSUE THREAD

**Issue by ancientpower** [space-wizards/space-station-14#1971]
Things that are actually broken:
- [x] Pulling requires a PhysicsComponent to work, which is apparently depreciated (I assume it needs mass for friction calculations)
- [ ] Pulling doesn't change the sprite direction of the pulled entity based on the direction it's being pulled

Things which would be nice but not actually broken:
- [ ] Pulling should slow down the puller based on mass if the pulled entity is scraping the ground

**Comment by metalgearsloth** [comment]
Pulling lets me transcend space and time (I replicated this on master and on smug's PR). It's easier to do if you're on smug's PR or if you turn on cvar net.predict 0.2 on master.

Console gets spammed with [ERRO] clyde.oal: [SetVolume:430] AL error: InvalidValue I assume because my position has gone screwy and the eye is going to some random Nan value or the likes.
[2020-10-16_13-48-47.zip](https://github.com/space-wizards/space-station-14/files/5388896/2020-10-16_13-48-47.zip)

**Comment by SweptWasTaken** [comment]
Closing this to concatenate into #2387
