### ISSUE TITLE
ninja suit actions dont show up

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#19970]
## Description
theyre added to the players actions Actions field but dont show up in the action bar or K
very bad and i have no idea why it happens, everything else works which both use GetItemActions just like suit

reverting #19964 fixed it...

it is not spawning the entities on client ok

**Comment by deltanedas** [comment]
@DrSmugleaf please help i have no idea how to fix it

**Comment by deltanedas** [comment]
the suit action entities are not getting sent to client so its not able to get the data...

**Comment by DrSmugleaf** [comment]
@deltanedas 
The actions are not added because the check in OnSuitInsertAttempt fails as args.EntityUid does not have a battery component.
Commenting out that condition makes the actions show up and work:
![image](https://github.com/space-wizards/space-station-14/assets/10968691/7613851e-d353-404d-8594-529514164326)
![image](https://github.com/space-wizards/space-station-14/assets/10968691/c8560c08-fe21-4853-81cc-e7020f3a72c9)

**Comment by DrSmugleaf** [comment]
There is a separate unrelated bug where equipping the energy katana to your hands causes an error but that is fixed by https://github.com/space-wizards/space-station-14/pull/20015

**Comment by deltanedas** [comment]
ah its handling insertion for actions never thought that would happen thanks for finding that out

**Comment by DrSmugleaf** [comment]
> ah its handling insertion for actions never thought that would happen thanks for finding that out

It wouldn't have been before, that's because actions are now stored in containers in order to be sent to clients.
Actions granted to the player directly are stored on a container on them.
Actions provided by items (like the ninja suit) are stored on the item entity.
