### ISSUE TITLE
Rejuvenate command/verb should reset cooldowns

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#20261]
Specifically action and `UseDelayComponent` cooldowns. Makes testing things like the ghost-boo action easier.

Should be easy as just subscribing to the `RejuvenateEvent` with `ActionsComponent`, and then setting the cooldown of all action in the component. ~~The actions system  `SetCooldown()` method also needs to be changed to support clearing the cooldown, because it currently doesn't take in null values.~~ #21517 added a method to clear the cooldown of an action.

**Comment by AlbertSnows** [comment]
Hi, some clarifying questions as a potential new contributor
-  What is the subscribing system? That is, what system is meant to subscribe `ActionsComponent` to `RejuvenateEvent`? Would it be `ActionsSystem`?
- `ActionsComponent` contains a collection of actions. Where can I learn more about what these actions look like? I ask because at the moment it's not obvious (to me) that said collection of items have some sort of modifiable cooldown property
- Is systmem an actual concept or typo? I assumed it was action system, but then `ActionsSystem` doesn't have a `SetCooldown()` method. The closest alternative seems to be `SharedActionsSystem`. Would that be the subscribing system you're asking to update? 

Thanks!

**Comment by ElectroJr** [comment]
Sorry about the long response time, I just never saw this comment.

> What is the subscribing system? That is, what system is meant to subscribe ActionsComponent to RejuvenateEvent? Would it be ActionsSystem?

Yeah just putting it in the action system makes sense

> ActionsComponent contains a collection of actions. Where can I learn more about what these actions look like? I ask because at the moment it's not obvious (to me) that said collection of items have some sort of modifiable cooldown property

There was an refactor not to long ago that changed how actions store data (#19900), so it might've changed since you left this comment, but actions are just entities with action related data stored on the action component (BaseActionComponent). But you should just have to iterate through entities in `ActionsComponent.Actions` and clearing the cooldown of each one.

> Is systmem an actual concept or typo? I assumed it was action system, but then ActionsSystem doesn't have a SetCooldown() method. The closest alternative seems to be SharedActionsSystem. Would that be the subscribing system you're asking to update?

That was just a typo. And yes the method is in the abstract class in the shared namespace. Its pretty common to not bother specifying that it should go in shared. Unless something needs to be server/client specific it should just about always be in the shared namespace/class.

> When you say SetCooldown doesn't take in null values, are you asking for the TimeSpans to be optional?

PR #21517  has since added a method to clear the cooldown, so that bit isn't really relevant anymore,

> Finally, what does the test case for this look like? Is there an action I can test in game to ensure the reset is done correctly?
Thanks!

The easiest action to test with would be the "ghost boo" action that ghost can use to make lights flicker, mainly because that action has a very long cooldown.
