### ISSUE TITLE
should be traits limit

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#20501]
why?
it's very weird speech, when selecting all accent traits
OR
make limit only to accent traits

**Comment by LankLTE** [comment]
I mean if someone wants to have every accent trait I don’t really see why that’s a problem

**Comment by Aisu9** [comment]
command players with wheelchairbound/blind/mute be like

**Comment by UbaserB** [comment]
i kind of agree with this. Its also detrimental when you get a captain with ALL traits.

**Comment by deltanedas** [comment]
command, especially captain, should be banned from having mute and blind traits its just too detrimental

**Comment by LankLTE** [comment]
God forbid you have to play one round without a captain.

**Comment by deltanedas** [comment]
yes i agree the solution is to kill and replace him!!!

**Comment by Just-a-Unity-Dev** [comment]
> God forbid you have to play one round without a captain. 

The real issue is people queuing up for captain intentionally with all traits enabled to make the round worse for everybody, blocking those who actually want to play captain. Admin issue of course but having every accent attached to you can quickly flood chat with too much text that doesn't need to be seen.

**Comment by LankLTE** [comment]
> The real issue is people queuing up for captain intentionally with all traits enabled to make the round worse for everybody, blocking those who actually want to play captain. Admin issue of course but having every accent attached to you can quickly flood chat with too much text that doesn't need to be seen.

I mean yeah but the best thing I can say is that it's an admin issue if they're doing it consistently, same way it is if they picked captain and fucked around every round. Allowing traits on command can lead to a lot of fun experiences so just outright banning them is something I'm not a huge fan of.

**Comment by deltanedas** [comment]
blind mute and wheelchair bound basically give cap a kill sign to any syndie
the others are ok on their own but combined are bad, like a captain with every single speech trait being unintelligble

**Comment by Mirino97** [comment]
At the moment we only have detrimental or neutral traits
I believe at some point we'll have positive traits, and when that happens, a point system should be implemented, kinda like 13 does.
At the current time, if someone wants to have terrible speech, I believe it's fine.

**Comment by Just-a-Unity-Dev** [comment]
> just outright banning them is something I'm not a huge fan of

It's a trait _limit_, not a trait _ban_

**Comment by forgotmyotheraccount** [comment]
Should specify that only speech/accent traits are the issue here. If someone wants to RP as a mute, deaf guy in a wheelchair, that's fine; they're only limiting the round for themselves. If someone wants to RP as a socially anxious dwarf with a lisp, they're degrading the round for everyone.

There's been talks of nerfing the social anxiety trait, which should probably happen, but the lack of a limit is the core issue. Over time the amount of speech traits is going to go up, not down, readability is only going to get worse as time goes on. I'd say you should get two max, species accents included.
