### ISSUE TITLE
Arrows inject chems when they shouldn't

### ISSUE THREAD

**Issue by dolgovmi** [space-wizards/space-station-14#20708]
## Description
If you throw an arrow at a person or whoever, it will inject it's chems into them, while not hitting them and flying past.
Probably shouldn't be like that since it doesn't actually hit?

**Reproduction**
1. Put poison on arrow
2. Throw at a person
3. Arrow flies past
4. Person still got injected

**Comment by notquitehadouken** [comment]
what if it just embedded when thrown

**Comment by Hades785** [comment]
Some observations:
- The projectile collision bypass, making it so walking on or throwing the arrow doesn't behave as if it was shot, works fine https://github.com/space-wizards/space-station-14/blob/37f22a8baf53571697db070b035833eed8869e9c/Content.Server/Projectiles/ProjectileSystem.cs#L32-L34
- The issue arises from the solution inject on collision not ignoring the collision, since only `ProjectileComponent` is configured with an ignore collisions flag, so only `ProjectileSystem` knows to do it https://github.com/space-wizards/space-station-14/blob/37f22a8baf53571697db070b035833eed8869e9c/Content.Server/Chemistry/EntitySystems/SolutionInjectOnCollideSystem.cs#L35-L60
- If someone tips an arrow with some solution and throws it, and the arrow does not collide with an entity with a bloodstream, then it is possible that the thrower gets injected with the solution instead.
