### ISSUE TITLE
Storage feedback

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#21248]
Gather feedback and what needs changing, i.e. UI / sizing / code / whitelists.

**Comment by spectralSpices** [comment]
Well, I'll hit the basic ones I've seen mentioned-pills and handguns take up the same amount of space, and people are fitting hardsuits into bags, which seems like an issue. As is, I think having nested storage as the go-to is allowing stuff like people fitting 42 C4 into a single duffel or tossing an entire engineering department's hardsuit count into one.

**Comment by keronshb** [comment]
# Feedback

## UI
- There should be more feedback on how much space an item takes up.
- There should be another visual other than "FULL" (maybe a volume bar?)
- My backpack below is full but didn't hit the max storage slots I saw 
![image](https://github.com/space-wizards/space-station-14/assets/54602815/ab3431af-3d71-494b-ad6a-54f7b5a63709)
- It showed 3/7 beforehand, and if I remove another one I have 2/7
![image](https://github.com/space-wizards/space-station-14/assets/54602815/805c1d60-d1a7-4f0c-871c-e783831c8415)
- An idea is to represent it with the background. A full bar could mean max space:
![image](https://github.com/space-wizards/space-station-14/assets/54602815/c1485f1b-95dc-4602-ae21-a513127b2046)
- Where a shorter bar could mean less weight:
![image](https://github.com/space-wizards/space-station-14/assets/54602815/e3d61316-de06-42ca-9a97-481ef807e618)
(Just pretend the background is that small)
- You could have stack sizes change size depending on the number in the stack:
![image](https://github.com/space-wizards/space-station-14/assets/54602815/4a8b1f46-83f8-4810-9585-a74e4df74f45)

## Sizing
- Not sure if this is for actual item size (tiny, etc) or if it's for how much it actually takes up
- You could have stack sizes change size depending on the number in the stack:
![image](https://github.com/space-wizards/space-station-14/assets/54602815/4a8b1f46-83f8-4810-9585-a74e4df74f45)
### Engineering Sizing
- This is pretty comfy in terms of having a stacked engie loadout:
![image](https://github.com/space-wizards/space-station-14/assets/54602815/ddacf129-6fd8-466c-99bf-bdabe4a41f70)
- But I do feel the current item size is a bit limiting (I could get rid of one of the medipens, flare, and meat but I left them for fluff)


## Code
- This is probably more sizing but bear with me.
- Regular backpacks/satchels should be upgraded to 21 size, after balance adjustments come out for item space/size.
- This will give people more leeway without it being too encumbering.
- Maybe SOME limit on boxes if sizes go up to 21 (3ish boxes or  box-likes maximum if default size = 21?)
- Regular backpacks should not fit anything over medium size
- Dufflebags should go from 10 > 31, should hold large sizes (prevent backpacks from being put in) but give you 20%-30% slowdown when holding/wearing/dragging

## Whitelists
### Medium/Large Guns
- For Shotguns/L6 Sized Guns
- I shouldn't be able to fit these into my regular backpack at all:
![image](https://github.com/space-wizards/space-station-14/assets/54602815/84ef42f5-548d-4a32-860a-a3478c740d12)
- One idea is for certain bags (Ie Sec, Nukie, etc) to have a singular dedicated medium/large gun slot.
### Tasers/Small Guns (Sec Belt)
![image](https://github.com/space-wizards/space-station-14/assets/54602815/9685651f-cf5f-4990-9bfa-5c73b9d1a47e)
- There probably should be at least 2 small guns max allowed in the sec belt. Multiple of everything else is fine so far?

# Bugs

## UI
![image](https://github.com/space-wizards/space-station-14/assets/54602815/d025bb55-1670-4d04-b76c-d569a0590962)
Long names extend into the size descriptions

## Sizing
- Just a general sweep of item balancing

## Code
- Just a general sweep of item balancing

## Whitelists
N/A

**Comment by Cheackraze** [comment]
incredibly poorly implemented, exacerbates every single issue that it sought to resolve, increases the maintenance and balance across literally thousands of entities, was incredibly rushed, no feedback was implemented, and causes almost the entirety of the game's systems to become unbalanced.

forcing a resource scarce modeled inventory system in a resource rich paradigm of game design, the two are fundamentally incompatible and will just cause an endless amount of pain to bring anywhere close to a 'balanced' or even enjoyable to play state. Should be immediately reverted until a more well thought out and actually thought out and planned system can be designed, not this rushed disaster.

**Comment by metalgearsloth** [comment]
> Should be immediately reverted until a more well thought out and actually thought out and planned system can be designed, not this rushed disaster.

Don't post garbage, didn't think I'd have to state in the OP.

**Comment by Cheackraze** [comment]
> > Should be immediately reverted until a more well thought out and actually thought out and planned system can be designed, not this rushed disaster.
> 
> Don't post garbage, didn't think I'd have to state in the OP.

excuse me? Are you actually wanting feedback or no?

**Comment by Carolyn3114** [comment]
guns/bags/hardsuits/large jetpacks shouldn’t be able to fit in bags (or at least, should take up 6-7 space)
 guns and stuff shouldn’t be able to fit in belts (or again, should take up more space in the belts)
other than that, with this, and the “only one inventory at a time” PR, I think there should be a hud rework that makes the bags look more like how modern goonstation/tg have them

**Comment by metalgearsloth** [comment]
1. Untrue, it barely changed storage system.
2. You need to explain your points not handwave it.
3. No it doesn't. 5 sizes is less than dozens.
4. No it wasn't.
5. Untrue but you're discord banned so can't read it.
6. This is just useless hyperbole.

This is not an issue to continue spinning in circles and is to address what needs changing.

**Comment by Cheackraze** [comment]
> 1. Untrue, it barely changed storage system.
> 
>     2. You need to explain your points not handwave it.
> 
>     3. No it doesn't. 5 sizes is less than dozens.
> 
>     4. No it wasn't.
> 
>     5. Untrue but you're discord banned so can't read it.
> 
>     6. This is just useless hyperbole.
> 
> 
> This is not an issue to continue spinning in circles and is to address what needs changing.

Ok, so not only have you not adressed a single critique, you're bringing straight irrelevant and harassing language into it?

Im trying to legitimately give criticism to the system and you are just trolling, Please engage in appropriate, on-topic discussions

**Comment by DrSmugleaf** [comment]
> Why is my comment marked as off topic? I am giving legitimate critique to the system as a whole. If anyone would like to actually discuss the merits of it, or any points I have made, I am open to having this conversation.

@Cheackraze It was marked off-topic because of its needlessly confrontational language, feedback without it is fine.
`incredibly poorly implemented, exacerbates every single issue that it sought to resolve` for example is confrontational and hyperbolic, as is `was incredibly rushed, no feedback was implemented` and `Should be immediately reverted ... not this rushed disaster.` "I don't think it correctly addresses the issues it sought to resolve" would be fine, as would "there wasn't enough time for all the feedback to be addressed".
This issue will have feedback that one or more contributors will have to read through to improve and change the system, and they have no obligation to reading comments that will make them uncomfortable doing so. If you are looking to get their feedback addressed by them, do so in a neutral tone.


> Im trying to legitimately give criticism to the system and you are just trolling, Please engage in appropriate, on-topic discussions

You are not giving legitimate criticism, you are leaving inflammatory comments that bait people into answering to them. Stay civil or you will be repo banned. This is your last warning.

**Comment by DrSmugleaf** [comment]
@Cheackraze to correct the post above, seeing as you are not interested in honest and civil dialogue while engaging in spreading misinformation, you are now repobanned:
![image](https://github.com/space-wizards/space-station-14/assets/10968691/9dce9b35-714a-4934-a23a-8ad96ba25cb0)

![image](https://github.com/space-wizards/space-station-14/assets/10968691/6991ab4b-8116-4a4f-a127-c921c6dd5170)

Anyone is welcome to leave feedback as long as they are civil in doing so.
You can appeal on the forums when you feel it is appropriate.

**Comment by Interrobang01** [comment]
<details>
  <summary>this reply is collapsed so i don't get yelled at, i forgot why i wrote this but I think it's important and now i've spent more time apologizing for my shortcomings than actually fixing them, i apologize</summary>


Suggested solution: get rid of nested storage; increase storage size of bags to make up for it

The core assumptions of this argument are that the problems I'm gonna mention are actually problems. I can't argue backwards forever, so arguments as to why these are problems shall be left as an exercise to the reader. I acknowledge that that's really scummy, sorry.

The problems this solution tackles:
1. Nested storage makes everything unfun
2. Everything takes up 1 slot which is goofy (i acknowledge that emogarbage just made a pr that addresses this)
3. Storage systems matter too much, which detracts from all the other gameplay

Suggested implementation:
- Make all storage objects take up a number of slots equal to their capacity (so a box takes 7 slots instead of 1)
- Increase backpack (and belt?) storage to like 20 slots

How this will fix outlined problems:
1. By axing nested storage, it stops being unfun because it doesn't exist anymore. The lost storage capacity is made up for by increased bag capacity.
2. Since bags now have an absurd number of slots, this doesn't matter any more. Sure, you could make arguments that now 20 paper uses as many slots as 20 L6 saws, but where are you even getting 20 L6 saws or 20 paper? All comparisons stop being realistic. The unrealisticness of these hypothetical scenarios translates into realisticness of the system.
3. Bags now have so many slots that people will rarely actually fill them, meaning no more storage gameplay (good)

Counterclaims and Countercounterclaims (there should be more of these, whoops):
CC1. Now you can fit like 20 laser rifles in a bag, far too much
CCC1: In this hypothetical scenario where someone has 20 laser guns and is hauling them around in a bag, the thing to rebalance away is the person getting 20 laser rifles (also with current implementation you can already carry 20 laser guns, just use a locker). That doesn't solve everything though, so as a bonus you could make guns not fit in packs and start leaning into suit storage-like systems.

It's late so I won't be able to reply to this for a while. Also, I spent so long organizing this that I'm not even sure if this is a good solution anymore. I also forgot why I'm writing this reply in the first place. Crap, just get this thing out of my sight, I'm done with this, (author's note: that last line was written 20 minutes ago)
</details>

**Comment by MagnusCrowe** [comment]
@Interrobang01 Have you considered what your proposition might mean for scenarios involving specialized containers like pill bottles, for example?  

Wouldn't what you suggest have a pill bottle take up 9 slots, same as a crowbar, a laser rifle, a coil of LV wire, a jug of bicar, an oxygen tank, a mouse, a flashlight, a lamp, and a pair of handcuffs? All to contain 9 itsy bitsy pills?

Apologies if I misread your post.

**Comment by deltanedas** [comment]
that or just use stalker inventory where unlimited volume but you get slowed down by weight and eventually cant move when at 70kg load :trollface:

**Comment by BlitzGunner225** [comment]
So imma add my 2 cents into the mix 

Actual problems with old storage

1. Boxes such as the emergency box weight is static and always more than what it can contain, meaning it’s an absurd waste of space. Perhaps having it as 15 and then increase to the weight of items inside if above.

2. UI is absurdly huge and is annoying to organize on you screen. Solutions are letting ui boxes magnetize to each other, the choice to make items inside ui appear in a grid system with only sprites until hovered over, and magnets for the corners of the screen for ui boxes

3.  Whitelists require specific items to be written rather than groups and it could use more whitelist options. Could have the ability to whitelist items only under a specific folder and a unwhitelist by default in item scripts.

4. Storage number info takes priority over items in ui when shrinking vertically and wastes space for containers that only have 1 or 1 type of item. Could fix by having the items take priority when under those conditions or an option to disable.

That’s all I can think of in 10 minutes and it seems not a single one was fixed. The new system instead attempts to minimize the amount of items in belts, which has never been a problem, makes precise balancing harder by restricting storage numbers to a smaller and more preset amount, and adds the new problem that storage is extremely abuseable with extra containers in containers. 

I feel next time that major changes like these should be shared at the concept stage so it can be shut down and people can move on rather than waste people’s time in case it ends in community uproar as this new system seems to have done.

**Comment by keronshb** [comment]
This is based from the newest PR #21373

I'll be posting in different parts as I discover more issues, balancing or otherwise.

## Engineering

![image](https://github.com/space-wizards/space-station-14/assets/54602815/92e4cc9f-b9b8-4722-8277-ea0ea23400ae)

- All sizes of cable coils should be able to fit inside of your box, including max stacks.
- Jaws of Life should be able to fit in your toolbelt but not in a box (it can fit in neither right now)
- Currently it's a bit too snug not being able to have enough room for some fluff items & a normal loadout.
- Can't bring a welding mask/goggles with me unless I sacrifice my hardhat slot or mesons slot

It becomes difficult trying to repair the station if you can't carry what you need on you. Engineers need to be able to move quickly so duffels are usually out of the question because they can slow you down (on top of hardsuit slowdown).

## Security

![image](https://github.com/space-wizards/space-station-14/assets/54602815/13b8872c-e549-4187-8bfd-4aecbd734c09)

- Can't fit ammo into the secbelt
- You can fit way too many disablers into your security belt + box + bag

Overall security storage is ok at best and you shouldn't be able to fit an entire armory on you at once, but you also shouldn't be able to fit an entire armory's worth of disablers/tasers on you. You also need more places to store your armmo as needed.

## Nukies

![image](https://github.com/space-wizards/space-station-14/assets/54602815/a2856de8-22fc-46a9-94a3-a25137ca7d4b)

- The Operative Duffel Bag should not have any slowdown
- The pinpointer should fit in your pocket (the captain's can)
- The jetpack should not be able to fit into your backpack
- Kardashnev-Mosin should be able to fit on the blood-red hardsuit's exo slot

Nukies have a decent amount of room for their loadouts, just some small things to change here.

A note on traitors: Same issue as engie, sorta? Just make sure they can have enough of a loadout + be able to safely carry steal items.

## Plant/Ore Bags

![image](https://github.com/space-wizards/space-station-14/assets/54602815/38ab7a34-40d9-4734-8f0f-1565ee0fa25b)

I feel these should stack but also look how many gatfruit you can carry in one plant bag (not even full yet)

## Heads/Captain

![image](https://github.com/space-wizards/space-station-14/assets/54602815/fa6ecf45-1309-4048-a1d3-24266272e927)

- I should be able to fit the antique laser pistol and other guns onto the captains carapace/winter coat/etc's exo suit slot
- It gets really snug if I want to have my antique & flash & disabler, even if I could fit something in my exosuit slot

Assuming the captain doesn't take their jetpack with them, it's _really_ hard to carry the basics & have room for other potential items (food, drink).

## Misc

![image](https://github.com/space-wizards/space-station-14/assets/54602815/6cf7c9d5-bec2-4e87-863b-bdc9200f0a8c)
![image](https://github.com/space-wizards/space-station-14/assets/54602815/4f2885b7-9908-4e0f-8fd2-2a9b1f8a1f7c)

- Syndicate Dufflebag is Huge where a Toolbelt is Ginormous

![image](https://github.com/space-wizards/space-station-14/assets/54602815/a12e7077-c12d-4fd4-aa84-599f6d83fd30)

- I can fit TOO many revolvers on me (thanks gatfruit)

## Summary

This is at a better place but there's still areas that can be improved such as:

- Storing TOO many small guns like tasers/revolvers
- Some jobs like Engineers or Heads reach capacity and need more room for other things
- Item size tweaking

**Comment by deltanedas** [comment]
bruh why is antique laser same size as a flash

**Comment by metalgearsloth** [comment]
@BlitzGunner225 

> That’s all I can think of in 10 minutes and it seems not a single one was fixed. The new system instead attempts to minimize the amount of items in belts, which has never been a problem, makes precise balancing harder by restricting storage numbers to a smaller and more preset amount

Whitelists require going through and manually removing them when we find something we're happy with obviously. Precise balancing is an oxymoron considering numbers were largely random and not consistent.

> I feel next time that major changes like these should be shared at the concept stage so it can be shut down and people can move on rather than misuse people’s time in case it ends in community uproar as this new system seems to have done.

It was, on discord, hence the discussion around "let's try it and see what works" not "let's never change anything". If you were still there you'd also see gridventory is going to get tried.

**Comment by BlitzGunner225** [comment]
>If you were still there you'd also see gridventory is going to get tried.

To clarify what I said would only affect visuals and not mechanics 

Saying no one balances precisely does not take into consideration future servers, future proofing, and still factually removes customizability which is bad (there is a reason most games use 100 hit points rather than 10). 

Also talking about a game changing feature in a space where like half of the fork owners CAN’T see it is unhealthy for the community. That also doesn’t include the players banned who play the game on other branches and are by definition apart of the community.

**Comment by BlitzGunner225** [comment]
Ah a new 4th edition

well it does feel better to the point that it’s mildly acceptable, it still feels like a downgrade and it does not fix any of the big problems with inventory. Packs are essentially back to how they were before storage wise. Belts/slots are limiting due to decreasing the storage balance variables (item weight, pack capacity, and pack movement speed) from 3 to 2 and was never a problem with whitelists and the storage number. Item balance, while now containing multiple presets rather than one is still more restricted in balance. You could just keep the high/flexible values, keep the idea of multiple presets or list them in a public game design doc, and get rid of the limiting slot system.

It just feels a bit pointless putting in so much effort to get a feature to work that most people weren’t complaining about rather than extremely important features such as mind and surgery. m

**Comment by deltanedas** [comment]
> extremely important features such as mind and surgery.

both of which are being worked on :trollface:

**Comment by BlitzGunner225** [comment]
> > extremely important features such as mind and surgery.
> 
> both of which are being worked on :trollface:

And have had little to no progress over the past 2 years

**Comment by BlitzGunner225** [comment]
> > And have had little to no progress over the past 2 years
> 
> Every single person who works on this project is an unpaid volunteer working out of their own volition, as a hobby. There are no professional studios or companies behind the project, we are just a group of people passionate about game development. As such, not a single one of us is forced to unwillingly contribute our time to Space Station 14, we all have a life. Most of us have a job or studies, and all of us contribute to this project in our free time.
> 
> In short, nobody is obligated to work on any feature, regardless of how urgent or important you or anyone else thinks it is. If you want it, you are perfectly capable of creating it and submitting a pull request yourself.

I know that this is volunteer work but I’m saying that rather than people putting so much effort into their own content, even against most of the community’s wishes, that they should instead think about everyone else and maybe work on the stuff that needs to get done.

**Comment by mirrorcult** [comment]
> 
> I know that this is volunteer work but I’m saying that rather than people putting so much effort into their own content, even against most of the community’s wishes, that they should maybe instead think about everyone else and maybe work on the stuff that needs to get done.

> If you want it, you are perfectly capable of creating it and submitting a pull request yourself.

**Comment by LordEclipse** [comment]
> > > And have had little to no progress over the past 2 years
> > 
> > 
> > Every single person who works on this project is an unpaid volunteer working out of their own volition, as a hobby. There are no professional studios or companies behind the project, we are just a group of people passionate about game development. As such, not a single one of us is forced to unwillingly contribute our time to Space Station 14, we all have a life. Most of us have a job or studies, and all of us contribute to this project in our free time.
> > In short, nobody is obligated to work on any feature, regardless of how urgent or important you or anyone else thinks it is. If you want it, you are perfectly capable of creating it and submitting a pull request yourself.
> 
> I know that this is volunteer work but I’m saying that rather than people putting so much effort into their own content, even against most of the community’s wishes, that they should maybe instead think about everyone else and maybe work on the stuff that needs to get done.

That encourages toxic behavior. If you are coding for free, Why should you be forced to acquiesce to people's requests or demands just because you took the time and effort to learn how to code, and they didn't?

**Comment by BlitzGunner225** [comment]
> > > > And have had little to no progress over the past 2 years
> > > 
> > > 
> > > Every single person who works on this project is an unpaid volunteer working out of their own volition, as a hobby. There are no professional studios or companies behind the project, we are just a group of people passionate about game development. As such, not a single one of us is forced to unwillingly contribute our time to Space Station 14, we all have a life. Most of us have a job or studies, and all of us contribute to this project in our free time.
> > > In short, nobody is obligated to work on any feature, regardless of how urgent or important you or anyone else thinks it is. If you want it, you are perfectly capable of creating it and submitting a pull request yourself.
> > 
> > 
> > I know that this is volunteer work but I’m saying that rather than people putting so much effort into their own content, even against most of the community’s wishes, that they should maybe instead think about everyone else and maybe work on the stuff that needs to get done.
> 
> That encourages toxic behavior. If you are coding for free, Why should you be forced to acquiesce to people's requests or demands just because you took the time and effort to learn how to code, and they didn't?

I’m not saying to force people, just recommending that they look at the bigger picture. Also some are considering the extreme push to get the new system to work, against most of the community’s wishes, as being a bit toxic.

**Comment by BlitzGunner225** [comment]
> > I know that this is volunteer work but I’m saying that rather than people putting so much effort into their own content, even against most of the community’s wishes, that they should maybe instead think about everyone else and maybe work on the stuff that needs to get done.
> 
> > If you want it, you are perfectly capable of creating it and submitting a pull request yourself.

I’m busy trying to figure out College now that I’m in it.

**Comment by retequizzle** [comment]
> > > > > And have had little to no progress over the past 2 years
> > > > 
> > > > 
> > > > Every single person who works on this project is an unpaid volunteer working out of their own volition, as a hobby. There are no professional studios or companies behind the project, we are just a group of people passionate about game development. As such, not a single one of us is forced to unwillingly contribute our time to Space Station 14, we all have a life. Most of us have a job or studies, and all of us contribute to this project in our free time.
> > > > In short, nobody is obligated to work on any feature, regardless of how urgent or important you or anyone else thinks it is. If you want it, you are perfectly capable of creating it and submitting a pull request yourself.
> > > 
> > > 
> > > I know that this is volunteer work but I’m saying that rather than people putting so much effort into their own content, even against most of the community’s wishes, that they should maybe instead think about everyone else and maybe work on the stuff that needs to get done.
> > 
> > 
> > That encourages toxic behavior. If you are coding for free, Why should you be forced to acquiesce to people's requests or demands just because you took the time and effort to learn how to code, and they didn't?
> 
> I’m not saying to force people, just recommending that they look at the bigger picture. Also some are considering the extreme push to get the new system to work, against most of the community’s wishes, as being a bit toxic.

That's a "them" issue tbqh, they are invited to the same opportunity that was presented to you and can PR things they would like to have done themselves if they are not satisfied with waiting. 

At this point, the heckling over what features do or do not get added needs to stop, especially when a decent proportion of the heckling/complaining/bitching is coming from people who don't actively contribute anything to the project.

**Comment by BlitzGunner225** [comment]
> > > > > > And have had little to no progress over the past 2 years
> > > > > 
> > > > > 
> > > > > Every single person who works on this project is an unpaid volunteer working out of their own volition, as a hobby. There are no professional studios or companies behind the project, we are just a group of people passionate about game development. As such, not a single one of us is forced to unwillingly contribute our time to Space Station 14, we all have a life. Most of us have a job or studies, and all of us contribute to this project in our free time.
> > > > > In short, nobody is obligated to work on any feature, regardless of how urgent or important you or anyone else thinks it is. If you want it, you are perfectly capable of creating it and submitting a pull request yourself.
> > > > 
> > > > 
> > > > I know that this is volunteer work but I’m saying that rather than people putting so much effort into their own content, even against most of the community’s wishes, that they should maybe instead think about everyone else and maybe work on the stuff that needs to get done.
> > > 
> > > 
> > > That encourages toxic behavior. If you are coding for free, Why should you be forced to acquiesce to people's requests or demands just because you took the time and effort to learn how to code, and they didn't?
> > 
> > 
> > I’m not saying to force people, just recommending that they look at the bigger picture. Also some are considering the extreme push to get the new system to work, against most of the community’s wishes, as being a bit toxic.
> 
> That's a "them" issue tbqh, they are invited to the same opportunity that was presented to you and can PR things they would like to have done themselves if they are not satisfied with waiting.
> 
> At this point, the heckling over what features do or do not get added needs to stop, especially when a decent proportion of the heckling/complaining/bitching is coming from people who don't actively contribute anything to the project.

Dude some people don’t have the time to learn how to code and shouldn’t be forced to as some sort of right of passage. I agree some people can get a bit toxic but there are plenty offering actual valid criticisms that should be listened to. And you don’t need to follow what people say but in scenarios like these where I’ve only found backlash, maybe you should rethink this stuff back to foundation to find out what it all means.

**Comment by EmoGarbage404** [comment]
i genuinely can't believe you're still rattling on about this trite shit so let me just spell it out clearly for you so you can understand why your point is dumb.

abso-fucking-lutely no one on the entire project is entitled to code *anything*. Not a single person here is operating on any kind of schedule or mission or goal that is in any way distinct from their personal vision of what they want to do for the project. 

Sorry to break this down for you but this feeling you have that the people should be focusing on "the bigger picture" in terms of some kind of development roadmap is quite simply just entitlement. If a person isn't working on it, it's because they don't want to and that's _100% okay._ So please, kindly, shut up about this "big picture" high horse that you feel the need to preach about. Especially considering your last contribution to the repository was literally over a year and half ago, I don't really think you have a good picture of what would be best for the overall big-picture development of the game.

Whinging aside:

> Dude some people don’t have the time to learn how to code and shouldn’t be forced to as some sort of right of passage.

Dunno how to spill this one to you other than this: a sizable amount of the people contributing to this project have no prior experience developing games or even coding at all. Many frequent contributors don't even code, choosing instead to use YAML markup to add assets or to contribute art or maps to the game. 

Putting in the time to help is the mark of a contributor: it is a literal, tangible embodiment of the work that a person has put into the game. It is a mark of knowledge, experience--and most of all--dedication to a community to put in the effort to be able to contribute to a larger whole. There is a reason that the people who put in the effort to do so are more respected and held to a higher standard.

> but there are plenty offering actual valid criticisms that should be listened to

I don't know why people keep going on about this but i'll just clarify this real fucking cleanly:
- BEFORE THE TESTMERGE: extended github and discord discussions regarding pros/cons and reasoning for why the changes were being made.
- AFTER THE TESTMERGE: again in discord, specific balancing issues being addressed and discussions were being held talking about various features and sentiments.
- AFTER THE 2ND MERGE: _Another round of balance discussions_, including decisions to make changes that i personally was opposed to but had larger community support. The move away from slot-based was _specifically_ because of community feedback. I personally liked it.
- NOW: We are literally STILL making balance changes in accordance to community feedback as well as brainstorming further changes to the system to make it more palatable and worthwhile of a mechanic. 

I get that you're not in the discord but i'm not sure why you're acting like there's some kind of oligarchy choosing how this gets done. 

> against most of the community’s wishes

You seem to have this strange illusion that space station 14 is, as a whole, a democratically made game, wherein every player should have their input voted up like some kind of Athenian election. The reality is that while players' feedback is an important cycle that is _**consistently and frequently**_ taken into account in terms of balancing and refining mechanics to be palatable, players are not the ones choosing what is being added or removed from the game.

The game exists as it is due to the consistent work of the many individuals who have contributed to the project while ultimately being shaped by the maintainer team, who diligently work to keep the game and project running. These aren't closed doors, but there is a barrier to entry; a barrier defined by the dedication and work that our contributors invest in the project. These people with the skills to build, reinvent, and support the game are the ones who shape it, wholly separate to the opinions of those who did not imbue themselves in the creation of this big hunking project that we all care about.

so would you kindly stop flooding this damn thread with pointless whinging?
thanks.

**Comment by deltanedas** [comment]
![19:38:50](https://github.com/space-wizards/space-station-14/assets/39013340/7ef25ac3-fe2c-40e7-904d-3618c7171d62)

:trollface:
empty susbox (mapper only???) gets 1 less slot
susbox can hold 7/8 pneumatic cannons which can old 8 normals items 
:trollface:

**Comment by deltanedas** [comment]
combat medkit is normal
![15:22:22](https://github.com/space-wizards/space-station-14/assets/39013340/6ef18567-dc9e-43cf-a938-a2aa3f68552f)

possible fix is making it large and giving agent chest rig whitelist + max item size large

**Comment by slarticodefast** [comment]
Considering that we now have gridstorage making this discussion about the old system obsolete I think this issue can be closed.
