### ISSUE TITLE
Moving text cursor to the Left/Right is broken. Using Up/Down for the console history is broken too.

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/space-station-14#2143]
I'm gonna point my blame finger at the tetris arcade PR

**Comment by PaulRitter** [comment]
definitely due to #2131 registering new keyfunctions, specifically "Aracade[Up|Down|Left|Right]" which all point to the respective arrow key. Someone who knows more about the keyfunction-system should look over this, i don't know what i could have done wrong... do we support multiple keyfunctions per key? (if not we should)
