### ISSUE TITLE
plants dont need nutrient to grow

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#21494]
## Description
they shouldnt be able to progress growth stages at all if theres no nutrient or water

![18:57:09](https://github.com/space-wizards/space-station-14/assets/39013340/957689da-3d61-4fa1-b573-8604fe56d3b5)

these grew to full with no complications

**Comment by CatMagic1** [comment]
Pretty sure water is also useless

**Comment by Brandon-Huu** [comment]
This is happening because of these two parts of code.

https://github.com/space-wizards/space-station-14/blob/fb60a5695092b05e713476ff4f6b3960b17b1cff/Content.Server/Botany/Systems/PlantHolderSystem.cs#L444-L445

https://github.com/space-wizards/space-station-14/blob/fb60a5695092b05e713476ff4f6b3960b17b1cff/Content.Server/Botany/Systems/PlantHolderSystem.cs#L461-L462

There is only a 35% chance for either of these two cases to trigger during a update.
When the above two if statements are true ( component.SkipAging ) is incremented by one.

However the code below executes every update.
https://github.com/space-wizards/space-station-14/blob/fb60a5695092b05e713476ff4f6b3960b17b1cff/Content.Server/Botany/Systems/PlantHolderSystem.cs#L407-L409

**Comment by UbaserB** [comment]
This issue has been resolved.
