### ISSUE TITLE
PDA apps are kinda broken

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#21561]
## Description

Clicking install NetProbe will spawn a new Install NetProbe button 

**Reproduction**

**Screenshots**

![зображення](https://github.com/space-wizards/space-station-14/assets/71643624/ac085c38-5d73-4ad9-8607-09ca29d452a6)

**Additional context**

**Comment by notquitehadouken** [comment]
Is this on wizard's den or a fork?

**Comment by GoodWheatley** [comment]
> Is this on wizard's den or a fork?

Reproduced on master.

**Comment by 0x6273** [comment]
> Is this on wizard's den or a fork?

I can reproduce it here. Seems like not a regression, a check for duplicates just never got implemented. There's a todo in CartridgeLoaderSystem.

https://github.com/space-wizards/space-station-14/blob/a367097c33591f461aa875461054a9a596ccee3f/Content.Server/CartridgeLoader/CartridgeLoaderSystem.cs#L194-L194

Fixing this seems like it would require comparing proto IDs, due to the way PDA software is currently implemented.

**Comment by IProduceWidgets** [comment]
I think this is intended. The cartridges are reusable, and the PDAs have a max apps variable.

**Comment by VasilisThePikachu** [comment]
If theres a todo to remove this function then its probably unintended. Theres also no reason to install the same pda app multiple times.
