### ISSUE TITLE
NaN/infinities in atmos

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#21645]
## Description
On round 38116 on Salamander, a pressure value apparently became NaN/infinity and killed everyone.
Apparently someone reached insane pressures and temperatures in Science, which probably lead to this bug. Spectate Nevaeh Pfiefer.

Suits did not protect against the pressure.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/45957058/6c1c4332-e7d9-4359-8f3f-7c9ef79860d7)

**Additional context**
People on atmos blockers (holofans/tiny fans) survived.

**Comment by MACMAN2003** [comment]
holy shit that's me in the screenshot
im famous

**Comment by deltanedas** [comment]
cheers ietf

**Comment by UbaserB** [comment]
terrifying

**Comment by BasedUser** [comment]
ITS NOT ME THIS TIME I FUCKIGN SWEAR

**Comment by deltanedas** [comment]
you are killer

**Comment by notquitehadouken** [comment]
haha, wrench go _*the sound of the sun exploding*_

**Comment by Partmedia** [comment]
I'm going to chime in with what I know about this issue:

I suspect it was introduced with https://github.com/space-wizards/space-station-14/pull/22803. I tried to fix it with https://github.com/space-wizards/space-station-14/pull/22876, however the problem kept happening. There is a problem that is related but likely not the cause of this problem, and a fix was in https://github.com/space-wizards/space-station-14/pull/22907.

The linked issue https://github.com/space-wizards/space-station-14/issues/22885 was likely fixed by https://github.com/space-wizards/space-station-14/pull/22464 because the issue went away for a while (see linked reproduction steps). It's still possible that they are related.

What is likely going on is:

1. Something causes a `GasMixture` temperature to be set to a big number, possibly a divide by near-zero.
2. That big number or possibly NaN gets propagated to neighbors by LINDA or through pipes.
3. Any `GasMixture` that interacts with this "corrupted" mix also becomes very big or NaN.

If you find a way to reproduce this issue on a local server, please reply with the steps you did to get this bug to crop up on your local server.

A branch to revert the likely culprit is located [here](https://github.com/Partmedia/space-station-14/tree/notafet/revert). I've asked other maintainers to try this revert if we don't make progress on this in the next day or two.

Thanks for your help and your patience while this gets sorted out.

**Comment by DrMelon** [comment]
Reading through and a ton of our atmos code uses single precision floating point (and associated MathF funcs rather than double precision Math funcs). Are we just degrading through floating point precision error in a bunch of places? We should try using doubles for sensitive math such as atmospheric simulation.

**Comment by Veritius** [comment]
i guess reality stopped collapsing a few months back so im closing this issue
