### ISSUE TITLE
Any simplemob can't pull things

### ISSUE THREAD

**Issue by Anzarot121** [space-wizards/space-station-14#22465]
## Description

https://github.com/space-wizards/space-station-14/pull/21864
You can't pull it off if you play Hamlet, Smile, any spider, any slime, any zombie, any space mob.
Why the hell does changing one mob make a change to ALL mobs?
**Reproduction**

Try pulling something like a mob. It will not work.

**Comment by deltanedas** [comment]
a lot of things use simple mob

**Comment by Anzarot121** [comment]
Should I download Dekstop, change the file to the second solution you suggested in that PR, or can I do it in the browser?

**Comment by deltanedas** [comment]
use git not github desktop :trollface:

**Comment by Errant-4** [comment]
> > ## Description
> > #21864 You can't pull it off if you play Hamlet, Smile, any spider, any slime, any zombie, any space mob. Why the hell does changing one mob make a change to ALL mobs? **Reproduction**
> > Try pulling something like a mob. It will not work.
> 
> Honestly this may be for the better, they don't have hands to pull.

Animals could feasible drag objects with their mouth/teeth. There are many examples, see pizza rat (ironically, that will not be possible since the change was specifically make mice unable to drag)

But I think arguing fron realism to rationalise an accidental change is the wrong approach. No reason has been put forward why drag should be removed from nearly every animal and pet. It makes them more interesting roles to play or be around. It also let's animals drag downed crew toward safety

**Comment by VasilisThePikachu** [comment]
Good enough

**Comment by Errant-4** [comment]
While we are on this, should rats (does that actually mean mice or rat servants? was that _only_ mentioned on the cl because the simplemob proto has a comment about rats?) even be included in this? From what I gather from the other PR, this was done primarily because mothroaches are currently popular due to the novelty factor, and thus there are a lot of them piloted by bored or mischiveous players, causing issues. But what reason is there to suddenly change mice? Have they been a problem? I haven't heard about that and they are not really that common a ghostrole either

**Comment by Anzarot121** [comment]
Mice have never actually been able to pull things

**Comment by VasilisThePikachu** [comment]
Mice have never been able to pull... Rat servents are no longer player controled

**Comment by Errant-4** [comment]
Huh. I wonder why that PR said that in the changelog, then

**Comment by Anzarot121** [comment]
Okay, what are they called in the code? "Rat" doesn't work for searches because there are too many words with those three letters in them.

**Comment by VasilisThePikachu** [comment]
I'm gonna guess it's a comment from when rat servants were player controled

**Comment by Anzarot121** [comment]
I also made it so that the cockroaches couldn't pull things.

**Comment by VasilisThePikachu** [comment]
All you need to do is revert the change to the simplemobs prototype and add the puller component without with "requireshands" to true to the mobs you wanna disallow from dragging

**Comment by Anzarot121** [comment]
And while I'm at it. Zombie NPCs do not attack mothroaches. With what it can be connected? This will be a separate PR in any case.

**Comment by VasilisThePikachu** [comment]
> And while I'm at it. Zombie NPCs do not attack mothroaches. With what it can be connected? This will be a separate PR in any case.

Have a look for factions

**Comment by Anzarot121** [comment]
So, if I put a link to this issue in the PR, if and when the PR is accepted, the issue will automatically close, right?

**Comment by Anzarot121** [comment]
And is there a need for a changelog here?

**Comment by VasilisThePikachu** [comment]
Yes do put a change log, and just put in somewhere in your pr "closes #22465" or "fixes #22465"

**Comment by Errant-4** [comment]
> Okay, what are they called in the code? "Rat" doesn't work for searches because there are too many words with those three letters in them.

mobratservant  mobmouse
