### ISSUE TITLE
when someone goes from crit to dead they stop moving

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#22564]
## Description
1. walk into space
2. bang stick yourself to crit
3. /ghost
4. body stops moving immediately

**Comment by dakamakat** [comment]
@deltanedas  this happens when we disable collision for a entity on dead MobState but i am not found any possibility to disable collision  without stopping movement , is this bug require engine changes or i am wrong? 
![image](https://github.com/space-wizards/space-station-14/assets/52600490/9eeee25c-3bad-4f6a-9394-17182923dd11)

**Comment by deltanedas** [comment]
i think it would need an option for SetCanCollide that preserves velocity yes

**Comment by metalgearsloth** [comment]
Realistically mobs just shouldn't have collisionwake or cancollide turned off.

**Comment by dakamakat** [comment]
thats seems right but now if we do so then we will constantly hit someone in crit on floor , feels like smth like this should be implemented before we can do so #21497

**Comment by Dutch-VanDerLinde** [comment]
issue is fixed
