### ISSUE TITLE
Using gloves whilst wearing gloves

### ISSUE THREAD

**Issue by Jarmer123** [space-wizards/space-station-14#22690]
## Description
 You are able to use gloves whilst they are unequipped. This doesn't feel intended 

**Reproduction**
 Hit someone with gloves that aren't equipped (Rigged gloves/gloves of the north star) 

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/148848017/460799c0-3a21-4152-9a70-624829975a54

**Comment by JoeHammad1844** [comment]
its more riskey than wearing them since you can slip, which invalidates the entire point of glove weapons

**Comment by Kadeo64** [comment]
> its more riskey than wearing them since you can slip, which invalidates the entire point of glove weapons

you still shouldn't be able to do it and northstar + rigged is literally the most overpowered thing in the entire game
also if someone is gonna spend their TC on a melee weapon that isn't the d-sword they're PROBABLY gonna get no-slips.

**Comment by deltanedas** [comment]
the actual issue is just using gloves while they are in-hand not equipped

if that were fixed this is no better than ctrl + b z ctrl + b, to swap between rigged and north star

**Comment by Jarmer123** [comment]
Ye, this is a bug report not a  balance issue

**Comment by The-Beebz** [comment]
It looks like the gloves might be triggering when just held and not equipped because the offending ones to have the MeleeWeapon type. I'd say a melee weapon is typically stuff you just hold in your hand like a knife/bat rather than equip like clothing or armor. 

https://github.com/space-wizards/space-station-14/blob/0237d09510a82e33e7f82a1fb86003cabe0c577f/Resources/Prototypes/Entities/Clothing/Hands/gloves.yml#L345-L362

**Comment by Jarmer123** [comment]
Fixed
