### ISSUE TITLE
fland shuttle too small

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22765]
## Description

fland is a high pop map and the evac courser is simply too small, maybe we could reuse the barratry shuttle?

**Comment by Emisse** [comment]
no to barratry shuttle yes to custom shuttle

**Comment by Emisse** [comment]
if someone wants to port delta shuttle or ceres shuttle id be fine with that too

**Comment by JoeHammad1844** [comment]
ill make my own when my current round is over

**Comment by JoeHammad1844** [comment]
yeah ill port delta
![image](https://github.com/space-wizards/space-station-14/assets/130668733/f7eaab5f-8e48-48e1-99ce-d5665457afb2)

**Comment by JoeHammad1844** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/130668733/bb8b7891-6757-4551-8237-7c61e4f1c7f2)
thoughts?

**Comment by Emisse** [comment]
looks good make sure to add a gyro and thrusters facing all directions and make sure theyre powered, since shuttles should support capacity for manual piloting, flareguy probably wants you to remove firelocks since he wants to test that out on shuttles.

**Comment by JoeHammad1844** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/130668733/3c089018-992a-4b68-9f13-46290a91e3ca)
thrusters and gyro, but im not removing the firelocks unless flareguy tells me

**Comment by JoeHammad1844** [comment]
now what exactly do I do to make it an emergency shuttle in the code?

**Comment by Flareguy** [comment]
Few thoughts:
- Remove the firelocks, testing on meta has gone pretty well from the little of what I've seen.
- Bring back the tool storage room (or replace it with something mundane like a storage room depending on how big you make engi) and put engi in the back. Civilians having nowhere to cower is pretty boring.
- The engi area should be insecure and designed in a way similar to the meta shuttle (unlocked front doors with power stuff behind a windoor) so that camping potential for engis is minimized. I would probably suggest using glass doors if you can make it look good, too.
- Make medical unlocked too, probably
- Probably remove the welding tank and replace it with an emergency suit storage or empty reagent tank or something? Unless you're feeling bold and want to test the waters, of course. Considering the shuttle won't have firelocks though, I probably wouldn't chance it.

**Comment by JoeHammad1844** [comment]
alright, how does this look?
![image](https://github.com/space-wizards/space-station-14/assets/130668733/88e1d31f-abfd-4389-92ab-9a82ab117e62)

**Comment by Flareguy** [comment]
> alright, how does this look? ![image](https://private-user-images.githubusercontent.com/130668733/291808358-88e1d31f-abfd-4389-92ab-9a82ab117e62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTY0MDEsIm5iZiI6MTcwMzA1NjEwMSwicGF0aCI6Ii8xMzA2Njg3MzMvMjkxODA4MzU4LTg4ZTFkMzFmLWFiZmQtNDM4OS05MmFiLTlhODJhYjExN2U2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwNzA4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjBkNDQ5OTVkMDUxZjI4ZGFjYTBiNGRmOTRiNzQ2MmQ2MThiYTFmN2UzNTkwZjNhODQyZjJjZjVhYjRjZGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dg5bYuIM2C4RfANPYlYdJ1DmSBpASZ00YmGvfkD1e9c)

Needs alarmlocks (the ones used in the halls) instead of maintenance firelocks, is probably fine otherwise though.
Don't be afraid to port the equipment stock from SS13 wholesale - without firelocks things will probably get pretty messed up, so it's not unreasonable to have stuff like the medibot or whatever.

**Comment by JoeHammad1844** [comment]
yeah i put a medibot in medical

**Comment by JoeHammad1844** [comment]
also that white crate is inflatable walls

**Comment by JoeHammad1844** [comment]
heres the engi area, the engi airlocks are unlocked, the external airlocks are locked with externals access and have fans
![image](https://github.com/space-wizards/space-station-14/assets/130668733/158794c4-9a93-4891-8e5e-42dfc2b5b462)

**Comment by JoeHammad1844** [comment]
i think its done, what needs to be done next to have it how up as a shuttle, give it a name, ect

**Comment by JoeHammad1844** [comment]
just remembered gravgen

**Comment by JoeHammad1844** [comment]
#22776
