### ISSUE TITLE
thieves do not appear on round summary

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#22977]
## Description
you wont appear on round summary if you're a thief

**Reproduction**
become thief
round end
you cannot see your objectives

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/45323883/76bce767-f0e5-4de6-b898-d0f6528c2343)

if you are both thief and a syndicate, your thief objectives will appear but only because you're also a syndicate
otherwise, nothing happens

**Additional context**

**Comment by deltanedas** [comment]
currently the thief rule component is added to traitor/rev rules with a % chance of being removed when players are added

instead i think it would be better if it was just a component for rules to *start another rule* on round start, then the thief rule can just have simple antag component for standalone objectives + probably easier to exclude traitors and headrevs since its janky

@TheShuEd

**Comment by Dutch-VanDerLinde** [comment]
thieves also appear on round summary during rev and nukie rounds

only in syndie rounds is where they dont appear

**Comment by Varen** [comment]
> thieves also appear on round summary during rev and nukie rounds
> 
> only in syndie rounds is where they dont appear

Just had a rev round and the thief did not appear.

**Comment by Dutch-VanDerLinde** [comment]
> > thieves also appear on round summary during rev and nukie rounds
> > only in syndie rounds is where they dont appear
> 
> Just had a rev round and the thief did not appear.

yeah sometimes it appears on rev rounds, sometimes it doesnt, so strange

**Comment by TheShuEd** [comment]
Yay
