### ISSUE TITLE
Being zombified as a wheelchair-bound character makes you immobile

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#22990]
## Description
You can't move.

**Reproduction**
1. Spawn as a wheelchair-bound character
2. Chug some romerol
3. Stab yourself to death
4. Become a statue

**Comment by themias** [comment]
The issue seems to be that you get unbuckled from the wheelchair when you go crit. If you are Initial Infected in a wheelchair, you can still use your chair and attack as a zombie. (I think the unbuckling is meant to prevent moving in vehicles when in crit.)

The solutions I can think of:
1. Remove the WheelchairBound/LegsParalyzed components on zombification. This is the easiest, but would be kind of weird, especially if you get cured of zombification and are now no longer paralyzed.
2. Try to buckle them back in upon zombification, the same as on startup. I tried this, but it is tricky due them not having hands as a zombie. Plus there would be a magically spawned new wheelchair.
3. Implement a crawling system. This would probably be the best solution, but would probably need a fair bit of design/review, etc. #21861
