### ISSUE TITLE
Restart vote results no output when admin online

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#23182]
## Description
During restart votes, results are not outputted to chat nor adminlogs when an admin is online. 

**Reproduction**
>be admin
>restart vote ran
>receive no results output
>cry in logless hell

**Comment by LankLTE** [comment]
No output is intentional, as I didn’t quite know what to put and didn’t exactly want to make it clear it’s because there was no admin on (like the old vote block just said “this is unavailable” with no further info). 

There should be logs for the passed vote being cancelled due to an online admin, however. Can someone verify that there actually aren’t any?

**Comment by TurboTrackerss14** [comment]
Confirmed vote results are logged in non-player logs.

However an output to adminchat or related admin text would be helpful to prevent adminlog diving.
