### ISSUE TITLE
Emergency light effect looks off 

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2320]
![GIF 20-Oct-20 12-00-58 PM](https://user-images.githubusercontent.com/701959/96604935-074c4780-12cc-11eb-9f9f-f30860b9775b.gif)

the spinning light cone from the emergency light is a few steps off from the light object itself, to the point where it gets iluminated when the cone is aiming at the wallmount

**Comment by PaulRitter** [comment]
this is due to the emergencylight sprite not being centered on 0,0, but being offset to the north.

to fix this you would either
a) center the sprite and all currently placed emergency lights (bad way imo)
B) subscribe to the rotate-event of the owner of an emergencylight component and change the offset of the pointlight on rotate (better way imo)

**Comment by SweptWasTaken** [comment]
Emergency Light also looks kinda dumb because it's sprite is lit instead of unlit
