### ISSUE TITLE
Revenants shouldn't be able use their powers in the chapel

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#23263]
## Description

They cant in ss13 and its a cool feature so they shouldnt in ss14

**Comment by Aisu9** [comment]
revenants already can't do shit unless someone left a corpse unsupervised(because absolutely no one is leaving a corpse in one piece OR the corpse is already in medbay or surrounded by 5 people)
Revenants should get a buff and gain ability to start doing shit before nerfing their ability to do anything(as a reminder they cannot even put a singular person to sleep so they can absorb their soul, this was removed when the diseases were removed from the game, care to give the revenant a single target sleep?)

**Comment by deltanedas** [comment]
if they had sleepy virus again this would be ok

**Comment by Aisu9** [comment]
> if they had sleepy virus again this would be ok

viruses have still a long way before they get back in, a sleeping "spell" would be nice

**Comment by Varen** [comment]
It'd likely be easier to make it "Near the god altars" rather than "the chapel", as the ss13 thing is based off map zones.

**Comment by Emisse** [comment]
agree we arent implementing areas

**Comment by UbaserB** [comment]
oh yeah i forgot revenants were underbalanced, my bad
