### ISSUE TITLE
Ninja abilities don't work

### ISSUE THREAD

**Issue by asperger-sind** [space-wizards/space-station-14#23688]
## Description

When trying to use ninja abilities that cost power they do not work, instead a popup appears saying that the ninja suit does not have enough energy, this occurs at any charge rate from 0% to 100%

Ninja gloves still work.

**Reproduction**

1. Spawn in as a ninja
2. Attempt to use cloak/throwing star/katana teleport
3. Get trolled and go murderboning instead.

**Screenshots**

none

**Additional context**

First reproduced on wizden leviathan at round #43231, the ninja was mostly active on the northern side of the station starting from 40(?) minutes.

I was not playing since roundstart or latejoined, I started as an observer.

**Comment by deltanedas** [comment]
recent trolling idk it worked a week ago

**Comment by Costyyy** [comment]
The issue seems to be caused the delay component that was added in #22502 in NinjaSuitSystem.cs. 
TryComp doesn't find the component and returns false. 
Also, power from the battery still gets used even if the delay check fails so I think that the charge check should be last or have these two checks be separate. 
Having them separate might be preferable to also get a different message when the reason you can't use the ability is the cooldown.
