### ISSUE TITLE
Mimics need to be a gamerule

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#23703]
If a mimic has a 0.1% chance of spawning it needs to be a gamerule, every other mob in the game is managed by gamerules and this shouldn't be an exception, see https://github.com/space-wizards/space-station-14/pull/21997

**Comment by IamVelcroboy** [comment]
I get your point about it spawning in dev and whatnot. But I just don't think gamerule makes sense for this? 

The whole idea was that it replaces a vending machine where a vending machine would normally be. It just kinda makes sense to use the spawner that way because it sets up an expectation that will randomly be a surprise.

I suppose you *could* have an event that swaps out the machine for the mob but I still think you'd want that to run at roundstart. Otherwise, a machine just magically transforms in the middle of the round..?

**Comment by metalgearsloth** [comment]
> The whole idea was that it replaces a vending machine where a vending machine would normally be. It just kinda makes sense to use the spawner that way because it sets up an expectation that will randomly be a surprise.

I suppose you could have an event that swaps out the machine for the mob but I still think you'd want that to run at roundstart. Otherwise, a machine just magically transforms in the middle of the round..?

If you don't want late starts add gamerule support, it makes 0 sense to be spawning mobs outside of gamerules and spawning them on devmap.

**Comment by metalgearsloth** [comment]
Additionally, mimics wander and have 1 fixed sprite which means no surprises are happening anyway.

**Comment by IamVelcroboy** [comment]
OK, well I see the change is up already. That was really fast.
