### ISSUE TITLE
You can put pet carrier in microwave

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#23800]
![image](https://github.com/space-wizards/space-station-14/assets/124214523/7fb8ff34-fe7e-4332-aa37-6233b7efbece)

**Comment by degradka** [comment]
I poked around and found out that you can put anything in the microwave, as long as you can hold it in your hands

**Comment by Tin-Man-Tim** [comment]
items that have the "metal" tag break the microwave and change its state and anything that's plastic gets converted into melted junk. Otherwise, at least from what can be seen in the code anything else just gets popped out after the timer is up. I think the question is what is the expected functionality? Like, do we want the microwave to break whenever something that shouldn't be in there gets cooked? Or should the player just not be able to put a bazooka into the microwave in the first place.

**Comment by GreyMario** [comment]
my thought on the matter is that the max size category you can put in a microwave should be Normal; this fixes pet carriers in microwaves quite nicely
