### ISSUE TITLE
PaI shouldn't be indestructible

### ISSUE THREAD

**Issue by Hmeister-fake** [space-wizards/space-station-14#23902]
## Description
There should be a dead state for PaI's so that they can't survive bombs and such anymore. Maybe an inbetween state for damaged, (repairable with a welder) that applies stutter to them?

## Why
If a PaI survives an explosion in someone's pocket, they can validly metagame who it was, and other reasons.

**Additional context**
Syndicate PaI should get minor explo resistance for funny

**Comment by GreyMario** [comment]
you keep using that word
I do not think it means what you think it means

**Comment by deltanedas** [comment]
its not metagaming its shitty
if cap has a pai there is nothing you can possibly do to prevent it from snitching on binary

**Comment by Errant-4** [comment]
> if cap has a pai there is nothing you can possibly do to prevent it from snitching on binary

That's not entirely true, you can radio jam them and then wipe them with no resistance (assuming you are even aware the pAI is there, made more difficult by them being able to be slotted into PDAs now)
EMP explosions should also have some effect on pAI but currently don't seem to

**Comment by EmoGarbage404** [comment]
Its not metagaming but being indestructible is dumb. Give it a reasonable damage threshole because, while surviving a minibomb to snitch on the bomber isnt metagaming, it is in fact really dumb

**Comment by Errant-4** [comment]
Any change introduced to address this should also consider MMIs and Positronic Brains, they are also currently invulnerable to direct damage

**Comment by Errant-4** [comment]
> also does jammer even work on pai binary channel

Yes (I tried before suggesting that as a solution)

**Comment by deltanedas** [comment]
ok its still shitty since before trolling captain:
- you must realise they have pai
- you must be a syndie and have tc spare for jammer
- you must buy jammer
- there cannot be anyone nearby if you are doing stealth since they will hear pai screaming JOHN SYNDICATE GAVE CAP NOCTURINE HELP x7

**Comment by Errant-4** [comment]
So there are two separate issues here

- pAI are "invisible witnesses" that are hard to counter because you can't really plan for something that you did not see. If you were not aware of their presence you will almost certainly onyy do so once they already incriminated you to everyone on General/all other silicon. I don't know if this is an issue that needs to be fixed somehow, or a skill issue (should have scouted the target better?)
- pAI don't die/become disabled from aoe attacks that you would reasonably expect to leave no one standing, whether or not you were aware of their presence

**Comment by Hmeister-real** [comment]
Was this closed as in they aren't indestructible anymore, or as in Maintainers don't want this (or Emisse no likey)? no PR listed in the first case
