### ISSUE TITLE
CQC for cook 

### ISSUE THREAD

**Issue by ElPidor** [space-wizards/space-station-14#24659]
## Description
Remermber that the statons chef was always popular for having CQC? 
Since the battle system is simple you can just give the person who reads CQC buffed punch damage and more some advanced disarm with some melee attacks blocking 
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/49343726/e26fad31-84d7-4ecb-bfcc-a079584f7c41)
With CQC you can also test some new mechanics like grab or toss

**Comment by Holinka4ever** [comment]
> Remermber that the statons chef was always popular for having CQC? 

This sentence is so wrong, i am gonna counter-argument that:

1)Chiefs are popular NOT because they having cqc, they werent actually popular, only thing they doing is making food.

2)Why you saying that cqc in chief, is the most valuable, overpowered and balanced thing ever, if in ss13 they cqc only for defending their kitchen from tiders, and it ONLY works in kitchen.

>Since the battle system is simple you can just give the person who reads CQC buffed punch damage and more some advanced disarm with some melee attacks blocking.

This is actually so simple, but actually to interesting to work with. I got same idea with carp scroll, but it giving you 100% reflect chance, but dis-allows using ranged weapon. But simplicity with cqc, can work with agents, i mean, what wrong would happen if you give cqc to agent?
