### ISSUE TITLE
Unable To Grab Grenades From Lockers

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#24691]
## Description

Some flashbangs/teargas grenades can't be picked up from the floor if they're coming from a locker. Once grabbed, the grenade gets sent back to where it was. Also heard it happened to another player when pulling one from a bag.

**Comment by MACMAN2003** [comment]
sometimes the fill on secbelts fails and the grenades inside of them appear in the right click context menu, i wonder if that's related to this.

i think it may be caused by the grenades somehow "not fitting" into the secbelt, because if you try to put a grenade into the secbelt it'll delay the insert for a second and have a pop up "that doesn't fit there!"

**Comment by Kadeo64** [comment]
> i think it may be caused by the grenades somehow "not fitting" into the secbelt, because if you try to put a grenade into the secbelt it'll delay the insert for a second and have a pop up "that doesn't fit there!"

this bug also happens with plant bags (aka security gets x-ray into plant bags to arrest botanists over gatfruits/deathnettle at max efficiency)
