### ISSUE TITLE
Lizards should have digitigrade legs as an option for markings

### ISSUE THREAD

**Issue by Hmeister-real** [space-wizards/space-station-14#25443]
## Description
It just looks cooler than normal legs, always preferred the digitigrade legs on Reptilians in ss13.

TG sprite example
![liz](https://github.com/space-wizards/space-station-14/assets/118129069/2f507648-bd6d-4a3d-aef8-75d1aab76b85)

**Additional context**
 They don't have to be functionally different, just look cooler like moth wings and arachnid appendages. Would probably need new sprites for certain clothes.

**Comment by Flareguy** [comment]
These need displacement maps to be added first since they have unique sprites + in my opinion they create weird design inconsistency in lizards. If we have digi legs, I feel like they need to be non-optional.

With that being said, an issue isn't a good place to discuss them, as they're definitely not something you can just add willy-nilly.
