### ISSUE TITLE
Massive Code Reorganization Needed

### ISSUE THREAD

**Issue by GraniteSidewalk** [space-wizards/space-station-14#2563]
We should organize classes more consistently. Right now it's all over the place.
I like:
- BodySystem:
        Prototypes:
        Components:
        Helpers:
- Atmos:
        Prototypes:
        Components:
        Helpers:

Or we can do what we're doing now but actually enforce it for more than the GameObjects folder:
- Prototypes:
       BodySystem:
       Atmos:
- Components:
       BodySystem:
       Atmos:
- Helpers:
       BodySystem:
       Atmos:

I like the first one better since it makes more logical sense - if you're working on X system you're not interested in every class that's a component, you're interested in everything related to X system.

**Comment by GlassEclipse** [comment]
Currently, Content.Server looks like this:
![Screenshot 2020-11-17 18 22 16](https://user-images.githubusercontent.com/32942106/99563032-73cf6a80-298e-11eb-8f25-26f538c3e5d5.png)
It's a pretty big mess. I say we enforce a standard by adding a handful of folders, most notably a modules folder where GAMEPLAY-RELATED code will be (could use a better name since that reminds me of byond).
In our new, better SS14, a modules folder would look like this:
![Screenshot 2020-11-18 11 14 50](https://user-images.githubusercontent.com/32942106/99563859-52bb4980-298f-11eb-9204-32f5720a165d.png)
There are many smaller systems that don't deserve a place near the big boy folders, so we can have a Misc. Content folder  (thinking of a good name). Also considered putting Modules and Misc. Content into a Gameplay folder
![Screenshot 2020-11-18 11 20 49](https://user-images.githubusercontent.com/32942106/99565524-5a7bed80-2991-11eb-9438-fcc5c1f29c64.png)
We can then place non-gameplay systems into a similar folder: Subsystems.
![Screenshot 2020-11-18 11 36 57](https://user-images.githubusercontent.com/32942106/99566358-67e5a780-2992-11eb-8f16-e7ac71970836.png)
With that the root folder will be pretty clean, save for some folders like Utility.

**Comment by PaulRitter** [comment]
To get the conversation roling, I very much like the layout he suggested in his comment.

I only have one wish. Please, PLEASE lets organize ui / bui in a seperatated folder.

**Comment by SweptWasTaken** [comment]
I've pinned this issue as it's come up again in conversation and I think it's best we take action to act on this while we can. Other maintainers should weigh in here.

![image](https://user-images.githubusercontent.com/49448379/120939767-1b34a480-c709-11eb-9487-7038d7534ebd.png)

**Comment by esguard** [comment]
I agree with this issue. Making sense of the codebase is quite difficult as a newcomer. 

Not only the code is split between Client/Shared/Server which is understandable but inside these three modules the folders and files are all over the place which makes it harder to find what you are looking for.

Regrouping all files related to one feature as suggested would make it easier to navigate the codebase.

**Comment by SweptWasTaken** [comment]
> 
> 
> I agree with this issue. Making sense of the codebase is quite difficult as a newcomer.
> 
> Not only the code is split between Client/Shared/Server which is understandable but inside these three modules the folders and files are all over the place which makes it harder to find what you are looking for.
> 
> Regrouping all files related to one feature as suggested would make it easier to navigate the codebase.

I think mirroring this across Prototypes/Components etc. would also be a big win for new contributors.

**Comment by mirrorcult** [comment]
here's my proposed organization

- all folders will go directly under Content.Server, Content.Client, etc.
- if there would only be one file in a folder, it doesn't need a folder (unless that file would go directly into the project's top directory, which is undesirable)
- folders are split into Components, EntitySystems, Visualizers, UI, Prototypes, Overlays, Commands, Helpers and Managers; again, these subfolders should only be created if they would have more than one file inside, otherwise you get folder bloat
- there should not be a 'misc' folder; misc folders are hell for organization and its completely arbitrary what goes inside them and what doesn't. you can put smaller game systems inside larger game systems if it makes sense, but don't just slap all the smaller game systems into a misc folder, its fine if they're in the same directory as the bigger stuff like atmos
- whatever directory structure is chosen should be mirrored to the Resources folder if possible

![image](https://user-images.githubusercontent.com/19853115/120940380-d6d9e200-c6d1-11eb-98dc-444bc90d9fb6.png)

in this example,
- atmos is a much larger game system, so it needs folders to hold all of these different types of classes. it has a subfolder for piping, which has its own set of components and entitysystems and such, since piping is pretty heavily related to atmos and it makes sense to relate it to atmos in the file structure
- explosion is a smaller game system; it needs a subfolder for components, but not for its entitysystem, helper, or command since there's only one of each
- buckle is a much smaller game system; it has only three files, with no subfolders

**Comment by ShadowCommander** [comment]
I agree with mirrorcult. Though, just put all the folders on the top level. No Modules or GameSystems folder.

We could also put engine required stuff like IgnoredComponents and EntryPoint into a Game folder or just leave them on the top.

**Comment by RemieRichards** [comment]
Agree with mirrorcult.

**Comment by SweptWasTaken** [comment]
Looks like most maintainers are agreed on mirrorcult's proposal as am I. I'll make a separate issue for outlining the code reorganization guidelines and for tracking.
