### ISSUE TITLE
Cryogenics access is only given to the captain

### ISSUE THREAD

**Issue by Varen** [space-wizards/space-station-14#25654]
## Description
Cryogenics access is only given to the captain. It should be given to all of command + security.

**Additional context**
#24096 says it added it but it seems like it didn't.

**Comment by deltanedas** [comment]
is cmo not meant to have it too

**Comment by Varen** [comment]
> is cmo not meant to have it too

Well, CMO is command too, so yes this issue includes that.

**Comment by Errant-4** [comment]
Security too. It's odd because at a glance, the prototypes indicate they should have it

cryopod.yml
![image](https://github.com/space-wizards/space-station-14/assets/35878406/ad53c1c3-0d15-4234-83d9-5d146d89195c)

security.yml
![image](https://github.com/space-wizards/space-station-14/assets/35878406/ac5d10b7-155a-4e64-b0d1-08c27cc8e76f)

**Comment by EmoGarbage404** [comment]
issue seems to be that the job prototypes don't have the access listed.

**Comment by lzk228** [comment]
imo it should be only at cap, cmo and hos (maybe warden) so it requires discussion
