### ISSUE TITLE
Jesse Rougeau / Jezithyr's Piracy Threat

### ISSUE THREAD

**Issue by Skyedra** [space-wizards/space-station-14#25937]
Please find attached an open letter detailing Jesse Rougeau / Jezithyr's actions on her anonymous alt account against me and my business.  In this activity, she invokes SS14/SSMV as cause for her threat, making this relevant to WizDen leadership.

https://spacestationmultiverse.com/2024/03/jesse-rougeau-jezithyr-game-cracking-threat-an-open-letter-to-ss14-leadership/

Obviously, it is quite a bad situation that one of WizDen's leadership staff, one who has been involved in dehubbing other downstreams, has herself been attacking a downstream fork developer's source of income not related to SS14 via an anonymous account on a deep web piracy site.  

Please take the time to read the letter as I hope WizDen will take steps to clarify that this behavior is not acceptable and not condoned by WizDen.

Thank you,
Skye

**Comment by metalgearsloth** [comment]
Try not harassing people on our repo thanks.

**Comment by DrSmugleaf** [comment]
Hello Skye,
Since you are continuing to spread misinformation and harass one of our contributors despite being told multiple times through both discord chat and written email to never contact this person again because you are causing them undue distress, you are repo-banned, and we have reported your account to GitHub for harassment.

I will remind you again that they do 
not wish to be contacted nor harassed by you because of your fragile ego being damaged. If you wish we can contact you more formally about the matter.

Furthermore this repository is for issues regarding development of SS14, not a public space for you to make a clown of yourself. If you have a staff complaint contact a PM or use the forums, and if you have a personal vendetta to enact I can gift you a clown nose to complete the rest of your behaviour.

I'm sure you have personal experience that such things can greatly affect someone's wellbeing. If it does not, I suggest you do something more productive with your time, as we are trying to develop a game here, not coax your narcissism.

Feel free to submit an appeal on the forums when you deem it necessary https://forum.spacestation14.io/

**Comment by Emisse** [comment]
Bold move doxxing someone on a public GitHub repository.
