### ISSUE TITLE
Thrown tiles deal damage twice

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#26022]
## Description
So I have thrown a steel tile and noticed mouse got isntantly crit... it should not to just 5 damage... but it took 10 instead and it was not because it bounced off wall or anything like that.

**Reproduction**
1. Grab a steel tile
2. Yeet it at something
3. Scan the damage and compare with damage listed on item

**Screenshots**
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/3c379408-8bd0-410b-b3a2-aea7b2d8b7a0)
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/07151fd9-7330-4e0b-8b99-89e360b65180)
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/66fb51eb-67eb-4d92-881a-72dcd992070e)

**Comment by wrexbe** [comment]
I threw some tiles at things, both locally, and on the server. Tried restarting the round. Not able to reproduce.

Can you still get this to happen?
Does this happen locally, or on a server?
Does this happen every single time, or only sometimes?

**Comment by thebadman4662** [comment]
Both locally and in game, It did not ever work against sec dog pet though, aside from that I tested it only on urists or other player sized entities, might not work with smaller ones.

**Comment by thebadman4662** [comment]
It seems damage is applied twice when something hits and then again when it slides on floor, you can get it reliably by aiming close to/at entity you want to doubledamage... I guess one could call it a feature rewarding good aim?

https://youtu.be/eIhrX1VWPtY

**Comment by wrexbe** [comment]
What I think is happening:
1. Player throws object
2. Object collides with, and then damages something
3. While the object is still moving, "ThrownItemSystem" StopThrow gets called, which causes RegenerateContacts to get called, which wipes out the StartTouching on the contact
4. Because StartTouching was wiped out by StopThrow, StartTouching happens again on the next contact update because the thrown item is still moving.

Different solutions depending on what is expected for the thrown item
1. Damages everthing it collides with until it runs out of momentum
2. Damages only the first thing it collides with, but keeps going until it runs out of momentum
3. Damages the first thing it collides with, and stops moving

**Comment by Plykiya** [comment]
Damage occurs upon entering another entity's fixture, and again on leaving another entity's fixture
StartCollideEvent is thrown twice without StopThrow ever occuring

**Comment by Plykiya** [comment]
The order of events when this occurs is
StartCollideEvent -> EndCollideEvent -> StartCollideEvent -> EndCollideEvent

**Comment by Plykiya** [comment]
https://github.com/user-attachments/assets/f010495d-032c-495d-9745-a425fb6d4302

Has nothing to do with item rotation or the item landing apparently

**Comment by JIPDawg** [comment]
I remember seeing a liltenhead video on this months ago. Not that it helps now. https://youtu.be/IK-KCDv4S8c?t=53

**Comment by Plykiya** [comment]
If they're off grid, it only hits once
YES, FINALLY, SOMETHING TO WORK WITH

**Comment by Plykiya** [comment]
IT ONLY APPLIES TO THE FIRST TARGET HIT
IT DOESN'T WORK IF THERE'S NO GRAVITY
IT USES LANDCOMPONENT()

WE'RE GETTING SO CLOSE

**Comment by Plykiya** [comment]
It's DamageOtherOnHitSystem
let's fucking go
