### ISSUE TITLE
Cargo telepad doesnt work anymore.

### ISSUE THREAD

**Issue by Adrian16199** [space-wizards/space-station-14#26181]
## Description

So basicly, using cargo telepad doesnt work due to the stuff being automaticly sended to the automated trading station, despite the fact that you link the telepad with the multitool.
**Reproduction**

-Get telepad
-Link it with multitool with the cargo request computer
-Buy somethin
-Goes to the automated trading station.
**Screenshots**

**Additional context**

Eh?

**Comment by metalgearsloth** [comment]
Okay so I've looked and it's going to require some work due to how trade is handling it and due to how device linking works.

- Assuming we even still use device linking then when the console approves a request it should immediately try and dump it into a new telepads queue. I think this is the SignalReceivedEvent.
- If there's nothing linked then dump it on trade station immediately.
- Gift event needs to just go through the same approval as everything else.
