### ISSUE TITLE
Beds have wierd buckling

### ISSUE THREAD

**Issue by Erisfiregamer1** [space-wizards/space-station-14#2631]
I go to sit in a bed. 
Most times, I get immediately unbuckled.
Otherwise, I sit next to the bed. What?

**Comment by metalgearsloth** [comment]
I think this loops back around to "contained entities really shouldn't have collision" (i.e. set CanCollide whenever something is inserted into a container and restore it when removed).

As the bed has collision as soon as you buckle to it it pushes you out via physics which makes the buckle break because of the MoveEvent.
