### ISSUE TITLE
Atmos can not recover from low pressure

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#26426]
## Description
Not exactly sure what's going on here but several rounds now pressure is lost in sections of the station and its not possible to refill rooms from the network.
Observations of issues happened about same time as this merge: #22521

**Reproduction**
- Loose some pressure in a room.
- make sure network is getting enough air
- check rooms that are not refilling.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/9f743ba0-814e-4b08-8372-90897df6abce)
![image](https://github.com/space-wizards/space-station-14/assets/47093363/f299d7c9-3a8c-467a-bb8d-9a0c71be5e31)

**Additional context**
When setting to just one output vent the vent really struggles to put out any real change in pressure.

**Comment by MjrLandWhale** [comment]
This might be worse than we think. From my testing I'm not seeing active/passive vents having ANY appreciable impact on the pressure in a previously spaced room. Nor does opening a canister have a lasting impact on the amount of gas in the room. 

The overlay is showing the gas being added to the tile in one tick, then it magically vanishes the next tick. I see it being added to the environment meaning the problem isn't with the vents or canisters. The temperature of any gas you try adding is handled properly as well. Venting a liquid oxygen canister will absolutely tank the temperature. Venting gas into the room can also change the overall ratio of gases while somehow not significantly impacting the pressure.

Hell, I've had a 300kpa Oxygen miner sitting in a room for the past 5 minutes... ZERO real change in pressure.

@ElectroJr since you made #22521 maybe you can help out?

**Comment by MjrLandWhale** [comment]
Workaround for this issue: have an admin run 'fixgridatmos' command.

**Comment by metalgearsloth** [comment]
> Workaround for this issue: have an admin run 'fixgridatmos' command.

Better for people to be giving info than just running bandaids and stopping comms.

**Comment by MjrLandWhale** [comment]
> Better for people to be giving info than just running bandaids and stopping comms.

Agreed, but also having the tools to mitigate a round-impacting bug where the station will slowly suffocate is equally important.

I ran into this bug in both of my most recent rounds. In both instances, I observed distro RAPIDLY lose pressure immediately after a spacing. The first instance was from a rod hitting the station. The second instance appears to have been from the HoS office getting bombed. My only ideas are that it has something to do with the new immutability functionality, or changes to how air-tightness is determined from the refactor..

**Comment by deltanedas** [comment]
> thought vents were supposed to automatically stop working when exposed to space to prevent distro from getting vented like this.

no its only when the pressure is low. without any bugs and healthy distro a small spacing will constantly suck distro out because the vent outdoes slow spaing

**Comment by ElectroJr** [comment]
Its possible that #26441 will fix this, though I don't know for sure given that I haven't really managed to reproduce it

**Comment by Titian3** [comment]
This is not longer a issue assuming Electro did enough atmos magic.
