### ISSUE TITLE
Xenoarch small-scale improvements desired before 3.0 rebuild

### ISSUE THREAD

**Issue by FairlySadPanda** [space-wizards/space-station-14#26480]
# ~~Artifacts gain value the more they are reseached~~

~~Add a small (+20% each time) multiplier to sale value for each node discovered during testing an artifact, to reflect that artifacts that sit on a pad are not money being made and used by the station.~~

# ~~Artifact Scanning Speed buffed to match pre-flatpack T2 upgraded parts speed~~

~~This was rarely used anyway but given the de-prioritization of upgrade parts this is just a gimme to reduce the boredom~~

# The node direction upgrade to pads is just built-in

It's a niche tech anyway and makes working on artifacts _slightly_ more interesting.

# ~~Nodes are changed to be two digit rather than five~~

~~There's simply not a potential of 10,000 nodes on an artifact, or ever scanning enough to need to use five digits. Everyone refers to nodes by their first two digits anyway. Don't make things look more complex for noobs.~~

**Comment by Tayrtahn** [comment]
I love and agree with all of these points.

With the direction upgrade, I would also like it if direction selection were possible from the verbs menu.

I also think it might be worth renaming the directions - I had no idea which way was "in" or "out" when I first used one, and I still have to think about it. Since the direction is in regards to node depth, maybe "deeper" and "shallower"?

**Comment by EmoGarbage404** [comment]
i think this is all done
