### ISSUE TITLE
Targeting

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#266]
## Target Doll
![image](https://tgstation13.org/wiki//images/f/ff/Hud-target.gif)
Since there was no good alternative suggested, we need to implement target doll for targeting specific limbs.

**Comment by PJB3005** [comment]
Pretty bad idea. The target doll adds no real gameplay value and massive complexity.

**Comment by PJB3005** [comment]
After some discussion in the /vg/ coder Discord, Reviire dropped the following idea:

Targeting uses high/medium/low, so while you can no longer target a specific hand, you can still generally target that region. Which side of the body the damage is done can be determined by some collision boxes for the weapon arcs or whatever.

This can really work since it's still very simple (only 3 states, not finicky at all) but still more than flexible enough and perhaps even has a bigger skill ceiling than SS13.

**Comment by acvzy** [comment]
Moved [here](https://hackmd.io/96HHKT-VQ2KO91c9i75V8A?both#Combat-dolls-2019-07-01-Reviire).
