### ISSUE TITLE
bat should require tool(s) to make

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#26679]
## Description
bat is arguable one of the best melee weapons in the entire game and all you need is 2 chairs and you can make it in a few seconds. its amazing for validhunting or as 0 tc guaranteed weapon/gibbing tool. i think it should take a saw to craft like validhunter sawnoff does since how are you going to glue and sand down a few planks of wood with your bare hands

**Comment by K-Dynamic** [comment]
You could make it an autolathe-only recipe (unless you want to lathe with your fingernails :trollface: )

**Comment by brainfood1183** [comment]
makes sense to be autolathe only.

**Comment by SlamBamActionman** [comment]
Not a huge fan of removing passenger combat options; the bat is strong, but it's also insta-Sec confiscate contraband, and it drops off in utility for actual combat roles due to it requiring two hands, being melee and dealing the most common damage type. Overall it doesn't deal that much more damage than a toolbox.

Gating it behind a handsaw will make it difficult to obtain if you're not medical personnel and trivial if you are, and gating it behind an autolathe means it's similarly locked behind science/cargo. If you want to make it more difficult to craft (something I could agree with) look at passenger-accessible options instead, like requiring basic tools or maints material (space glue?).

I'm honestly not concerned in the slightest that it's unrealistic to make it without proper tools; as far as suspension of disbelief for crafting in videogame goes, this one is pretty inoffensive.
