### ISSUE TITLE
need hyper exofab and circuit printer

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#27039]
## Description
they deserve it much more than autolathe given how much they use

**Comment by Boaz1111** [comment]
you should double check this with emo

**Comment by Boaz1111** [comment]
they said something about this

**Comment by deltanedas** [comment]
@EmoGarbage404 among

**Comment by deltanedas** [comment]
actually what if instead of having like 8 different hyperlathe prototypes it was just an upgrade that you can install into any lathe (but not oreprocs, it has industrial oreproc already) so if sci is extremely generous they can install it on a secfab

also solves the problem of having to figure out who to give the hand me down normal lathe board to

**Comment by ARMOKS** [comment]
This is what we used to have, it was much better IMO but was removed and replaced with hyper lathes. Most machines used to be upgradable.

**Comment by EmoGarbage404** [comment]
The general reasoning for why there isnt hyper circuit and hyper exofab is because i didnt want the upgrades to be only useful to sci. They're obviously quite helpful, but proto/auto layhes can be regularly distributed to basically anyone without any fuss and i felt that was a good thing to encourage.

As for making a generic upgrade, i don't love the idea of centralizing multiple potential techs into a single unlock. Theres also the issue of discoverability (is an ore processor a valid lathe for this? Is the biofab? Should they be?)

I dont think that the two upgrades proposed here add much interest besides letting sci scoot out some extra resources.

**Comment by deltanedas** [comment]
handing out protolathes allows random tiders to:
- make pkas
- make jaws
- make force projectors for pro shitter gameplay

these will probably result in a no fuck off from sci if they care, similar to circuit printer

a hyperlathe upgrade item having lathe in the name would automatically rule out oreproc and biofab, but make secfab and medfab obviously apply

**Comment by Golinth** [comment]
> I dont think that the two upgrades proposed here add much interest besides letting sci scoot out some extra resources.

Isnt that what basically all of the current upgrades are anyway?

**Comment by EmoGarbage404** [comment]
the circuit printer one exists and the exofab one isn't wanted
