### ISSUE TITLE
fire spread ignores mass

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#27052]
## Description
from liltenhead ops
it ignores mass so 20 stack urist gives 10 stacks to mouse and vice versa

it should scale based on mass of thing on fire / total mass, mouse has negligible stacks to urist and urist gives close to full stacks to mouse, like throwing paper at people

though this might create infinite fire glitch

**Comment by thebadman4662** [comment]
If bodies lose collision on death, they should lose it for spreading fire too, that would be simple fix I suppose, and if someone wanted to use live IIMs they should probably still take a single instance of that fire spread on throw, that way they take 10 and victim 5, you can splash bunch of water on self to minimize self-damage but not sure if it would douse mouse as well(because you spread anti-fire stacks???).

You could also make fire stacks decay even when not on fire. 1u of weldfuel is 0.05 firestack, so thats 2u decay per tick... Perhaps alcohol/weldfuel stacks should simply be gutted? They are already impractical outside of extreme cases like this, nobody would use them for flamethrower payload when phlog/clf/napalm are 4-8 times stronger.

**Comment by deltanedas** [comment]
throwing burning mice should still work, just like paper and not cfl3 grenades

**Comment by WarMechanic** [comment]
Suppose that a Urist had 1 mass and a Mouse had 0.1 mass:

Should a Urist attempt to split fire stacks with a Mouse, it should only lose a maximum of (20 * 0.1 = 2) stacks of fire. The Mouse's fire stacks should be clamped to 20.

On the contrary, if a Mouse were to split fire stacks with a Urist. The mouse's stacks should be split (20 / 2 = 10) while Urist gains the remainder, offset by mass (10 * 0.1 = 1 stack).

I'm not going to go too in-depth because it's too early in the morning for this. But as long as the relationship applies both ways there shouldn't be an infinite fire bug, atleast not for long.
