### ISSUE TITLE
Being "clumsy" allows you to phase through windoors

### ISSUE THREAD

**Issue by IamVelcroboy** [space-wizards/space-station-14#27245]
## Description
If you climb a table and fall during the process, it allows you to pass right through a windoor that would otherwise be blocking your access. 

**Reproduction**
See video

**Screenshots**
https://github.com/space-wizards/space-station-14/assets/107660393/85a5dfb6-eedc-4717-bfdc-f359e281ac53

**Additional context**
n/a

**Comment by beck-thompson** [comment]
Yeah I had this happen last night where a clown tripped and broke into chem

**Comment by Tayrtahn** [comment]
Ahh, I see what's going on. The DoAfters for both the climb and the bonk are running at the same time, so the player gets knocked down from bonking and then moved by the climbing action. Could be fixed by using DoAfterArgs to make them consider each other duplicate events. 

I should be able to fix this tomorrow.
