### ISSUE TITLE
Toilet "jump inside" is visible for mobs that are too big to fit

### ISSUE THREAD

**Issue by MasterFurret** [space-wizards/space-station-14#27316]
## Description
The jump inside verb works if you're a small mob. It should not show up if the mob is too big to fit.

The verb should not show up if the mob cannot fit.

**Reproduction**

- Right click toilet
- Click "Jump inside" verb

**Screenshots**
![bug](https://github.com/space-wizards/space-station-14/assets/62036996/09d7fd40-486c-4350-9f53-31d27d270632)

**Comment by 0x6273** [comment]
Pretty sure this is intended? It works for small mobs like mice, but humanoids are too big to fit.

There should probably be a popup or something that tells you that.

**Comment by UbaserB** [comment]
actually the more i read over it the more unsure i am this will just need replicating later

**Comment by 0x6273** [comment]
The jump inside verb works if you're a small mob (tested with mouse, I assume any mob with ItemComponent works). It works regardless of if it's hooked up to a disposals pipe, but flushing only works if it's hooked up. There's no actual bug here as far as I can tell, everything works as intended.

The problem is that the verb still shows if you're a mob that's too big to fit in the toilet, and there's no feedback when you use the verb. Either the verb should be hidden or disabled, or there should be a popup that says you're too big to fit.
