### ISSUE TITLE
Stun Prods Have a Deconstruction Option But Won't Say How

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#27330]
## Description

Make a stunprod, use it up, then try to break it back down, you can't actually disassemble stun prods it seems even though the right click UI says you can.

**Comment by lzk228** [comment]
same with artifacts

**Comment by Lukasz825700516** [comment]
https://github.com/space-wizards/space-station-14/blob/13c65378425e2d8254e8ed4e68061643b1245308/Content.Server/Construction/ConstructionSystem.Guided.cs#L40
with the default value of `DeconstructionNode` set to `start`, this statement never succeeds when node of construction graph has no defined edges.

Adding `    deconstructionTarget: null` (used in some gun recipies) to Resources/Prototypes/Entities/Objects/Weapons/Melee/stunprod.yml fixes this issue, but I believe the edges of node in construction graph should be checked in order to decide if given thingy should have deconstruct verb or not.
