### ISSUE TITLE
When PDA fails to load properly, you can see uplink options + play music

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#27376]
## Description

None of the buttons actually work and nothing loads, but it's quite funny to have the options visible even if your PDA is not intended to do either of those things

**Reproduction**

Haven't found any reproduction steps, but other people have reported the same issue

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
I need logs from anyone as I can't repro it.

**Comment by Plykiya** [comment]
Seems to happen on the first open of shift for some peeeople....

**Comment by Kayek14** [comment]
I dont know how it happens but sometimes when you open a PDA, it could be yours or someone else's, you see "open uplink" "close uplink" and some other options. When you click them nothing happens. You have to close the window and reopen it to get the PDA to fuction properly again.

It is a really big issue because ive seen security who encounter this issue when stripping a players PDA, see the uplink and kill them because they assume its a traitor, when its auctually a regular crewmember.

Ill try to repo this and send in a screenshot/video of it if i can get it working

**Comment by Kayek14** [comment]
had a round where this happend randomly as a security officer. Opened PDA and saw the screen and started recording. If you take out your ID or turn off/on the PDA it seems to fix the issue.


https://github.com/space-wizards/space-station-14/assets/106507028/d732bbb5-0cc5-43e5-abfd-9e02a082860d

Nothing happens when clicking on the uplink options.

**Comment by metalgearsloth** [comment]
Have any admins who've seen this VVd the state or anything else involved.
