### ISSUE TITLE
Rename IAttackBy/IAttackHand/IAfterAttack?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#274]
The naming dates back from SS13. I don't think it reflects the intended behavior well though.

**Comment by PKPenguin321** [comment]
What would be preferable renames? My thoughts are...
- `AttackBy` -> `AttackedBy` since it's run when something is "attacked by" something else
- `AttackHand` is a tricky one since it's literally just `AttackedBy` but for hands. `AttackedByHand`? Might be too verbose.
- `AfterAttack` -> `AfterAttacking` since it's run after attacking something with said item

**Comment by PJB3005** [comment]
My thoughts were more dropping the terminology "attack", especially since in SS14 we have a distinction between combat mode and not, and you can't attack outside combat mode (when these run).

**Comment by optimumtact** [comment]
InteractWith, InteractHand, PostInteract?

**Comment by PJB3005** [comment]
Keep in mind that we also have `IActivate` which is E-key bound and unrelated to hand contents.

**Comment by Qustinnus** [comment]
I want to pick this up, can I use oranges suggestion it's my preferred one.

**Comment by PJB3005** [comment]
Oranges suggestions are fine probably.
