### ISSUE TITLE
SpawnItemsOnUse component does not play any sounds

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#27616]
## Description
The component has a sound datafield for a sound to be played on use, which currently does not work.
Some of the affected entities are:
- MonkeyCubeWrapped
- FoodSnackChocolate
- FoodSnackNutribrick
- HypoDartBox

example:
![grafik](https://github.com/space-wizards/space-station-14/assets/161409025/54da561c-56bc-4c2f-84b3-9a40c925c7a3)

some items circumvent this bug by additionally using EmitSoundOnUse, which seems to work fine:

![grafik](https://github.com/space-wizards/space-station-14/assets/161409025/69b92675-4488-449b-9788-621cbbd08838)

**Reproduction**
- spawn a wrapped monkey cube
- unwrap it
- no sound is played

**Comment by Tayrtahn** [comment]
The issue here is that the sound is being played by the entity but the entity is promptly deleted, which cuts off the sound.

EmitSoundOnUse doesn't actually fix this - it appears to, since the client predicts playing the sound but doesn't predict deleting the entity, so it gets a chance to play locally before getting the message from the server to be deleted. This means that only the local player (the person using the item) hears the sound - it's still silent for other players.

**Comment by Tayrtahn** [comment]
If someone wants to throw together a quick followup PR that changes chopsticks (and anything else that uses the same workaround) back to using SpawnItemsOnUse to make sound when spawning items, that would be appreciated.

**Comment by slarticodefast** [comment]
Awesome, thanks for the quick fix. I'm just about to finish a PR that uses this. I can do the followup PR afterwards.

**Comment by slarticodefast** [comment]
Followup PR is done. I checked all uses of SpawnItemsOnUse and it looks like the chopsticks were the only one doing it that way.
