### ISSUE TITLE
Borgs being buggy

### ISSUE THREAD

**Issue by GalaxyCad** [space-wizards/space-station-14#27678]
## Description
So an ahelp came through about a borg not being able to see their laws and people not being able to take out their modules. this has been going on whenever an Ion storm hits the borg.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by lzk228** [comment]
any more info? because with only that its hard to understand what is problem with

**Comment by muburu** [comment]
this one is super weird, on one hand my laws have been hidden from me before (can't use the view laws action), but other times i've been able to see them, including when i'm emagged or when i get ion stormed. i don't know if it's even related at all to ion storms, whenever this happens it's always linked to the chassis, so if you get a new one the bug is removed..

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
from my understanding a restart does fix it as well

**Comment by VasilisThePikachu** [comment]
sounds a bit like #27439

tell me if you think so otherwise
