### ISSUE TITLE
Revolutionaries icons not showing as ghost

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#27768]
## Description
Sometimes the icons for Revs can sometimes not show leading to unneeded Ahelps and general confusion about why someone just died to a group of people

**Reproduction**
unsure how to reproduce this bug but it has been constant for at least a week from before this post was made

**Comment by QuietlyWhisper** [comment]
~~I think it was intentionally removed because it's hard to roleplay seeing your entire department is revs and then pretending you didnt see that~~

They should probably just be removed for non aghosts, I'd rather have the extra ahelps than chances for player issues, unless it's more preferable that players know which people are revs or not to report bad actors, despite the fact they might be revived with that information

**Comment by Plykiya** [comment]
it wasn't removed, I believe when I'm a ghost I only get updated on the rev icons once a headrev converts a new rev

**Comment by QuietlyWhisper** [comment]
> it wasn't removed, I believe when I'm a ghost I only get updated on the rev icons once a headrev converts a new rev
> 
> the feature still exists for ghosts with no restriction, it just loads in oddly

I amended my comment with this new information thanks

**Comment by beck-thompson** [comment]
It looks like it just doesn't work at all anymore, converting someone didn't update anything
