### ISSUE TITLE
traitor allegiance requests

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#27872]
## Description
recently #27855 got merged and i feel this is a good time to bring up the allegiances and bonds between the syndicate, as well as some RP suggestions featured in ss13. Here are a few:

- [ ] Make the various groups hate each other (e.g. You are the Donk Co. Traitor; kill all waffle corporation traitors)
- [ ] add the panel that shows when you become a syndicate in ss13, which includes code words and responses
- [ ] implement reputation (i actually dont know how this worked in ss13, i just watch mime man videos and some other creators)
- [ ] Have objectives based off of your chosen syndicate employer (e.g. You are the ARC traitor. (1: get a reputation of 598.8, die a glorious death, etc.,)
- [ ] Make it so that killing a fellow traitor is actually obvious, because just having "You need to kill ____" doesnt drive conflict
- [ ] Add an option in loadouts to select the organization who hired you (for fun reasons and some peoples lore stuff)

More TBA, add suggestions in replies

**Additional context**

**Comment by K-Dynamic** [comment]
Interesting except antags would rather work together unless there's enforcement or in-game mechanic for rewarding infighting

**Comment by moonheart08** [comment]
I think there's far better approaches than blatant "you must kill XYZ" for incentivizing distrust.
Here's an easy one, three new objectives:
- Meet with [name] and obtain their documents in exchange for yours.
- Meet with [name] and obtain their documents. (You do not have any.)
- Intercept documents from [name] and ensure they do not reach their destination.

One of these objectives spawns you with a syndicate secret documents item, the other needs you to procure the documents through some means (which they will not be happy about because you doing so will mean failure for them and whoever they're supposed to be trading with), and one requires you to ensure someone's documents do not leave the station to begin with.

Given you ensure there's always a pair of the first objective, targeting eachother (to ensure it's always possible) the other two will cause natural fighting and even distrust, because you could very well be lied to about them being your trade partner.

**Comment by Everturning** [comment]
> One of these objectives spawns you with a syndicate secret documents item, the other needs you to procure the documents through some means (which they will not be happy about because you doing so will mean failure for them and whoever they're supposed to be trading with), and one requires you to ensure someone's documents do not leave the station to begin with.

this IS interesting! a great way to influence those kinds of "everyone here lives, just work with me" negotiations. The part i kinda find a flaw in is that you SPAWN with the item. Does this imply roundstart traitors? Or is it like when you make someone a thief or something as an admin and they get the item in their backpack?

**Comment by moonheart08** [comment]
> > One of these objectives spawns you with a syndicate secret documents item, the other needs you to procure the documents through some means (which they will not be happy about because you doing so will mean failure for them and whoever they're supposed to be trading with), and one requires you to ensure someone's documents do not leave the station to begin with.
> 
> this IS interesting! a great way to influence those kinds of "everyone here lives, just work with me" negotiations. The part i kinda find a flaw in is that you SPAWN with the item. Does this imply roundstart traitors? Or is it like when you make someone a thief or something as an admin and they get the item in their backpack?

This objective would likely be built for round-start setup, given the need to have a *pair* of players for this to work.

**Comment by EmoGarbage404** [comment]
Don't put random ideaguysing in github. Make a forum thread or something if you judt want to throw out random ideas. Feature requests should be for actually agreed upon and actionable things that need to get done. Anything else should be a thread or a design doc.
