### ISSUE TITLE
Replays take a morbillion years to load on low memory systems

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#28052]
## Description

This seems to have began becoming an issue as of recently.

Users around 8gb to 16gb (with a well enough stressed system) seem to have issues loading replays. As they nearly hit their memory cap. Causing replays to take a while. There dont seem to be any erorrs. Just CRAWLING slow.

**Reproduction**

1. Get a vm (or spare computer) with low memory
2. Try to load a replay

**Additional context**

When i had tested loading a replay on a VM with 6gb of ram it took around 30 mins to load. Which sounds like a pretty average time around what people who experience this issue expirience.

**Comment by deltanedas** [comment]
a ~120mb replay took my entire systems memory and a lot of swap to load

**Comment by Kayek14** [comment]
Seems related to #27217 

Check to see how much memory it is using, on my rig it eats up everything i have remaining, 20gigs in some cases.

**Comment by moonheart08** [comment]
This is likely due to the fact replays load every entity to ever exist during a round back into memory. While many small entities will compress well, RAM isn't compressed.

**Comment by PJB3005** [comment]
This didn't use to be so severe or an issue tho.

**Comment by moonheart08** [comment]
> This didn't use to be so severe or an issue tho.

Well, hard to say for sure without someone doing a dotMemory trace.

**Comment by VasilisThePikachu** [comment]
Would dotmemory even work if the system does not have memory anymore? (which is what causes the bug here) idk how to use it much so maybe this is a feature

**Comment by PJB3005** [comment]
5 years of bikeshedding over whether somebody will actually run dotMemory instead of somebody just doing it

**Comment by tom-leys** [comment]
Seems the issue is similar to what moonheart08 says. The entire replay is loaded into ram from zlib compressed files, then processed into checkpoints. We might need to move to streaming the replay from disk, so only frames currently wanted are stored in memory. I'm suggesting that we only store a few instances of `GameState` (big class, one per frame) in memory at a time.

My approach would be 

- `LoadReplayAsync` needs to index the files and find all the frame start positions (byte offsets) in the files for later random access. 
- `ZStdDecompressStream` needs get/set stream position support. 
- `ReplayData` needs to cache only some of the frames, dynamically loading frames from filesystem on demand (right now plain lists are used). 
- Support for loading a single frame given info calculated by `LoadReplayAsync`, used by ReplayData

This would cap the memory usage at some small admin data, the checkpoints and cached frames. We could adjust how many frames are cached to reach the memory usage we think is sensible.

This way a user's computer would stream the file once to sanity check and set up frame index numbers. A second scan would create checkpoints (this would cache and evict every frame in the process). Then the user would just watch the replay and the ReplayData would get streamed from file.

**Comment by PJB3005** [comment]
That's all well and good but the checkpoints are the real killer. Even if you stream the actual regular playback data, the checkpoints will continue to take almost all the RAM (and, because you're evicting regular playback data, those objects can't even be shared).

**Comment by tom-leys** [comment]
> That's all well and good but the checkpoints are the real killer. Even if you stream the actual regular playback data, the checkpoints will continue to take almost all the RAM (and, because you're evicting regular playback data, those objects can't even be shared).

Sounds reasonable. The checkpoints DO each contain the entire game state at that time, so it's gonna be game size * num checkpoints. Your logic checks out.

So the solution to that is to scale the number of checkpoints based on system memory (perhaps aim for no more than 20% memory for checkpoints or similar). Could also do some of the dynamic checkpointing suggested by the source code - i.e when you are navigating forward through game state, create a checkpoint every X ticks, storing 3 and drop the oldest one. Then if you skip back a short distance you've got a dynamic checkpoint to build from.

**Comment by tom-leys** [comment]
So I went and bought new ram today because I only had 16GB up to now. So I can run a development environment while working on this problem :D

I loaded a small 60MB zipped replay from here - https://moon.spacestation14.com/replays/salamander/2024/05/17/salamander-2024_05_17-07_53-round_53835.zip

The memory usage from replay loading is about 7 GB. 
- 46% is checkpoints
- 18% is loaded deltas from the file

![image](https://github.com/space-wizards/space-station-14/assets/5285589/1dcdaff8-9e02-47a2-a9fa-0d8dc2702e1c)

**Comment by tom-leys** [comment]
These CVARs controlling checkpoint creation look promising. I might spend some time tuning these to reduce the number of checkpoints to less than loaded data as a starting point.

**Comment by tom-leys** [comment]
Okay, so it turns out that what I just posted above was wrong. It seems that creating checkpoints is churning through a ton of short-lived allocations and this creates deceiving statistics in the memory profiler. What I have here is a profile of loading that large replay. As the replay is loaded the memory increases to the right.

Baseline before loading the replay 1.65 GB::
![image](https://github.com/space-wizards/space-station-14/assets/5285589/fd3e16fc-59aa-4cd5-8010-6103e8b32c09)

After loading data before processing 4.24 GB
![image](https://github.com/space-wizards/space-station-14/assets/5285589/6b11f228-e408-4dec-b07d-52269d4bbffc)

After checkpoints 6.33GB
![image](https://github.com/space-wizards/space-station-14/assets/5285589/e50e82d3-fd56-4ecb-af0f-fc0a081fb64b)

I have re-tuned the checkpoint creation to make them less often and added stats about them. This reduces checkpoint usage by a lot
![image](https://github.com/space-wizards/space-station-14/assets/5285589/86ad4a3a-ec7d-495e-9498-79d0275250c5)

**Comment by metalgearsloth** [comment]
https://discord.com/channels/310555209753690112/770682801607278632/1240471389337550850

**Comment by tom-leys** [comment]
So it seems that checkpoints have been decreased from 1/3 of persistent memory on this snapshot to 1/6. The natural next step is smarter streaming of the replay data from the compressed file.

**Comment by tom-leys** [comment]
I have removed the short-lived allocations during checkpoint creation (so 8GB less memory thrashing). Streaming replays from disc is a much larger change so I probably shouldn't take that on and create a large PR.

**Comment by moonheart08** [comment]
Atomizing the perf improvements seems like a good idea, yes, especially as this impacts the ability for admins to load replays so making it a Little easier *right now* and then even better later is ideal vs making it much easier in two months with no meantime improvement.

**Comment by tom-leys** [comment]
I think the PRs that I have provided are good enough to resolve this issue. I expect that loading times will have improved dramatically for affected users and wouldn't be surprised if they are now sub 5 minutes.

**Comment by Flareguy** [comment]
Seems like this may have been fixed? Recently, I was able to load a replay almost as fast as the regular client, and I only have 6GB of memory.

**Comment by tom-leys** [comment]
> Seems like this may have been fixed? Recently, I was able to load a replay almost as fast as the regular client, and I only have 6GB of memory.

Horay! Good to hear. I guess my fixes have worked :D

**Comment by mirrorcult** [comment]
yeah from anecdotal reports i think this is done enough to be closed
