### ISSUE TITLE
Box Station Evac can spawn a SalvageHumanCorpse

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#28149]
## Description
Corpse on da evac shuttle, he so stinky.

**Reproduction**
Be on Box
Evac
Find corpse

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/130304754/c76b072d-5ade-4d87-a692-ccd2aa153164)

**Additional context**

**Comment by Lamrr** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/96937466/a166fa46-6a6d-49b7-b9a5-74d98c4d1cea)
It has a SalvageMaterialCrateSpawner mapped which can rarely spawn a corpse instead of a crate;
```
    - type: RandomSpawner
      rarePrototypes:
        - SalvageHumanCorpse
```
Personally I'd put this under funny but unintended feature (provided it doesn't happen to often)

**Comment by TurboTrackerss14** [comment]
Yeah its an almost non-issue, however the evac shuttle being filled (atleast in part) by a gigarotted miasma spewing corpse isn't a good look for NT 🫡 

Might be an idea to swap it out with another spawner.
