### ISSUE TITLE
The "fire fighting" door remote should not exist.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#28249]
## Description
There are a few majors issues with this item's existence:
- It exposes an **implementation detail** of firelocks, allowing them to be configured like standard doors when they don't support any of the other functionality of standard doors, like being hacked, that is required to support this.
  - And no, we shouldn't make them hackable, they don't have locks and are designed after real-world firelocks for a reason. They are deliberately "dumb" and aren't meant to ever pose as significant barriers to the player. Actual doors are for locking off areas, not firelocks, and using firelocks to lock down an area with bolts shouldn't be a thing.
  - What does a firelock being "emergency access" even **mean**, they don't have access controls and open on click.
  - No, you should not be able to electrify firelocks either and I hope I don't need to explain why.
- A remote for them is very low utility, there's little reason to be opening or closing them at a distance when either a) You have access to the fire alarm, and can pull it to control the doors or b) You are trying to use them as flow control, which is the purpose of standard doors, not firelocks. 

This feels like a case of "you *can* add this, but should you?" not being one of the questions asked when the item was introduced, without actually looking into the ramifications of the item's introduction.

**Comment by WarMechanic** [comment]
Emergency access of firelocks? Probably not needed. However, being able to bolt firelocks is very useful for flow control when you consider that firelock access extends to firelocks all over the station and not just in engineering. A common use case is when a firelocked hallway is more than 1 tile wide, it becomes wasteful to atmos holofan all 3 tiles when you can simply force a chokepoint.

I'd much rather see firelock signals / wires that pertain to only bolting or power (think command doors having more wires) rather than removing engineering utility.

**Comment by nikthechampiongr** [comment]
Related forum post: https://forum.spacestation14.com/t/firelock-hacking/8250/6

**Comment by moonheart08** [comment]
> Emergency access of firelocks? Probably not needed. However, being able to bolt firelocks is very useful for flow control when you consider that firelock access extends to firelocks all over the station and not just in engineering. A common use case is when a firelocked hallway is more than 1 tile wide, it becomes wasteful to atmos holofan all 3 tiles when you can simply force a chokepoint.
> 
> I'd much rather see firelock signals / wires that pertain to only bolting or power (think command doors having more wires) rather than removing engineering utility.

Bolt the doors the firelocks are over/near, instead. Hallway firelocks are always accompanied by actual doors.
Firelocks themselves really don't need bolts.

**Comment by deltanedas** [comment]
> and aren't meant to ever pose as significant barriers to the player.

they are very much so with these simple steps:
1. dont have power
2. have a firelock get forced close by spacing or something (which does not need power to happen)
3. if you didnt powergame crowbar as a medic or janitor you now die from spacing thanks to mr firelock

**Comment by nikthechampiongr** [comment]
> > and aren't meant to ever pose as significant barriers to the player.
> 
> they are very much so with these simple steps:
> 
>     1. dont have power
> 
>     2. have a firelock get forced close by spacing or something (which does not need power to happen)
> 
>     3. if you didnt powergame crowbar as a medic or janitor you now die from spacing thanks to mr firelock

That is no longer an issue. You can pry firelocks with your hands now.

**Comment by deltanedas** [comment]
oh good

still dont like firelocks theyre annoying anyway we have airlocks to block of rooms

**Comment by Errant-4** [comment]
Airlocks are for blocking off corridors, where you don't want a "door"

**Comment by dffdff2423** [comment]
I agree that bolting firelocks is a bit weird. However, I think atmos techs should have some kind of remote for bolting doors so random people don't space the hallway when you are doing minor renovations.

**Comment by Lamrr** [comment]
Can firelocks not be welded closed? Surely that would be a better solution if we need to 'lock them down' while fixing areas.

**Comment by UbaserB** [comment]
Personally I'm fine with the fire-fighting door remote

**Comment by Admiral-Obvious-001** [comment]
The one function I know emergency access on firelocks does is that it allows anyone to be treated as engineer access to the doors, where ordinarily the door would refuse to open in the event of a danger level closure.

Firelocks in my opinion should be able to be hacked for consistency but perhaps with fewer wires, just one wire for the bolt and maybe another one for access. They'll work on their own without power anyways, just they'll be less lethal because of the access lock for the same reason I described in the other paragraph.

**Comment by EtereohZ** [comment]
I think having the ability to bolt firelocks is very important as an atmos tech. It's very detrimental when random people start opening doors to the plasmaflooded room/frezon leak room and the temps get fucked everywhere.

I had a shift at Omega where an anom crit, releasing frezon at the big hall where most of service is. It was mostly contained until a borg opened the firelocks and people started coming in, then the central and eastern parts of the station were freezing and life became a pain.

If the remotes get removed I'd ask for another way to prevent people into getting into dangerous rooms, otherwise containing whatever gas is released will be much more difficult, and I really would prefer not having to take 20 minutes to restore the atmos of every room that becomes unlivable.

I'd say it's fine if the emergency access option gets removed, at least I've never used it.
