### ISSUE TITLE
Non-admins can use the "fuckrules" command

### ISSUE THREAD

**Issue by Hmeister-real** [space-wizards/space-station-14#28629]
## Description
I enjoy using this command, but it should probably be limited to just admins so shitters/raiders can't instantly ban-evade and rejoin.

**Reproduction**
 Join game, rules pop-up, open console, type "fuckrules", rules are skipped and you go straight to lobby

**Screenshots**

**Additional context**
Other non-wizden servers have this fixed.

**Comment by ElectroJr** [comment]
IMO, if people know enough about the game to know about the fuckrules command, and want to use it instead of reading the rules then they were probably never going to read them in the first place, so the permissions don't really matter. And the timer is there to try get people to read it, not to somehow block shitters/raiders. Making them stare at the button timer isn't going to reform them.

**Comment by ninruB** [comment]
Either way alt tabbing for a minute is still an option. `fuckrules` may rarely come in handy when Urist is joining a round during the pre-round screen but gets the occasional "hey re-read the rules" pop-up. In this edge-case using `fuckrules` may give them enough time to ready up instead of waiting through the full minute, the round starting, and having to latejoin/observe.

**Comment by PJB3005** [comment]
Fuck rules exists because, if I'm testing something on another system, I don't want to be forced to wait 60 seconds for the rules prompt. Locking it behind admins would defeat that purpose.

Electro already pointed out why it doesn't matter to anybody who isn't intent on following the rules anyways.
