### ISSUE TITLE
Jugs spawned with labels do not lose it when hand labeler is applied.

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#29126]
## Description
Spawn labels seem to not longer be treated as one but rather as part of their name, resulting in confusing medical jug labels that say they are for example both carbon and [insert custom label].

**Reproduction**
1. Apply label to jug that spawns with a label of their own
2. Examine

**Screenshots**
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/d87b2cb1-cf62-4fb4-a112-f4a2b01d7ff2)

**Comment by beck-thompson** [comment]
I think its from #27863 and is intended! I think jugs should probably have the (name of chemical) as a label instead of part of the name. That would fix this!

**Comment by deltanedas** [comment]
its not intended it just didnt change jugs/bottles/syringes to use it

**Comment by Tayrtahn** [comment]
With #27863, roundstart/spawned labels automatically get applied to the entity name on MapInit - I made sure to include that so that the bottles in the booze dispenser would show up properly.

Looks like the chemical jugs are both labeled at spawn AND have their label baked into their name, like @beck-thompson said. They can just use the label now and LabelSystem will make sure their name is correct.

I'll throw together a quick PR removing the baked-in labels from the names (and adding them as suffixes for mapping).
