### ISSUE TITLE
Pills have double labels

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#29462]
- Spawn in radiation kit medkit
- Notice how all the pills have double labels

![image](https://github.com/space-wizards/space-station-14/assets/45323883/ca910c2b-e306-474f-92fc-807dd06e8262)

**Comment by Tayrtahn** [comment]
This should be a very easy fix - all YAML, no C# required.

Just locate the pill entity prototypes and remove the label from their names. The label text should probably be added to the suffix field on the prototypes so they still have distinct names in the entity spawn panel for mappers/admins.

Like with chem jugs recently, the prototypes no longer need to have their labels baked into their names, since they'll automatically be applied when they spawn.
