### ISSUE TITLE
Airlocks close even while blocked by a player.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#295]
![image](https://user-images.githubusercontent.com/8107459/62834744-f710f500-bc50-11e9-8688-510762314a5a.png)

**Comment by CatTheSystem** [comment]
They closing because Collision mask of airlock is 1 and collision layer of player is 2 so when it comes to Collision detection code fails in the middle section (because 1&2 == 0): 
`public void DoCollisionTest(ICollidable collidable, Box2 colliderAABB, List<ICollidable> results)`
`if ((collidable.CollisionMask & body.CollisionLayer) == 0x0)
                {
                    continue;
                }`
