### ISSUE TITLE
Wielding is broken

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#29677]
1. Pull something
2. Wield popup says you wielded even though you didn't.

**Comment by AJCM-git** [comment]
uh so is the first step trying to pull something while you have a wieldable item inhand and not wielded?

**Comment by JIPDawg** [comment]
Below are other issues regarding wielding and recreation steps. 

#29521
#29589

**Comment by luizwritescode** [comment]
I think I have located where this bug is happening.

If you wield a gun while dragging with the other hand you end up calling SharedHandSystem.TryUseItemInHand() [in this file](https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/Hands/EntitySystems/SharedHandsSystem.cs)

It then calls SharedInteractionSystem.UseInHandInteraction() which then checks for blocking using ActionBlockerSystem.CanInteract() and CanUseHeldEntity() and in none of these action blockers a check for wieldable is made
