### ISSUE TITLE
Syndicats get one shot & explode instantly by mouse traps

### ISSUE THREAD

**Issue by MarzieK** [space-wizards/space-station-14#29782]
## Description
Syndicats will die/explode instantly after touching an activated mouse trap. 

**Additional context**
I have no god damn clue if this is intended or not, but it sure does make syndicats not worth the TC knowing this. All I have to do is throw a mouse trap and they're dead instead of wasting a few bullets.

**Comment by beck-thompson** [comment]
Yeah this is because the curve that controls the damage is super steep! The less you weigh the more damage the traps do. Cats only weigh like ~6 kelograms so the damage is very high.

I did some more testing and only two mousetraps is enough to gib a normal cat! I guess the fix is either to make cats weigh more or make the damage falloff steeper.

**Comment by Vermidia** [comment]
Syndicats are supposed to be immune to these step triggers, so when the fix gets it it'll be fixed

**Comment by slarticodefast** [comment]
Fixed by  #31011
