### ISSUE TITLE
TEG can function as an infinite power source

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#29893]
## Description

It stays at the value it was generating before being destroyed.

**Reproduction**

1. Get hit by a meteor
2. Lizard round #59181

**Screenshots**

<img width="351" alt="Screenshot 2024-07-10 170607" src="https://github.com/space-wizards/space-station-14/assets/58439124/e406b7f6-06ca-4f44-a03c-b3d3743ead02">
<img width="530" alt="Screenshot 2024-07-10 170628" src="https://github.com/space-wizards/space-station-14/assets/58439124/9bfc0a82-44cb-4dc0-b95e-14695702321b">

**Additional context**

**Comment by luizwritescode** [comment]
I was able to replicate the issue like this:
1. first you need to power the TEG, so pick any 2 canisters 
2. use viewvaribles to massively increase the temp inside one canister
3. now fill both loops and run the TEG
4. delete one of the circulators to simulate it being hit by a meteor
5. TEG's PowerSupplierComponent is now stuck in the last value it had

I digged some more and found that inside `TegSystem`:

the code that updates power is inside `GeneratorUpdate` 

```
 private void GeneratorUpdate(EntityUid uid, TegGeneratorComponent component, ref AtmosDeviceUpdateEvent args)
    {
        var tegGroup = GetNodeGroup(uid);
        if (tegGroup is not { IsFullyBuilt: true })
            return;
            
        var supplier = Comp<PowerSupplierComponent>(uid);
        var powerReceiver = Comp<ApcPowerReceiverComponent>(uid);
        if (!powerReceiver.Powered)
        {
            supplier.MaxSupply = 0;
            return;
        }
```

a bugged half built TEG will hit the first return (as it should on most cases) but then because of it never reaches the second check to update power

replacing the order of the checks seems to fix things on my end
