### ISSUE TITLE
Kobold and Monkey AIs are broken now

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#30051]
## Description

They spawn, walk one or two steps, and they no longer respond to anything else after that

Related? https://github.com/space-wizards/space-station-14/pull/30017

**Reproduction**

**Screenshots**

**Additional context**

**Comment by DieselMohawk** [comment]
Does this include them running to grab weapons?

**Comment by Plykiya** [comment]
> Does this include them running to grab weapons?

yes

**Comment by deltanedas** [comment]
think its the invalid-returning pr that caused it

it should cancel the task not return?

**Comment by luizwritescode** [comment]
not sure if it helps debugging but right now:

- any number of monkeys spawned with no weapon in-range will walk to a location and get perma stuck there
- if you try to drag one of these monkeys it will pathfind its way back to that same location no matter the distance
- if there is something they can grab in-range they will _sometimes_ grab it and if they do they behave normally

**Comment by osjarw** [comment]
Working on this right now, I believe I know whats going wrong.

**Comment by osjarw** [comment]
> think its the invalid-returning pr that caused it

This is most likely related to the Better Planning PR, since that PR causes the planner to switch to higher priority tasks, and picking up a weapon is currently a higher priority task than attacking hostiles.

> it should cancel the task not return?

I believe that cancelling a task is done by returning `HTNOperatorStatus.Failed`, which it now does upon getting an invalid Uid.
