### ISSUE TITLE
Brownies require whole eggs

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#30123]
## Description

Most recipes take the raw egg reagent, which allows you to either place it into a beaker or put the whole egg in the microwave. This seems to be unintended.

**Screenshots**

![image](https://github.com/user-attachments/assets/bf331029-dfb0-4a44-b57e-02fa7dce2bb8)

**Comment by Ian321** [comment]
There are in total seven recipes that use hole eggs instead of "raw egg". Most of them could use this change. I'm a bit unsure about the burgers and especially the boiled egg. (On the side, how does one boil an egg?)

![egg](https://github.com/user-attachments/assets/370dbf36-4123-432e-bce4-0602a7dc0a8a)

**Comment by Ian321** [comment]
I guess @arimah has to re-generate the cookbook now to update the recipes. And this can probably be closed.
