### ISSUE TITLE
Colorful costumes do not show appearance correctly when worn by female characters

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#30565]
## Description

Wearing a colorful costume will only show one of the colors the costume chooses for its item sprite, meaning you always have a solid color piece of clothing rather than anything with patterns

**Reproduction**

**Screenshots**

**Additional context**

**Comment by IProduceWidgets** [comment]
Since the others work, Im going to assume its a sprite / rsi / yml issue

**Comment by Plykiya** [comment]
> Since the others work, Im going to assume its a sprite / rsi / yml issue

Nah, literally all the colorful costumes don't work.

**Comment by Plykiya** [comment]
https://github.com/user-attachments/assets/854bffdd-47e4-455c-9c21-f167c3e836f3

**Comment by Plykiya** [comment]
I can confirm that both the sprite and the clothing component have all of the same matching layer states and layer colors

**Comment by Plykiya** [comment]
I can confirm that the colors and layers match up when being rendered in ClientClothingSystem.cs

**Comment by Plykiya** [comment]
Kind of concerning given that these are the only two files that could really be at fault...........

**Comment by Plykiya** [comment]
It works if your character is male, not female.

**Comment by Plykiya** [comment]
![image](https://github.com/user-attachments/assets/1b0bc1ee-67e2-4fb5-ad48-2c8c93051917)

**Comment by mio780308** [comment]
![螢幕擷取畫面 2024-09-30 223442](https://github.com/user-attachments/assets/e8f1de1f-674e-47ec-9e43-f9bf0e0b091d)

Hello! possible fix here:
https://github.com/space-wizards/space-station-14/commit/c2c90e1c579d8af79b0cab182315713cc836e9d6#diff-67e52eb70cba2e05c2651030961e5632194d4724e27d2bc48398f64ca82ecf9fR327

This bug seems to occur because when RenderEquipment inserts layers into SpriteComponent, the index doesn't move after adding displacement layers, causing torso layer to be pushed behind decor layer and torso layer is rendered after decor so female characters don't get the patterns.

**Comment by Plykiya** [comment]
fantastic
before & after the changes

![image](https://github.com/user-attachments/assets/76db23c5-2018-43d5-a7b7-9317fa4b4c72)

![image-1](https://github.com/user-attachments/assets/0c9994ec-fa16-41ab-b6b6-4850eb8fdd49)
