### ISSUE TITLE
Random story books write Nar'Sie as narsie, IE the ACTUAL on god most unimportant bug ever

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#30719]
## Description
Title, the "narsie cultist" random character is spelled as "narsie" as opposed to Nar'Sie, the (i think) correct spelling.

**Reproduction**
Step 1. Open random storybooks until you get one mentioning a "narsie" cultist.

**Screenshots**
![20240806172546_1](https://github.com/user-attachments/assets/2e74377c-3022-43bc-b56d-8b08b26590ca)

**Additional context**
i cant believe this, my immersion

**Comment by slarticodefast** [comment]
![grafik](https://github.com/user-attachments/assets/b97f6f2b-48b9-4cee-963d-863c8589f863)

The localization string for this is found in story-generation.ftl
Good first PR material, if someone wants to fix it

**Comment by bruhmogus** [comment]
while we're at it we might as well also capitalise ratvar to Ratvar

**Comment by LeoSantich** [comment]
Hello space-station-14, I'm a newb and I think I can handle this issue if possible.  I should be able to handle both the Nar'Sie and Ratvar fixes if I get the ok.

**Comment by Hrosts** [comment]
> Hello space-station-14, I'm a newb and I think I can handle this issue if possible. I should be able to handle both the Nar'Sie and Ratvar fixes if I get the ok.

You don't need the ok, just learn how to PR and do that. This issue is the "ok" you seek.

**Comment by LeoSantich** [comment]
Understood.  Appreciate your patience.  I'll go read your documentation again and submit a PR with a proposed fix, thank you.

**Comment by LeoSantich** [comment]
Is there any preference as to how it should look?  I saw some SS13 documentation that spells 'narsie' as 'Nar'Sie'.  At least one page in the SS14 wiki spells it as 'Nar'sie'.  There could be some intentional convention that I have yet to discover in the docs so far.  

Also, I'm loving this game.  New to it, but this is completely awesome.  I didn't even know about SS13.  The documentation here is so thorough it could train people literally in almost the complete software development cycle, if not 100%.  The odd passages with the strikethroughs are a bit intriguing, but otherwise spotless.  I have been really curious how I was going to go from having a little code knowledge to deep in some real game development, and this looks like the perfect way. 

I'm still fumbling around learning the game while reading the dev docs as well.  Everything build and ran as promised.  What's the quickest way to invoke the storybooks?  Do I need a particular space station or character?  This bug is a home run, not many bugs have the lines that require edited right in the bug.  Clearly, I'd like to be able to verify whatever change is decided per the input requested above.  Also, is it such that verifying the fix in one storybook should reasonably verify the change took throughout the game, or should I canvas the different space station types for the storybooks to check?  

Thanks again for your help, awesome game!

**Comment by slarticodefast** [comment]
I just had a look and every occurence I found in the code was Nar'Sie and I would suggest using that.
We don't really have official lore, so someone on the wiki might have used it differently.
The best way to test it would be to use the F5 spawn menu to spawn a lot of randomized books until you get one containing it I suppose.
If you need any help with the dev environment, feel free to ask us on our Discord channel, lot's of helpful people around there. Thats how I quickly learned coding for the game :)

**Comment by LeoSantich** [comment]
@slarticodefast,
Super thanks for such a speedy response.  Hope to get this in asap.  I'm on the discord site now, thanks.  The docs really helped me set up the dev environment and I think I'm good so far, but I'll definitely reach out if I run into issues.  Great support.
