### ISSUE TITLE
Save Item Location does not work

### ISSUE THREAD

**Issue by Doc-Michael** [space-wizards/space-station-14#30740]
## Description

The dearly beloved QoL feature of being able to save your items position in your bag/belt or any other storage container appears to be broken, no matter how many times you try to save an items position it just doesn't save it, i tried changing keybinds thinking its my issue but that didn't help.

**Reproduction**

-Spawn an empty bag
-Place a crowbar in the most bottom right corner of the storage UI
-Save the Crowbars position by pressing middle mouse button on it.
-Take the crowbar out
-Put the Crowbar back in the bag
-Wheep as the item position did not get saved

**Screenshots**

**Additional context**

**Comment by thebadman4662** [comment]
Its because it have broken hotkeys and hotkeys menu yet again, which is 2nd time now and 1st time was not fixed, yet issue where I reported it was closed?

Anyways, MMB and MMB+Shift which I both use for save item get somehow cursed and you need to reasign them + any other hotkey you use for same buttons as well(point at XXX in my case). If you remove inputs for hotkeys instead of reassigning them you will break the options and will have to reboot the game, which also will load last used hotkeys setting which are in their broken state.

Its possible full hotkey reset and/or deleting hotkeys file will fix it just like in last 5 cases and its just hotkey files somehow getting damaged with PRs and no longer being entirely compatible one way or another.

**Comment by deltanedas** [comment]
hotkeys breaking has to be rebound every time you start
 for me i had examine and rotate construct on mmb and it trolled me unless i rebound examine to mmb after starting game
