### ISSUE TITLE
player-panel-false isn't used as intended (probably)

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#31016]
i was doing translation for player panel, and after translating the file player-panel.ftl i tested it in-game and player-panel-false wasn't used and True/False text wasn't localed at all

**Comment by nikthechampiongr** [comment]
I forgor... The fix is easy, but my internet access is so horrible right now that attempting to clone the repo fails and I don't think I can get away with a web edit. If you want to fix it then you just need to go to PlayerPanel.xaml.cs and make it use the localization string depending on the Boolean for whitelisted instead of turning the boolean into a string. If nobody else does it I'll do it in a few days when I'll be back home.
