### ISSUE TITLE
Nukeops no longer give papers for the station's nuke. 

### ISSUE THREAD

**Issue by Golinth** [space-wizards/space-station-14#31216]
## Description

For a couple months now, the paper that spawns with nuke ops that describe the nuke ID and code to blow the nuke is consistently the nukie's nuke, the station nuke is never chosen. 

**Reproduction**

Force the gamerule to nuke ops, load into a map, and check the nukie paper, it will always be the codes for their nuke. 

**Additional context**

The random choice between the two codes was first added in https://github.com/space-wizards/space-station-14/pull/14025 and I do not see any PR that indicates that the removal was intended. If it was, please let me know. 

According to some, the behavior has been broken since at least April. Many months at the very least.

**Comment by beck-thompson** [comment]
OK did some testing this appears to be because the nukie station is spawned *before* the station is spawned. Because of this, the when the paper looks for all available nukes, it only sees the nukie one (Station hasn't spawned in yet) and uses it.

If you spawn the paper manually after the station is spawned it picks up both nukes.

I don't know what the fix should be but that's the issue!
