### ISSUE TITLE
All the AI issues I could find

### ISSUE THREAD

**Issue by ARMOKS** [space-wizards/space-station-14#31633]
1) Singulo / tesla can eat the AI's "eye" and brick the player
2) There is no way to save an unanchored AI.
3) AI functions without power
4) AI can see through depowered cameras
5) AI can sometimes see through cameras with cut wires
6) AI can see through cameras when the camera router is broken / unwrenched
7) AI cannot interact with high-security doors
8) AI can only be "killed" via minibombing its tile and unanchoring it
9) Doors need an AI control wire

That seems to be the extent of it. Looking into finding a few more

**Comment by DogZeroX** [comment]
4 is intentional with ss13 parity

**Comment by ARMOKS** [comment]
I feel like its gotta be a bug on 13 too, cause like. The cameras have no power

**Comment by lzk228** [comment]
#31543

**Comment by Moomoobeef** [comment]
I can see a case both ways for 4.

The AI seeing through de-powered cameras is unrealistic and makes it more of an omnipotence than an AI. **However** this means that during a power failure of the station (which happens a lot on LRP :P) the player can still play instead of just being *literally* in the dark.

On the other hand:
The AI not being able to see through powered cameras is more realistic, and it means that there's a consequence for power failure (so the AI might have an incentive to "protect" engi) and it allows antags to actually hide things from the AI by just removing power to a camera.

Note that the "realism" argument is pretty much meaningless since ss14 is more focused on being *fun* than *realistic*. So the main comparison here is:
- Omnipotent AI that can see in places that are destroyed as long as the camera hasn't been destroyed
OR
- Regular AI that has reason to be aware of and care about power failures on the station (which can also benefit the crew since power failures are generally a bad thing for crew)

**Comment by ThatOneGoblin25** [comment]
Would it be possible to those areas to stop updating so AI can "see" the rooms but receive no updates until power is restored?

**Comment by Moomoobeef** [comment]
> Would it be possible to those areas to stop updating so AI can "see" the rooms but receive no updates until power is restored?

probably could do that. That's a game design question and also might be challenging or impossible to feasibly implement but I dunno :shrug:

**Comment by Simyon264** [comment]
Maybe make cameras have an internal battery like emergency lights that lasts like 15 minutes
