### ISSUE TITLE
Stuff like reinforced crates and reinforced walls shouldn't take damage from fists

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3174]

**Comment by Peptide90** [comment]
Someone might want to test this but AME has metallic damage set and does not take damage from fists so I think this is fixed.

However, I still think sec crates are far too easy to break so cargo can buy a non lethal crate and armour and be into it in 30 seconds. Think locked crates need a damage threshold so that anything under a certain damage amount won't actually accumulate damage (things like crowbars do 3.5 damage so say less than 6 or something? So guns and explosives still break em.

**Comment by mirrorcult** [comment]
this particular issue is def fixed
