### ISSUE TITLE
we need logs for admins to properly administrate

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3178]

**Comment by Peptide90** [comment]
To add to this, it would be handy to have an ingame "events" log for admins to have access to (not sure how feasible it would be to have it open as a new window rather than in window so it could be on another screen).

Events for such a log could include:
- deaths (who died and last player to cause intentional damage)
- rapid pressure releases e.g. someone fully opening a gas canister or causing a large hull breach. (Either output the coordinates and local area name or if possible the person who interacted with the entity to cause it).
- excessive temperatures (gotta highlight then plasma fires so an admin can decide whether to intervene).
- explosions (just for the purpose of monitoring e.g. non antags making bombs).
- fuel tank explosions. (Keep an eye on assistants welder bombing).

**Comment by ElectroJr** [comment]
Should this be closed now?
