### ISSUE TITLE
PDA/medical scanner long range intel

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#31863]
## Description
Among new features on display is copy of character that is shown in the window. Should someone decide to keep it open they will know at all times when target is standing still, when taking damage, when gibbed and so on.

**Reproduction**
1. Take medical PDA/scanner.
2. Scan the captain.
3. You no longer need pinpointer as HoS. Sec comms being down do not matter like for implanter either.

**Comment by godisdeadLOL** [comment]
#31696
Both has something to do with `ItemToggleComponent`.

**Comment by themias** [comment]
I think the issue is that you only need to be in range to start scanning. Normally the DoAfter would handle being too far away, but the analyzer now updates with info after the DoAfter is complete.

There probably needs to be a range check every so often in an Update() or something.

**Comment by goet** [comment]
> ~I think the issue is that you only need to be in range to start scanning. Normally the DoAfter would handle being too far away, but the analyzer now updates with info after the DoAfter is complete.~
> 
> ~There probably needs to be a range check every so often in an Update() or something.~
> 
> Nevermind, looks like this was fixed already.

Just for clarity's sake: HealthAnalyzer already had logic to turn off the scan if the target went to far away, eg: damage values would stop updating. The issue is with SpriteView, which just takes a reference of the target's SpriteComponent, so any value changes on the component would show up on the analyzer regardless of what the analyzer wanted. 

I went with the simplest solution for this, but if you are interested, a way to properly clone SpriteComponent to "freeze the view" would be kinda nice. It seemed like a ton of work to me, and I honestly don't know if it would have any applicability outside of this.
