### ISSUE TITLE
Figuring out whats wrong with foam issue

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#3199]
We have many reports of it crashing/slowing down the server, if anybody has any idea why this happens comment below and i will change the issue title and description.

**Comment by Peptide90** [comment]
Could this be due to the objects under the foam interacting with it constantly causing the server performance to tank? Will need tested.

For now maybe nerf the chem dispenser or disable the metal foam grenade since it's not particularly needed at the moment? Can work on porting inflatable barriers as a substitute.
