### ISSUE TITLE
Ripley mechs don't lose energy on use

### ISSUE THREAD

**Issue by K-Dynamic** [space-wizards/space-station-14#32318]
## Description

Ripleys used to lose energy on use when using modules, which is no longer the case.

This may affect other mechs.

I am unable to recall if power decreased on movement.

**Reproduction**

1. Pilot a mech with a module (i.e. Ripley mech with clamp)
2. Examine mech stats while using module (i.e. pick up and drop crate with clamp)
3. Notice unchanged power level (remains 100%)

**Comment by JIPDawg** [comment]
are these the round start ripley's or one that Science made.

**Comment by JIPDawg** [comment]
So I think I found the issue, but I'm not sure if it's intentional or not. Looks like the round start Ripleys have the Small hydraulic clamp mapped in, and for whatever reason this clamp actually recharges the ripley? When using the large clamp it loses about 2% power per use and then using the Small one recharges 2%? I don't think it's intentional, but not entirely sure.
