### ISSUE TITLE
botany on maps needs hydro doors

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#32599]
recently hydro doors were added
so someone should add them to maps

**Comment by BackeTako** [comment]
The way I added the doors mean that if mappers have used the correct hydro door in mapping it will already be added.

Since I just changed it so the hydro doors use their own sprite, instead of inheariting the default door sprites.

Packed for example:
![example_hydro_door](https://github.com/user-attachments/assets/74c5e8be-7d92-49d1-ba8c-5aa8f9db1969)

**Comment by Everturning** [comment]
ah alr I'll close then
