### ISSUE TITLE
Pipe unanchoring is exploitable

### ISSUE THREAD

**Issue by MissKay1994** [space-wizards/space-station-14#32632]
## Description
All pipes eternally hold gases even when you unanchor them. The pipe will just eternally be filled with gases until you deconstruct it and build a new one. Pipes will hold the gas indefinitely and can be anchored and unanchored to cause mass destruction

**Reproduction**
Build a set of pipes, fill them with a pump, and unanchor one. There will still be gas in the unanchored pipe, which you can then release by anchoring it elsewhere and unanchoring it again

**Screenshots**
This is after I anchored and unanchored it a few times but the initial pressure was 1400kpa
![20241003205549_1](https://github.com/user-attachments/assets/ee78463d-14a7-4cc8-8fb3-fd1d8d7cdd01)

**Comment by Golinth** [comment]
> Connectors eternally hold gases even when you unanchor them.

I think this is true of all pipes

**Comment by MissKay1994** [comment]
An admin has said that this is definitely a bug and not supposed to happen

**Comment by wraith811** [comment]
yeah this is a mildly annoying part of artifact science because with most setups theres no good way to purge any excess pressure in the connector so you just kinda have to deal with mixing gasses in your cannisters and losing some of it to the connector which isnt a huge deal for most rounds but can lead to some minor accidents like a RA accidently dioxide poisoning themselves when they fill up their o2 can from the artifact room "oxygen can"

**Comment by Golinth** [comment]
It’s definitely still a bug, I just meant to say that it’s not unique to connectors
