### ISSUE TITLE
AI can be targeted by artifact teleporation

### ISSUE THREAD

**Issue by Scribbles0** [space-wizards/space-station-14#32644]
## Description

title

https://github.com/user-attachments/assets/bdb7251d-0ead-4a32-b5d0-764931f9fb36

**Comment by Scribbles0** [comment]
reported in #31543, close for dupe maybe?

**Comment by slarticodefast** [comment]
We can keep it open as its own issue. 
I assume the problem lies in PortalArtifactSystem.cs
It looks for any entities with the MindContainerComponent and selects a random one from that list.
Then a portal is spawned and the position is manually swapped with the artifact.
Instead of MindContainerComponent the search should be for MobStateComponent (similar to the bluespace anomaly).
Additionally there should be a check to filter out any entity inside a container.
