### ISSUE TITLE
Unable to eject Borg brains or modules

### ISSUE THREAD

**Issue by SkippyMcSkips** [space-wizards/space-station-14#32987]
## Description
When you attempt to eject a brain or module from a Borg, nothing happens. It gives no errors or indication anything has tried to happen.

**Reproduction**
Unlock and open a Borg
Attempt to eject anything from them

**Comment by deltanedas** [comment]
it does work its just all borg ui updated is delayed by 1 action so if you remove 2 modules you only see 1 removed, etc

**Comment by SkippyMcSkips** [comment]
No, it doesn’t work. The issue I’m reporting is that it’s completely impossible to remove a Borgs brain and modules from its body.

If me or anyone else I ask try, nothing happens.

**Comment by JIPDawg** [comment]
Any other repro steps or possibly something else that happened? I'm not able to reproduce. Can take out brains / modules with no issue.

**Comment by SkippyMcSkips** [comment]
It's possible it's something specific to the downstream server I usually play on. Let me raise the issue with them and see if they can reproduce.

**Comment by BombasterDS** [comment]
> it does work its just all borg ui updated is delayed by 1 action so if you remove 2 modules you only see 1 removed, etc

It's happening because of borgs preferable names. As i can understand, when you make preferable name from borg it'll ignore NameIdentifier (For example, when you spawn a borg with f5 menu - you'll get Toaster (Si-6575), but when you spawn roundstart with preferable name - you'll be just RobotName without identifier. But borg UI still checks name this identifier that leads to negative number on substract) 

BorgMenu.xaml, Line 57 and 58

**Comment by SkippyMcSkips** [comment]
Resolved by https://github.com/Goob-Station/Goob-Station/pull/867
