### ISSUE TITLE
Wielding should be automatic

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#33537]
## Description
Wielding items, such as guns, should automatically occur when the player has two hands free. More or less, wielding should be turned in to "the state an item goes in to when both of your hands are free."

With all of the wielding QOL changes (you are no longer blocked by wielding something in most instances,) there's basically no reason for this to not be a feature now. What I said above about wielding being a default state is basically already true, except that you have to push z to initiate it. It's a fairly unnecessary and obnoxious piece of hand management that adds nothing to the game.
In addition to this, wielding prevents other interactions that use Z from being on the same item. This means that gun bolting cannot be added to stuff like the Kammerer or bolt-actions until this is fixed.

**Comment by lzk228** [comment]
ummm no?
we have a good micro control and free to use it, that's what i like it in this game
and why the game should prevent me to hold a gun in one hand or even shoot it holding in one hand if i want it

**Comment by MissKay1994** [comment]
Counterpoint. How are you going to reload if it forces you to use both hands to hold a gun. This idea is awful in terms of not thinking about the gameplay aspects where you NEED a free hand to do things. This is _**ESPECIALLY IMPORTANT**_ if you are a secoff who just gunned a person down and now are cuffing them to drag them. This would force the secoff to potentially have to leave the gun on the floor just to drag the cuffed person. Also consider, that if you are in a hardsuit in a spaced area, you can't use a back slot for your gun to have free hands, and may not have a backpack or even duffle to carry this gun you now are forced to fill both hands with on top of having to put it on the floor the reload it, which may as well be surrendering so the other person with a Viper, WT, laser pistol, and so forth can execute you without any resistance.

**Comment by Pumkin69** [comment]
this doesnt make any sense

**Comment by Djungelskog2** [comment]
uh... is this bait?

**Comment by Errant-4** [comment]
I do agree that it could be a good change, and would free up some of the "input-space" which is currently kind of cluttered. But this would succeed or break on exactly how it is implemented. I do think it's an idea worth playing around with

One option would be that the item simply auto-wields when equipped and the other hand is free, but you could still unequip the way you do now, by switching hands. This would allow us to remove wielding from the Use key
And if you need to wield it again, uh I guess you would then have to put it in your other hand to "equip it again". That is less convenient than currently. Not ideal, especially since you would need to do that after every reload. Hmm

**Comment by Flareguy** [comment]
> Counterpoint. How are you going to reload if it forces you to use both hands to hold a gun. This idea is awful in terms of not thinking about the gameplay aspects where you NEED a free hand to do things. This is _**ESPECIALLY IMPORTANT**_ if you are a secoff who just gunned a person down and now are cuffing them to drag them. This would force the secoff to potentially have to leave the gun on the floor just to drag the cuffed person. Also consider, that if you are in a hardsuit in a spaced area, you can't use a back slot for your gun to have free hands, and may not have a backpack or even duffle to carry this gun you now are forced to fill both hands with on top of having to put it on the floor the reload it, which may as well be surrendering so the other person with a Viper, WT, laser pistol, and so forth can execute you without any resistance.

The point I was trying to make is that wielding doesn't have any limitations on what you can do, to my knowledge. Your second hand is basically "free". Are there even any situations where this isn't the case?

**Comment by SlamBamActionman** [comment]
I don't think there is any state where you are better off not wielding the weapon if you have a free hand.

Imagine the UI flow like this:

You have two free hands and pick up a gun that has the wieldable property with your active hand. This autowields it. If you swap active hands (i.e. you swap to the hand that didn't pick up the gun), it unwields it. If you swap active hand back to the one holding the gun, it wields it again.

You have one free hand (because you are holding a mag, a shield, whatever). You pick up a gun that has the wieldable property with your active hand. Since your other hand is occupied, it will not be wielded. If you swap active hand back and forth it will not wield the gun, until the hand not holding the gun becomes empty *and* the active hand is the one holding the gun.

There is no instance in the game where you will be utilizing your free hand while it is not also your active hand. Reloading or cuffing are actions that make you switch active hand to your offhand, at which point the gun would auto-unwield.

There are three issues I can see arise from the implementation though.

1. Dragging can be initiated regardless of your hand, and defaults to your offhand if your active is holding something. 
2. The crusher item has some wonky stuff with whether you are wielding it or not. Though personally I feel it needs to be remade to be nicer to use either way.
3. We are assuming wielding will always be an upgrade to the item's performance and functionality, which is currently the case, but might not be in the future.

1 can be solved by just unwielding if you start a drag action (and immediately wielding again if you stop dragging and still have the gunhand as your active hand), or requiring you to use an empty hand to initiate a drag.

**Comment by SlamBamActionman** [comment]
There will also be a bit of a weird thing I guess where if you, say, pick up a baseball bat from the ground you will immediately wield it, which can be seen as a more hostile position to be in and might not reflect your intentions.

**Comment by FairlySadPanda** [comment]
Just wanted to stash a thought from discussion on contributors here: this ends up feeling like there's a "can use this item properly" and "can't" state. This is the same as deflection, where your effectiveness drops in some circumstances.

**Comment by keronshb** [comment]
No this is not desired.
