### ISSUE TITLE
"Vox Boxes" should be removed from all maps immediately

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#33720]
These have outright racist connotations. If I had known that some maps are as bad as they are I would have flipped shit about this months ago.

Do not peanut post on this issue, I am going to be zero tolerance on any punishments handed out from this fiasco.

Edit: people are finding this thread without being aware of the surrounding context. See here: https://discord.com/channels/310555209753690112/900426319433728030/1313935602252513312

**Comment by Nox38** [comment]
where are voxes supposed to eat?

**Comment by PJB3005** [comment]
> where are voxes supposed to eat?

We are discussing possible alternative manners to deal with this.

**Comment by Ghost-Prince** [comment]
Do you mean that the nitrogen only rooms, to be moved to more communal rooms (nearer to kitchens and bars) so that they can have their mask's down an eat without getting poisoned by oxygen in regular atmosphere?

**Comment by PJB3005** [comment]
No, remove them entirely

> Do you mean that the nitrogen only rooms, to be moved to more communal rooms (nearer to kitchens and bars) so that they can have their mask's down an eat without getting poisoned by oxygen in regular atmosphere?

**Comment by Warpzoned** [comment]
> No, remove them entirely.

Both conceptually and thematically? Even though I partially understand a re-branding due to their less-than-adequate connotations, why remove N2 rooms as a whole? They're a great accessibility feature instead of having to micro-manage your tank and food.

**Comment by PJB3005** [comment]
> > No, remove them entirely.
> 
> Both conceptually and thematically? Even though I partially understand a re-branding due to their less-than-adequate connotations, why remove N2 rooms as a whole? They're a great accessibility feature instead of having to micro-manage your tank and food.

Yes. Solutions that avoid the micro-management you described are better.

**Comment by Djungelskog2** [comment]
Not in the current conversation occuring on discord but *please* go down the route of having box masks let people eat through them. Clown and mime vox already have this ability and it gives vox an extremely niche "upside" I'm their custom gear. It would also just be way simpler and more fun for the players.

**Comment by Golinth** [comment]
I'm going to post what I already have in the discord, as it was largely ignored. 

If N2 boxes are in poor locations, why not standardize n2 boxes to be forced in the bar? Why are we comparing something akin to wheelchair accessible seating to straight up segregation and racism? Understandably, the new Core and current Cog boxes are in terrible locations and should be changed ASAP, but change the offenders and make them readily accessible. The original Core one was nearly perfect. Keep the box where it was, move the bar to where the theatre is now, and you have a reasonable and accessible way for voxes to interact and enjoy the bar, while also enjoying the freedom of removing their mask. Don't relegate the box into some corner of the bar either. Make it a core feature, make equivalent to a normal table. 

Removing the uniqueness of a species that people are making conscious choices to play. (When I play vox, its because I don't want to have the same experience as playing a lizard). By removing that you are enforcing species as an aesthetic choice, not a mechanical one. If this is something we are okay with, begin to allow purely aesthetic species (such as vulp or felinds).

**Comment by PJB3005** [comment]
@Golinth I'm sorry, but this topic is not up for debate. I am making this call straight as a project lead.

**Comment by DEATHB4DEFEAT** [comment]
> These have outright racist connotations

I've only just heard of this, but isn't this the *opposite* of ~~"racist"~~ specist? You're providing a safe space for an alien specie instead of forcing them to suffocate or make their own space. What's caused your sudden, seemingly irrevocable dislike for them after existing for over 2 months?

**Comment by Kadeo64** [comment]
> But does this extend to nitrogen rooms in medbay? In the context of treating patients, medbay vox boxes have connotations for accessibility & disability services rather than racial segregation. So I wouldn't mind seeing medical nitrogen rooms on high pop stations, where there's enough Vox players to justify the map space it'd take up.

IMO, a thing like this should instead be made into something modular. Instead of having a nitrogen room in medical, there should be an artifact-chamber like room that can be spaced and re-pressurized into pure nitrogen/plasma(plasmamen)/etc. Then it becomes a general treatment room and not a vox thing.

**Comment by metalgearsloth** [comment]
> > These have outright racist connotations
> 
> I've only just heard of this, but isn't this the _opposite_ of ~"racist"~ specist?

![image](https://github.com/user-attachments/assets/a68116b9-a6db-4913-b2a2-a8ad5f304950)

**Comment by DEATHB4DEFEAT** [comment]
> [image](https://private-user-images.githubusercontent.com/31366439/392602245-a68116b9-a6db-4913-b2a2-a8ad5f304950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTYxNjYsIm5iZiI6MTczMzM1NTg2NiwicGF0aCI6Ii8zMTM2NjQzOS8zOTI2MDIyNDUtYTY4MTE2YjktYTZkYi00OTEzLWIyYTItYThhZDVmMzA0OTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIzNDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3Mjk2NmQ5OWFlNjVlMzgyOTYwNTU0OTUxNDUwOWIwYTkyYTFmNTU3ZGZiYmU0MmYxZTVkY2U1ZDFkMmU3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ulnDC0-juL0HbhVwmsrZWDakn31X7L931ASVz-8jgvg)

Ah, isn't that just one map though? The ones I saw seemed fine, and moving/improving that one should be a simple fix.

**Comment by metalgearsloth** [comment]
I saw 3 posted and they were all equally slums.

**Comment by Errant-4** [comment]
I think that was the last one
