### ISSUE TITLE
None of the player options of the ghost warp menu work

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3393]
somewhat relevant for adminning

**Comment by Macoron** [comment]
Can't reproduce it locally. A few notes though:

1. It teleports to players attached entity, not players last body. Usually this is players character, but it can also be a ghost or ghost role.
2. When admin tries teleport to themselves, it won't do anything.  Because it will teleport admins ghost to last admins ghost position.

**Comment by Macoron** [comment]
So after some additional research, I reproduced this behavior. The problem is with current pvs implementation. Though server changes ghost position, client doesn't receive it first time. You need to press warp button twice or move your character. Disabling PVS fix it.

I have no idea how to fix tbh.

**Comment by gbasood** [comment]
Currently, the player list for ghost warp doesn't seem to update as, for example, new players join, and warping to players doesn't work at all, with no errors logged on the server.

**Comment by metalgearsloth** [comment]
Pretty sure this was fixed
