### ISSUE TITLE
CE hardsuit should be nerfed

### ISSUE THREAD

**Issue by kosticia** [space-wizards/space-station-14#34074]
Hardsuit of CE is so much OP, and even better than hardsuit of RD, because it's have full radiation resist and small lowering of moving

**Comment by Cojoke-dot** [comment]
I mean, full rad resist is really only useful for the singulo, I don't see how that makes it op. RD's suit can be put into a duffle bag to negate its movement debuff, has the same speed debuff as the CE's hardsuit, has better heat + blunt + caustic protection. and only a 10% radiation damage deficit.

**Comment by ArtisticRoomba** [comment]
I don't see how RD's hardsuit is worse than CE's.

CE's hardsuit isn't really OP in my opinion. Of course, as an engineering main I am as biased as one could ever be, but I can tell you that if someone wants to kill me they can just shoot me. Running is futile.

Cojoke-dot already said what I was going to say. However, I will add that the RD's suit is literally bomb-proof. 90% explosion resist is no joke.

They're department head hardsuits. One of a kind. They're important for a reason.

**Comment by BramvanZijp** [comment]
> I don't see how RD's hardsuit is worse than CE's.
> 
> CE's hardsuit isn't really OP in my opinion. Of course, as an engineering main I am as biased as one could ever be, but I can tell you that if someone wants to kill me they can just shoot me. Running is futile.
> 
> Cojoke-dot already said what I was going to say. However, I will add that the RD's suit is literally bomb-proof. 90% explosion resist is no joke.
> 
> They're department head hardsuits. One of a kind. They're important for a reason.

Cries in CMO Hardsuit

**Comment by SlamBamActionman** [comment]
The CE's hardsuit is specialized to deal with damage types that would be relevant to the work, and is suitably different in other resistances to make up for this specialization. Radiation resistance is of particular importance since it makes it possible for CE to freely work in the viscinity of the singularity, something even normal Engineers have to pay attention to. 

And since this issue draws comparison to RD's suit; RD has 20% better blunt resistance, 10% better explosion resistance, 10% heat resistance at the cost of 10% worse piercing resistance and no fire protection. CE is also expected to be wearing his suit a lot more compared to RD, hence the *5%* movement increase (20% instead of 25%), and also why RD can *actually store his suit in a duffelbag* when not in use. 

Is it strong? Yes, all head hardsuits are. And unlike RD, who has an easy ability to get their hands on new and powerful Science equipment over time, CE is likely going to be stuck with only his suit and magboots as significant upgrades. There is no need or desire to nerf CE's hardsuit at this time.

**Comment by deltanedas** [comment]
> all head hardsuits are [op]

cmo :trollface:
