### ISSUE TITLE
Controlling another player's mob or character causes them to see only space.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3731]
## Description

This is true on both debug and live servers, tested by K33N with me. When you control their mob, they'll be kicked into seeing blank space, and then they will have to reconnect or respawn in order to come back.

**Comment by ShadowCommander** [comment]
Tested a bit. Both the player trying to control the mob and the previous controller see space. The new controller can still move the mob, but the view doesn't update due to `Owner.Transform.MapPosition` being `NaN, NaN`.

The previous controller gets put in space because a ghost doesn't spawn for them, which means EyeManager uses `_defaultEye`.

**Comment by Acruid** [comment]
Multiple clients controlling a single entity has never been supported by the engine. Multiple things would break like PVS, Eye, and Input. Mind system probably can't handle having two minds in one entity. Historically the first player would be ejected back to the lobby, and I think now the first player is supposed to be ejected into a ghost, which sounds like it is broken. Open a feature request in the Engine repo if you think we *really* need this, because it will be a lot of work implementing properly.
