### ISSUE TITLE
Criticisms of Fluent and the entire localization system

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3811]
## Description

Let it be known that these are from the perspective of the man who has contributed the most yaml to the project so I won't really be talking about it's usage in C# code here, although @DrSmugleaf has voiced similar concerns.

I also would like to state that this system being released without any sort of linter or tooling is incredibly frustrating.

Bad
- I'm not typing out comp-body-lizard-bottom-penis-frenum-cumstain for every single name in yaml.
- This approach will drive off contributors to the project, and dash any hopes of having "DM-style ease of use" with yaml. 
- There's more that I can't formulate right now because I haven't eaten anything rn but i'll add to this later.

I don't think tooling or a gui for yaml will solve my issues with this system. Language support is good, yes. But if we're not accepting translations into the main codebase, we can expect codebases that actually DO use the fluent system to convert all those names themselves. We can provide tooling for THEM, but having those terrible strings in the main codebase is awful.

@DrSmugleaf said he'll document the issues with C# stuff underneath.

**Comment by PJB3005** [comment]
> I'm not typing out comp-body-lizard-bottom-penis-frenum-cumstain for every single name in yaml.

We literally already had a solution for this but it got broken with serv3. Waiting on Paul to get back and fix it.

**Comment by Ygg01** [comment]
Having talked to Dr. Smug, we can fix some issues. Like parser and resolver emit their own error, but Fluent is made to be "error-resistant", in presence of errors it shouldn't fail. At least not horrifically. And errors do have spans we can use and messages we can expose.

**Comment by DrSmugleaf** [comment]
The issues in C# are no localization id validation/autocompletion when writing them in code (same goes for YAML) and in general the lack of a syntax highlighter for .ftl files. I started work on a Rider plugin for fluent syntax highlighting [in a personal repo](https://github.com/DrSmugleaf/intellij-fluent-support-plugin) ([Example for a folding builder](https://plugins.jetbrains.com/docs/intellij/folding-builder.html)) but since then @PaulRitter has pointed me to [language servers](https://docs.microsoft.com/en-us/visualstudio/extensibility/language-server-protocol?view=vs-2019) which seems like a better way to do it.
A Fluent linter to validate ids used in YAML would be nice but is annoying to do with some of the prototypes using fluent localization and some not.

**Comment by PaulRitter** [comment]
I have awoken from my slumber, sorry for the later reply:

> I also would like to state that this system being released without any sort of linter or tooling is incredibly frustrating.

yes, but also consider this: tooling & linting will take equally as much effort as to implement the system in the first place. we were building tech debt, simple as that

>     * I'm not typing out comp-body-lizard-bottom-penis-frenum-cumstain for every single name in yaml.

not how it works

> I don't think tooling or a gui for yaml will solve my issues with this system.

elaborate why? which issues exactly?

---
that being said fluent throwing no errors on invalid syntax isn't fine at all and should be addressed asap. im going to retire this issue in favor of a ["todo for fluent" issue](https://github.com/space-wizards/RobustToolbox/issues/1737), as fluent isn't going away
