### ISSUE TITLE
Make GridAtmosphereComponent use JobQueue

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3818]
Probably better to have this unified across AI + pathfinding + atmos for long-running tasks that can be time-sliced.

**Comment by Zumorica** [comment]
Atmos could definitely use Jobs for handling its update stages. However, JobQueue doesn't work since it inserts paused jobs at the very back. Atmos needs paused jobs to be inserted back at the front. Something like this:
`Job A Starts -> Job A Paused -> Job A Resumes -> Job A Finishes -> Job B Starts -> Job  B Finishes -> Job C [...]`

**Comment by Zumorica** [comment]
Honestly, I'm not sure I want this.
