### ISSUE TITLE
Startup / Shutdown cleanup

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3869]
`This can be called multiple times during the component's life, and at any time.`

Startup / Shutdown get called whenever a component's Running property is set. I imagine there's quite a few components that don't handle this properly and should do so.

This refactor has two parts:
A) Some components are manually tracking if they're running and should instead just use the Running property.
B) Likely you'll mostly need to refactor stuff out of OnRemove into Shutdown and (part of) Initialize into Startup on most components.

This property is useful for admins toggling components during runtime or for systems dynamically disabling components for performance reasons (e.g. subfloorhidesystem).

**Comment by Acruid** [comment]
The original idea was that you can start/stop component updates on a per-component basis. This was designed back when components still had their own `Update()` function and `EntitySystem`s did not really exist. This would effectively remove the behavior of a component without *actually* removing it, and allow content to "turn it on/off".

Currently the `Paused` flag completely supersedes this functionality. Having components that are completely disabled but still exist (I guess you are just supposed to poll `Running` every time you access them, just like `Paused/Deleted`) sounds terrible in hindsight. The `Paused` flag already filters components being returned by component queries.

There is zero code that is currently writing to the `Running` property, and it is only being changed internally by the natural lifetime of the component. The whole "Running" concept and code could be completely removed, making Startup and Shutdown just lifetime events. If a few specific components need to track if they are "Enabled" that seems like something that should be handled on a per-component basis.

Because I doubt any Components or Systems properly support this behavior, part B of the refactor is basically going to be auditing and fixing/rewriting most of the 400 components in Content. That is really not worth the effort for allowing an admin to VV toggle a component off.

Do we really want to be able to effectively remove a component (`Running = false`) from an entity without *actually* removing it, therefore requiring *every* piece of code accessing *any* component to have to check the `Running` flag in the off-chance an admin disabled it? If this sounds terrible, then the Running flag needs to be removed.

**Comment by Zumorica** [comment]
I didn't know about this, but after reading Acruid's explanation I think we should just remove the `Running` flag and treat them as lifetime events as he said.

**Comment by metalgearsloth** [comment]
Should we have a method for when the component is paused and resumed then?

**Comment by Visne** [comment]
So what's the deal with this issue now that we've decided to take the ECS route?
