### ISSUE TITLE
Interaction refactor

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3901]
Currently it's messy. Ideally:
* It'd be in shared and predicted
* No more interfaces and all of them replaced with eventbus instead
* General code cleanup / ripping out large parts of it. There's a fair amount of duplicated code that's hard to extend.
* Make the methods not reliant on ICommonSession because this makes any sort of NPC development a massive pain in my ass.
* Drag dropping should be moved to its own server-side system
* While you're at it remove the duplicates in SharedInteractionSystem.cs I beg of you.

This probably also coincides with hands getting refactored to be less spaghet.

**Comment by ElectroJr** [comment]
The issue is relatively outdated and should probably be closed.

> It'd be in shared and predicted

Basically all done.

> No more interfaces and all of them replaced with eventbus instead

Some still remain, but probably better to replace this with a dedicated issue (#8422)

> General code cleanup / ripping out large parts of it. There's a fair amount of duplicated code that's hard to extend.

Has been significantly changed over time. If theres something more specifically wrong with what remains, it should get a more specific issue

> Drag dropping should be moved to its own server-side system

Drag dropping is currently managed separately from other interactions. Was it not when this issue was created, or is there still something left to do here?

> While you're at it remove the duplicates in SharedInteractionSystem.cs I beg of you.

see general code cleanup

> This probably also coincides with hands getting refactored to be less spaghet.

Refactored, now 10% less spaghet

**Comment by ElectroJr** [comment]
> Refactored, now 10% less spaghet

But interactions are still very spaghet
E.g., see #10404
