### ISSUE TITLE
being dead does not stop you from getting oxydamage and eventually gibbing

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3946]
short search revealed this isn't documented yet

what needs to be fixed:
- oxydamage should not gib (?)
- you shouldn't take anymore oxydamage after being dead and - yknow - not breathing

**Comment by scrato** [comment]
The damage comes not from no oxygen but low pressure
![grafik](https://user-images.githubusercontent.com/1233646/118997738-2bb6f200-b989-11eb-9e16-328f2695dc15.png)
this causes the gib. When dead with Envsuit but no oxy the ChangeHealth will not be called again after death
![grafik](https://user-images.githubusercontent.com/1233646/118998785-024a9600-b98a-11eb-8725-01368dfb5af3.png)
But I don't know whether or not low pressure will correctly gib you. I imagine high pressure does, but low?

**Comment by scrato** [comment]
Just my assumption though. But I could not reproduce it with a suit.

**Comment by PaulRitter** [comment]
interesting, so the low pressure is applying blunt damage. genuine question: what would the more realistic behaviour be? maybe damage the body up to a given threshold?
gib threshold is 200 iirc, so maybe only apply blunt damage up to 150?

**Comment by scrato** [comment]
Yeah, I find it fascinating
[What happens to the unprotected body in space](https://www.cnet.com/news/what-happens-to-the-unprotected-human-body-in-space/)
The low pressure will size-up your body to twice the normal size because your blood expands, but the skin will still keep your inner stuff inside. 
So a treshold for blunt damage because of low pressure would make sense in my opinion.
The GibBehavior is set to 400 Blunt damage.
![grafik](https://user-images.githubusercontent.com/1233646/119240562-b0a03800-bb50-11eb-9eab-45ea1c70f90c.png)
Maybe set the treshold low pressure damage at 350? High pressure sure will make you go boom I think.

But what I noticed is that the temperature outside in normal clothing is set at 310.149963 which I think is a bit to high.
(Isnt it around 283 Kelvin?)

**Comment by AJCM-git** [comment]
Now oxydamage has a cap at 40 and blunt at 200 so they dont gib you
