### ISSUE TITLE
PDA flashlights sporadically break after being turned on

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4040]
![image](https://user-images.githubusercontent.com/7907891/119061237-e18e3a80-b9a1-11eb-9416-5704893ccdb6.png)

How to reproduce:

- Go into a dark area and turn on your PDA flashlight. The PDA flashlight will work as long as you remain in the "blob" of darkness, regardless of whether it's equipped to your PDA slot or in your hands.
- Go to an area with lights without changing where your PDA is (if it's in hand, leave it in your hand).
- Go back into a dark area. The PDA flashlight will no longer work. You will need to either put it in a different slot (switch hands or put it in your pocket or PDA slot) for the light to work.
- The light will go back out when you exit the dark area.

**Comment by PaulRitter** [comment]
@PJB3005 any ideas here? seems like the issues isn't with the pda flashlight itself, but some renderer/lighting funnies

**Comment by metalgearsloth** [comment]
was this after rendertree fix?

**Comment by 20kdc** [comment]
So I have found a small problem that could affect lights: Movement and rotation events don't appear to propagate downwards. Please correct me if I am wrong on that.

**Comment by 20kdc** [comment]
Ok, so. Apparently, movement and rotation events not propagating downwards is by-design. ("There is no guarantee it will be raised if they move in worldspace, only when moved relative to their parent.")
This is good because it means the engine won't need to spam movement events, but bad because it means RenderingTreeSystem has to do a recursive search on each MoveEvent.
But doing that fixes the bug, so I'm PRing it to RobustToolbox.
