### ISSUE TITLE
Edge case with cloning players who leave after being scanned/cloned can spawn Urists

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4073]
This bug was originally reported by Hardly#1296, and is a distinct issue from #3654, which I believe was fixed by Swept's cloning fix PR.

![image](https://user-images.githubusercontent.com/7907891/119581149-07478500-bd90-11eb-8342-51d1a4098a07.png)

How to reproduce:

- Clone a player.
- Have the player being cloned choose to not transfer their soul to their new body.
- Have the player being cloned then leave the server.
- Kill the cloned body.
- Attempt to clone the player who left the server.
- The cloner will spawn Urists with no cooldown

**Comment by 20kdc** [comment]
The cloner spawning Urists with no cooldown probably indicates a server exception after https://github.com/space-wizards/space-station-14/blob/master/Content.Server/GameObjects/Components/Medical/CloningPodComponent.cs#L119
Assuming the Urist immediately leaves the pod, it is probably also before line 129 (`BodyContainer.Insert(mob);`)
The problem is, I'm not sure what code here would fail that wouldn't be blocked by other code.
My guess is that `GetPlayerProfileAsync` fails (in which case this may be partially but not completely solved by #4013 - as it moves that step back to scanning time, and an exception in `GetPlayerProfileAsync` would simply cause a silent fail-to-scan)
