### ISSUE TITLE
Incorrect sprite for bread when in microwave

### ISSUE THREAD

**Issue by Swirl-droid** [space-wizards/space-station-14#4093]
**Description**
When placed in the microwave, bread uses the empty plate sprite, or the bread is missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/84341487/119898690-74028100-bf42-11eb-9e35-3aba134aaa64.png)

**Additional context**
v0.1

**Comment by HolyTigerGod** [comment]
The first question why you get bread and a plate not only plate

**Comment by SweptWasTaken** [comment]
Not really a bug since it's how the menu is designed.

https://github.com/space-wizards/space-station-14/blob/1508efff5410aa187e00a960021930295fbd9f0e/Content.Client/Kitchen/UI/MicrowaveBoundUserInterface.cs#L123

It only takes a texture when the bread is a sprite with layers, the bread and the plate.

**Comment by PaulRitter** [comment]
> 
> 
> Not really a bug since it's how the menu is designed.

Its not rendering multilayer items when it should. Fits the definition of a bug in my book.

That being said, this should probably use the control we already have to render sprites of entities (p sure its being used in the characterwindow for example)

**Comment by Visne** [comment]
Yes, the issue here is that ItemList only accepts a texture. It has to be refactored to allow RSI layers.

**Comment by mirrorcult** [comment]
i am pretty sure this is fixed
