### ISSUE TITLE
Emitters and Solar control computers are broken

### ISSUE THREAD

**Issue by SethLafuente** [space-wizards/space-station-14#4293]
## Description

Both of this are connected to electricity the solar control computer does not open and the emitter just doesn't work 

If you click on any of them while you are hosting your own thing to test changes you made your game will crash 

**Screenshots**

![image](https://user-images.githubusercontent.com/84478872/126227368-4d02d526-8f52-4770-bdbf-1e9d38116658.png)

**Additional context**

This was taken in US West

**Comment by SweptWasTaken** [comment]
For the solar control panel when clicking on it it throws
`System.Exception: 'No precompiled XAML found for Content.Client.GameObjects.Components.Power.SolarControlWindow, make sure to specify Class or name your class the same as your .xaml '`
I tried to debug this and don't see why it wouldn't be working.

For the emitter it complains about
`System.NullReferenceException: 'Object reference not set to an instance of an object.' _powerConsumer was null.`
Pretty sure this is due to emitter being kinda shitcode before the Pow3r changes.
