### ISSUE TITLE
Alert crash when using godmode

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4555]
If you take damage, enable godmode, then rejuvenate, often the game crashes because of an alert severity not being found.

**Comment by mirrorcult** [comment]
pretty sure this is just cause of the master tests failing

**Comment by metalgearsloth** [comment]
This is something different to your issue I think. It's been crashing my game locally for a while, I just keep forgetting about it.

**Comment by ElectroJr** [comment]
I can't seem to reproduce that crash by following those steps using either the rejuvenate verb or command. Is there anything more specific you are doing?

On a somewhat related note though, I think godmode isn't actually working properly after the damageable refactor,  you can still take damage. So that's another bug that I let through :/

This is already fixed in #4529, so probably not work creating a separate issue or PR for.

**Comment by AJCM-git** [comment]
I cant reproduce either. Closing
