### ISSUE TITLE
Shuttle rotation issues

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4593]
- [x] Occlusion is broken (PJB said he'd do dis)
- [x] Eye rotation should lerp and not snap when you change parent
- [ ] Engine needs a default Eye behavior but content also needs a way to override this
- [x] Doors don't correctly close as they use the WorldAABB to check if anything's intersecting which isn't suitable when rotated
- [x] Same with EntityStorage checking entities intersecting when closing
- [x] IconSmoothing is... cooked
- [ ] InteractionOutline flickers if a grid is rotating, maybe because of clickmap?
- [x] GridFixtureSystem should probably be shared too so client can at least correlate fixtures with chunks (this is more useful for accurate bounds PR)

Anyone looking to work on these easiest thing to do is changed ShuttleSystem.cs:121 to false and then SharedShuttleComponent.cs:20 to Cruise

**Comment by moonheart08** [comment]
Entity Spawn Panel ghosts and grid freak out on spinning grids.

**Comment by mirrorcult** [comment]
wall bleed blur seems to be nonfunctioning 
![image](https://user-images.githubusercontent.com/19853115/136636439-84786bab-629f-47ff-999a-cbf922025177.png)

**Comment by moonheart08** [comment]
Y sorting is scuffed on rotated grids

**Comment by metalgearsloth** [comment]
y-sorting fixed on https://github.com/space-wizards/RobustToolbox/commit/476b5182f8acfe63b8d459d20faff7b9fb71bf92

**Comment by metalgearsloth** [comment]
Parallax has pop-in when spinning, I'll try to get a recording of it but I keep forgetting.

**Comment by juliangiebel** [comment]
Things get stuck and spasm around inside disposal pipes when the station is rotated

**Comment by metalgearsloth** [comment]
Doors fixed on https://github.com/space-wizards/space-station-14/pull/4874

It's a bit of a hack but it only needs approximate anyway sooooo

**Comment by hubismal** [comment]
Directional Audio seems to be based on world directions instead of whatever grid you're on. So when the ship rotates, so does the direction of the audio. Get a clown next to you to honk his horn repeatedly and turn the ship. If you have headphones you should hear.

Screenspace shaders don't rotate with the camera so there are very ugly borders that cut off the screen. You can see this best with the singulo shader on a rotating ship.
![image](https://user-images.githubusercontent.com/47284081/137568958-b4ac9aa0-237b-44bf-b266-84669f17bbed.png)
