### ISSUE TITLE
Click detecting like pointing and right click menu works in the screen's black bars.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#4651]
## Description
- Find an entity.
- Make sure to not hide it behind FOV, maintain line of sight with it
- Move so it's outside of the viewport and in the black regions on the side.
- Right click it.

The airlocks at spawn work well for this.
![image](https://user-images.githubusercontent.com/10968691/135669880-f5eb3ca9-48e9-4950-b9ff-91c974d001f3.png)

**Comment by ElectroJr** [comment]
Would the solution be to just prevent **any** left/right click interactions happening on the black bars (e.g., clicking on the bars with a gun won't shoot), or to selectively disable only some interactions like examine & right-click?

Also, what is the best way to check if an entity is in that region? Because apparently `_eyeManager.GetWorldViewbounds()` includes the black bars as part of the view-bounds. Is it actually supposed to?
