### ISSUE TITLE
Inserting beaker into ChemMaster doesn't enable the Eject button

### ISSUE THREAD

**Issue by Ygg01** [space-wizards/space-station-14#4660]
## Description
To reproduce:

1. use beaker on ChemMaster 
2. press eject

Expect a beaker. Got zilch.

EDIT: You can eject via verbs.

**Screenshots**
![Content Client_0IFai8Hx7D](https://user-images.githubusercontent.com/1146204/133946242-20b4877d-9392-42c3-9b61-f35ccb76d108.png)
![Content Client_yL5hVhmRzj](https://user-images.githubusercontent.com/1146204/133946278-85c8d0ff-d66f-4a19-98fd-e3ba3e88bbf1.png)
![Content Client_35v5enoYJ8](https://user-images.githubusercontent.com/1146204/133946244-be06df95-cb52-4f62-a7f8-6795efa6440f.png)

**Additional context**
It does work when pressing Eject Beaker.

I suspect the Verb might have broken ChemMaster.

**Comment by ElectroJr** [comment]
I saw this earlier. IIRC the machine is looking for something with a "buffer" solution, while the beaker has a "beaker" solution or something like that.

The beaker is inserted, but as the machine can't find the solution so the UI doesn't update (says there is no beaker, can't press eject button). The verb just checks if there's a beaker inside and ejects it, without checking solution names, so that's why the verb still works. 

This was a couple of days ago, maybe more solution/puddle updates changed that and this isn't the cause anymore.

**Comment by Ygg01** [comment]
Cracks nuckles. 

ChemMaster and ReagentDispenser were on my hit list anyway.
