### ISSUE TITLE
Announcements need a text limit

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#4996]
## Description
![image](https://user-images.githubusercontent.com/7806367/138573465-e15f8bf8-dee4-42c6-8fd4-05c24acea3da.png)

**Comment by TimrodDX** [comment]
> 
> 
> May also be the name/job slots on ID cards

Correct, though the problem is actually worse with ID cards. In this instance, I copy-pasted the entire text of Moby Dick into both the Name and Job fields - first I did the first five or so chapters and then I did the entire e-book copied right from Project Gutenberg. 

Copying the entire book caused the game to crash when I picked the card up.

![image](https://user-images.githubusercontent.com/7907891/138574843-ccff6c00-d224-4908-9168-9433d76afe40.png)

![image](https://user-images.githubusercontent.com/7907891/138574865-122b8bd3-db8d-4ccf-a526-ffcf01881e38.png)

**Comment by SweptWasTaken** [comment]
> 
> 
> Is this for station announcements or server announcements? AFAICT neither has their length checked and the only public caller is the comms console which truncates the message on both client and server and I'm not sure if admin / round stuff should be getting truncated.
> 
> ID card one definitely needs fixing.

Since the ID stuff got fixed shouldn't this be closed?
