### ISSUE TITLE
You can select wires hidden under walls and zap yourself with them.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5089]
.

**Comment by thevinter** [comment]
`InRangeUnobstructed` is being called with `ignoreInsideBlocker=true;`

I'll see if I can fix it but don't count too much on it

**Comment by thevinter** [comment]
Setting `ignoreInsideBlocker=false` in line `133` of `[SharedInteractionSystem.cs]` is a very ugly hack but it seems to (weirdly) fix everything without breaking (seemingly) anything. I tried Dragging, Healing and other stuff that used it as `true` and everything worked.

I'm not committing any PR because i'm kinda sure it actually breaks something I'm not aware of but you should probably check it

**Comment by mirrorcult** [comment]
ignoreinsideblocker true was used for things like being able to interact with wallmounts, does that still work?

**Comment by metalgearsloth** [comment]
I outlined a solution in https://github.com/space-wizards/space-station-14/pull/5121
