### ISSUE TITLE
Combat Mode needs improvement

### ISSUE THREAD

**Issue by GraniteSidewalk** [space-wizards/space-station-14#514]
In my opinion, while in combat mode:
- You should be able to pick up items with an empty hand
- In general, any non-combat mode actions should be taken if no combat mode override is found unless it's explicitly combat oriented, like firing a gun
- Combat hotkey should be C by default, easy to press and nobody cares about character info that much

**Comment by PJB3005** [comment]
Agreed to all of these, mostly.

Personally what I want to do is make it so that "combat mode" acts more like interactions do in SS13, where you will attack stuff if given the chance to but otherwise will just use do regular interactions. Then furthermore in combat mode holding left click for a small amount of time (like 0.15 seconds) should do the full swing combat attacks we have now for melee attacks.

This should mean that interaction is still possible in combat mode for doing things like picking stuff up, but you also won't *accidentally* pick stuff up if you're trying to punch somebody who is walking over a pile of items.

**Comment by Injazz** [comment]
related to #396

**Comment by SweptWasTaken** [comment]
https://hackmd.io/@tgstation/B1NSuS0YI

This is tgstation's design document on a "combat mode". It's relevant as they're planning on removing intents and using a combat mode like us.

**Comment by SweptWasTaken** [comment]
tgstation removed intents and merged combat mode in [this pr](https://github.com/tgstation/tgstation/pull/56601).

**Comment by SweptWasTaken** [comment]
Fixed. Closing.
