### ISSUE TITLE
Forcefeeding is immediate, has no text log and cannot be prevented.

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#5234]
## Description
Forcefeeding whether with pills, drinks, syringes or pneumatic cannons aimed at the skull is immediate, leaves no evidence besides a munching or slurping sound. This even works with pneumatic cannons. One recent round had a traitor RD filling his pneumatic cannon with lexorin and killing everybody on the station, bar one, who he explicitly allowed to live.

Steps:
1) Acquire a food object or container. A pill, syringe, beaker, slice of bread, pizza, etc. 
2) Determine delivery method. By Hand? By Syringe? Or by Pneumatic Cannon?
3) Find your target. Click on them with the active item, or aim at the head with the pneumatic cannon and fire after following normal construction and loading procedures.
4) There is a quiet munching or slurping sound effect (completely silent if syringe) and your target will metabolise the reagents.

Solution: Have a timed bar, a visual log and stop the feeding procedure if there is a mask in the way (or exosuit item such as labcoat or hardsuit).

**Screenshots**

**Additional context**

It's infrequent to see, but it's extremely hard to prevent or even work out who's doing it when someone decides to use poisonous (i,e non explosive) chems en masse on everyone they come across.

**Comment by ElectroJr** [comment]
#5582 Should fix the direct forcefeeding of food & drink part of this. Syringes need to be fixed separately.

The pneumatic cannon actually gets "buffed" by #5582 by not making the target swallow the food whole instead of nibbling on it ... maybe that's a bad idea? But on the other hand, we have logging now so it should be easy to find the culprit. And it's funny.

And yeah, masks & such should block all force feeding. I'm happy to work on that after the basic do-after PR is merged.

**Comment by ElectroJr** [comment]
Can be closed after #5658 and #5656 are merged.
