### ISSUE TITLE
Chemistry Bottles cannot be placed in chem dispenser, master and syringes can't draw/inject from it

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#5236]
## Description
Chemistry Bottles can be drank from and transfer their contents into beakers and large beakers, but they cannot be directly placed in chem-masters, dispensers or drawn from by droppers or syringes. I suspect this is because they don't have the drawable/injectable tag in the code like the beakers do.

Step 1) Go to a Chem Dispenser, put a beaker in and then anything you like in the beaker then alt+click to extract the beaker when done.
Step 2) Put your beaker in the chem-master, transfer to buffer and then create a bottle.
Step 3) Take a syringe and try to draw from the bottle. You won't be able to. 
Step 4) Try to put your bottle in chem master or chem dispenser, you won't be able to either. 

**Screenshots**
![image](https://user-images.githubusercontent.com/93771043/140907984-e49b6965-7e30-48f0-a9e6-5d41b480a2bb.png)

These are the bottles in question

**Additional context**

Since Pills can't be labelled or have sprites changed, the only way for a doctor to be able to identify what's in his medkit or medbelt is using bottles and memorising the descriptions. At the moment doctors have to manually force-feed people (which is not as immediate as syringe) or make the chems on the spot. Or... rigorously catalogue and organise with several medkits and pills.

**Comment by xRiriq** [comment]
> Step 3) Take a syringe and try to draw from the bottle. You won't be able to.

I fixed the injector behaviour in https://github.com/space-wizards/space-station-14/pull/5250.

**Comment by xRiriq** [comment]
> Step 4) Try to put your bottle in chem master or chem dispenser, you won't be able to either.

I don't actually feel like this is a problem but I am more than happy to be wrong. To me the container that you provide as input to the ChemMaster 4000 and the output of the chemical dispenser is a beaker. A bottle is an output of the ChemMaster 4000 and isn't in the same class as the bottle. Because if you really want to put the bottle into either machine you can dump it into the 'scientific object' of the beaker which works for the other kind of chemist devices like the dropper and syringes. I wouldn't expect a dropper, syringes, or a cup from the bar to be able to be used in the chemmaster without transfer to a beaker that 'fits' the machine's outputs or inputs.

**Comment by Peptide90** [comment]
Adding to this, syringes don't seem to be able to draw currently.

**Comment by lzk228** [comment]
can draw and inject, but not fitting in chem machines seems intended
