### ISSUE TITLE
Multiple atmos devices are broken

### ISSUE THREAD

**Issue by juliangiebel** [space-wizards/space-station-14#5341]
## Description

Multiple atmos devices don't work correctly:
- [X] Mixers UI percentages can't be set properly. They reset after entering them.
- [x] Valves still let gas through when closed (#6121)
- [x] Passive gates don't seem to let gas through
- [x] Injectors don't seem to work. Haven't tested powering them.

Problems on Saltern:
 * Oxygen gas valve is closed by default so the air on the station would be replaced with pure nitrogen if valves where to work correctly.
 * The outlet to the left of the air mix thank is using an injector instead of a passive vent

**Comment by ike709** [comment]
> Mixers UI percentages can't be set properly. They reset after entering them.

After testing this it seems the issue is that if you still have the text input selected (ie your text cursor is active) then when you hit set it'll set that node to100%. But if you deselect the text input first and then click set it works as expected.

Not sure what the issue there is because it seems to work fine for the other inputs?

**Comment by ElectroJr** [comment]
Mixer UIs seem to work? Though they are still a bit awkward to use with the "Set" button.
