### ISSUE TITLE
Monkey ghost role lacks the ability to be controlled

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5410]
It's still under AI control, despite having hands.

**Comment by FoLoKe** [comment]
The problem is that MakeSentient() is not called by default in the GhostRoleSystem and mob still possessed by AI, maybe calling it after this line fixes problem by deleting AI and ensuring all controls components:
https://github.com/space-wizards/space-station-14/blob/d35ce8c4a6ad17097183a24954af4ee5e55ee5d5/Content.Server/Ghost/Roles/GhostRoleSystem.cs#L173
Another problem is that once the mob is controlled by human you cannot remove AI because AdminVerb is blocked by existing mind

**Comment by ElectroJr** [comment]
did #5682 fix this?
