### ISSUE TITLE
Chemist has no roundstart spawner

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5511]
## Description
thus, they start at 0,0 on the grid

**Comment by PJB3005** [comment]
Why are latejoin spawners job specific?

**Comment by Zumorica** [comment]
Because `SpawnPointComponent` is shitcode. It has a "job ID" field and a "spawn type", which can be late join, job, observer, etc.
However, from what I can *see* current master gameticker spawning code doesn't take late join job into account.
Ideally, we should have `JobSpawnPointComponent`, `LateJoinSpawnPointComponent`, `ObserverSpawnPointComponent`...

**Comment by PJB3005** [comment]
Uh, yeah, exactly. Spawn point code doesn't care about the job ID for latejoin spawns.

So why is this an issue?

**Comment by PJB3005** [comment]
> Because SpawnPointComponent is shitcode. It has a "job ID" field and a "spawn type", which can be late join, job, observer, etc.
> However, from what I can see current master gameticker spawning code doesn't take late join job into account.
> Ideally, we should have JobSpawnPointComponent, LateJoinSpawnPointComponent, ObserverSpawnPointComponent...

This is far from shitcode, it's lukewarm "could have been done better perhaps but it's so consequential so why even care" at best.

**Comment by Elijahrane** [comment]
Works on my machine
![image](https://user-images.githubusercontent.com/60792108/143448439-3f6786e5-07b6-47a2-8a17-0a14a29fa4aa.png)

**Comment by moonheart08** [comment]
it was like 2AM and I was on the wrong branch :HECK:
