### ISSUE TITLE
Saltern Atmos Area Eats Tiles

### ISSUE THREAD

**Issue by Efruit** [space-wizards/space-station-14#5598]
## Description
https://user-images.githubusercontent.com/602406/143769203-931525ac-43ee-4479-b19f-e74a96aa69f3.mp4

-----

1. Go to Atmos in Saltern
2. Pick up some tiles.
3. Place a tile somewhere without one.

**Additional context**
Running 378d95ff6bb1f0bc3455d489a79dfaac4cb203ec.

**Comment by TimrodDX** [comment]
This is actually a missing sprite, rather than a code bug. When the sprite base got changed to /tg/, "underplating" (what happens if you build lattice and put metal over it) had its sprite changed to be the same as "plating" (which is lattice -> metal -> floor tile). That room uses "underplating" rather than "plating", which is why it eats a single floor tile per tile if you put them down.
