### ISSUE TITLE
Glowsticks currently do not emit light

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#5713]
Glowsticks currently do not light up when activated. Their sprite changes to a glow outline and black centre rod but do not emit light.

Enabling the point light makes them work with their intended effect but permanently rather than on activation.

**Comment by SweptWasTaken** [comment]
I did a bunch of testing with this and I believe it's a result of something constantly resetting the values of `PointLight` to zero on entities with `ExpendableLight`.

You can check this by setting the `Energy` field of `PointLight` on the glow-stick to something other than zero, then cracking it. It'll briefly light for a second and then go dark.

I also think this resetting to zero is what's causing the flare to flash like it does.

![2021-12-14_13-05-40](https://user-images.githubusercontent.com/49448379/146079548-659555aa-d097-47c5-82f6-ab66199fb3ef.gif)

I don't think it's `LightBehavior` since the debug entities for stuff like fade_in etc. all work like they should.

![2021-12-14_13-06-02](https://user-images.githubusercontent.com/49448379/146079621-557aa651-4f9e-4102-bfd6-13772368c79c.gif)

**Comment by Peptide90** [comment]
> I did a bunch of testing with this and I believe it's a result of something constantly resetting the values of `PointLight` to zero on entities with `ExpendableLight`.
> 
> You can check this by setting the `Energy` field of `PointLight` on the glow-stick to something other than zero, then cracking it. It'll briefly light for a second and then go dark.
> 
> I also think this resetting to zero is what's causing the flare to flash like it does.
> 
> ![2021-12-14_13-05-40](https://user-images.githubusercontent.com/49448379/146079548-659555aa-d097-47c5-82f6-ab66199fb3ef.gif)
> 
> I don't think it's `LightBehavior` since the debug entities for stuff like fade_in etc. all work like they should.
> 
> ![2021-12-14_13-06-02](https://user-images.githubusercontent.com/49448379/146079621-557aa651-4f9e-4102-bfd6-13772368c79c.gif)

I noticed the same behaviour. Setting the pointlight / energy to enabled makes the light constantly glow which isn't great but shows the info in there is correct so the issue must be with pointlight as you say.

**Comment by SweptWasTaken** [comment]
> 

Maybe PointLight could be refactored? I believe that @SoulSloth is the original creator of the ExpendableLight stuff so he might have some pointers.

**Comment by lapatison** [comment]
I believe it can be closed, because #10227
