### ISSUE TITLE
Laser guns accept any kind of power cell and can become stupid overpowered.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5751]
## Description

How to replicate:

- Change the map to Packed Station.
- Go to Cargo and order a Laser Crate.
- Open the crate and get a Retro Laser Gun.
- Go to Science and get the Large Power Cell they have there.
- Your Retro Laser now has 225 shots in it. 
- This also applies (to a lesser degree) to the lasers in the armory on Packed.

Logically, each gun should only take one cell type (small or medium, as large is supposed to be for APCs as I understand it) and be unable to take anything else.

**Comment by ElectroJr** [comment]
Adding additional checks to what items can be inserted beyond just checking an entity whitelist requires making some changes to `ItemSlots`. I was going to make those changes either way to support magazine-weapons with their different calibres, so I can just also add in similar checks for power cells when I do that. 

Currently I'm just waiting on #5638, because that also modifies item slots and I don't want to create unnecessary conflicts that I then need to resolve.
