### ISSUE TITLE
Incorrect config settings crash server

### ISSUE THREAD

**Issue by renodubois** [space-wizards/space-station-14#588]
This is from #584, the fix is correct there but the underlying issue is that incorrectly written yaml files can lead to server crashes, when it should really just display a server warning instead.

**Comment by PJB3005** [comment]
There's really no one-size-fits-all solution here. Personally I'm a fan of "fail fast and loudly" so invalid config producing a *mere* warning is iffy to me.

That said, making the game more robust about stuff going wrong is definitely a good idea. #584 was because the entity throws in creation which puts invalid entity data into the entity list. https://github.com/space-wizards/RobustToolbox/issues/949 would avoid "one entity creation failing makes entire game unplayable".

**Comment by SweptWasTaken** [comment]
P sure this is discussed as intentional. Closing.
