### ISSUE TITLE
You cannot place tiles on plating that has wires or other objects.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#601]
Steps to reproduce:
1. Crowbar tile
2. Place wire on plating
3. Try to place tile back

This also happens with chairs and other objects.

**Comment by SpaceManiac** [comment]
seems like this may have something to do with tiles not being as "real" as everything else

**Comment by ShadowCommander** [comment]
The problem is that wire click boxes are the whole tile, so clicking the plating with a wire on it only clicks the wire.

**Comment by RemieRichards** [comment]
We'll have to programmatically vary the bounding/click box based on direction.

**Comment by ShadowCommander** [comment]
Two things need to happen.
Wires and auto-connecting things like that need a programmatically changed click box.
Other things like chairs need to have their click boxes changed in their prototype.

We most likely also need to remove collision boxes from the `stationstation.yml` file too so that the things already on the station have the correct collision boxes. #647

**Comment by AJCM-git** [comment]
Fixel by #1133
