### ISSUE TITLE
Mop refactor

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6048]
How they used to work:
Mop is dry. Click puddle then click bucket to move liquids

How they work right now:
Mop is wet. Click puddle to destroy reagents while mop is wet.

How they should work:
Mop is "dry". Click puddle if mop is wet then click bucket to move liquids.

**Comment by Willhelm53** [comment]
I'll give this a try!

**Comment by Willhelm53** [comment]
I think I understand the mop code well enough to take a swing at this. But @metalgearsloth did you mean anything in particular by the quotation marks around "dry?"

RE: "wet floor" after mopping - instead of showing this as a water puddle, we could either:
1. Hide water puddles below a certain volume (for ~~unwitting players to slip on~~ fun!) and create the need for wet floor signs
2. Change the sprite to some kind of "sparkle" overlay to show that the floor was just cleaned and is slippery.

**Comment by ShadowCommander** [comment]
I think he means that it should work how real mops work in that they use the water to dilute whatever it is on the ground, then squeeze that diluted mixture into a dirty bucket in the cart.

> 1. Hide water puddles below a certain volume (for ~unwitting players to slip on~ fun!) and create the need for wet floor signs

Don't hide puddles, but you can try to make water puddles a bit more transparent.

> 2. Change the sprite to some kind of "sparkle" overlay to show that the floor was just cleaned and is slippery.

Some SS13 servers have a shine decal that gets applied after mopping up the diluted mixture, so that or a shader would be cool to show that it's slippery.

**Comment by DubiousDoggo** [comment]
It would be nice if the mop could handle a few puddles before needing to go back in the bucket, or even just a single puddle for that matter
