### ISSUE TITLE
Implement TF2-like mob collision handling (or another solution)

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#626]
In the case #625 gets merged and #217 is closed we need to go back to the mob collision code and implement a more final feature-set.
What was discussed on the discord was a TF2 system where the faster moving player is moved away, with a slight bit of movement added to the slower player.

**Comment by ancientpower** [comment]
bring back intents you cowards

**Comment by PJB3005** [comment]
I mean combat mode should still make you completely impassible like SS13. Although the current problem is that we don't have any way to avoid both people getting stuck if you enable combat mode on top of somebody.

**Comment by ancientpower** [comment]
ah, in that case the pushback collision system makes sense

**Comment by ProfanedBane** [comment]
Aggressively push them out of your tile then don't let them back in perhaps? No doubt exploitable.

**Comment by ancientpower** [comment]
You could argue that making your mob impassable by changing intent is "exploitable" but I think most people would consider that a game mechanic.

**Comment by PJB3005** [comment]
I find it absolutely astonishing that half the rounds I play in SS13 I run into somebody who WILL NOT turn on help intent when I bump into them and can't get past.

Like seriously there'll be a 5 second shuffle of me (on help intent) pushing into them (not on harm intent) as we go opposing ways and it ALWAYS ends with them stepping aside instead of just hitting 1 on their number row *holy shit*.

**Comment by ancientpower** [comment]
A good way I think it could be handled is like how you can push past NPCs in Stardew Valley (I'm sure there's better examples), you have to press against them for a second and then you can clip through them. 

Basically make it so when someone's in combat mode you can still walk through them but you get met with higher resistance pushing you out of their bounding box.

**Comment by ProfanedBane** [comment]
Could add onto this in that if the dude blocking in combat mode lands an attack on the dude trying to get through it resets the push-warmup.

**Comment by GameMaster85** [comment]
I actually spoke about this in DMs but I should have brought it in a channel. :(

Right, so since I used to do a lot of source engine shenanigans, TF2's pushout system was static but in our case, we can do it a bit more dynamically. I was thinking of a bit of a scalar with differing priorities. When two players interact collision box wise, a scale between them both comes through, where 0 means they are not opposed to player-pushing, and 1 means they are completely not wanting to be entered player-box wise.

If both players are 1, both players will immediately be pushed outside of each other ASAP. This can be used for Object-like mobs like Mechs, or just simply a number close to 1.
If both players are 0, both players will ignore each other completely. (Should not be this, but instead 0.1 so that both players will slowly un-occupy the same space.)

If one value is higher then the other, the one that is higher will take priority. A 0.8 mob will be pushed less out of a spot than a 0.2 mob and if this difference is high enough the 0.2 shouldn't be getting past the 0.8 with their movement. In essence, someone in harm can have a higher value than someone in help, keeping it's intended behavior.

Akin to mech-like mobs, a high enough number like 0.99 will make them barely to never move when pushed into.

**Comment by metalgearsloth** [comment]
Done in new physics.
