### ISSUE TITLE
NSS Pillar Megaissue

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#6460]
Just a list of stuff thats off with it

- Clown theatre is depressurized at roundstart? Seems to depressurize way too fast in general, like arrivals (Mithrandalf#0706)
- Medbay is way too bright. Whole station is kind of too bright
- Engineering is all-access?
- Janitor has no access to their closet
- A lot of windows dont have grilles under them
- Need more stuff in the library, dice+games etc
- We need a AME Controller in Engineering (reported by Projject_Delta#6954)
- Disposals might be unanchored
- No tiles under the clown door (Mithrandalf#0706)

Reported by  @Elijahrane :
- All wardrobes seem to be unfilled
- Chapel needs PietyVend
- The sec checkpoint needs a button and shutters and a locker, ID console, multitool, and maybe crew monitor (yeah they don't save right now but you can set them up with a multitool if you want to man it)
- Chemistry needs a grinder and some starting plasma
- Bridge probably wants a huge table against the window with some flashes and first aid kits and stuff
- Medical could use a few more rollerbeds
- Med break room needs something to put in the microwave (donk pockets)?

**Comment by Delete69** [comment]
![doorstuck](https://user-images.githubusercontent.com/95458399/152619128-b1b41ba5-7797-48c4-aa15-ed60e1c92151.jpg)
doorstuck (unpowered)

**Comment by Pangogie** [comment]
Desperately needs a decoration pass. Posters/carpets/catwalks/flavor trash.

**Comment by Mith-randalf** [comment]
Clown room needs some serious love. Pies, banana skins, station needs some instruments in general. Maint feels super super empty.

**Comment by Elijahrane** [comment]
Misconfigured access:
-Engineering maintenance
-Janitor closet + maintenance
-Sec maintenance
-If that thing in the centre of sec is supposed to be warden's office it should be restricted
-External airlocks
-Research airlocks in that strange room behind shutters to the hallway
-Library (needs new access now imo, it's time)
-Morgue maintainance probably needs Medical / Chapel access rather than just medical (this is true for all maps)


Other feedback:
-Some of the internal spaced areas can probably use glass floors for a safer but similar effect. There's just an insane amount of these
-We have a bunch of bureaucracy stuff now, all those front desks everywhere should probably use some
-More service / greytide fun items like game boards and instruments
-Expand one of the depts somewhere along the main hallway to at least split it in 2 rather than a straight shot
-Replace sec surgery room with evidence storage
-Remove the HOP bedroom airlock to hallway
-Make the empty room below med/research breakroom a sec departmental office
-Cargo could also use a sec departmental office somewhere
-The shiny tile room in rec area would make a nice rage cage room
-No permabrig?
-Map in shutters where they make sense, they can always be set up with a multitool and saving will be fixed when someone codes itTM

**Comment by Kromabae** [comment]
Some of my feedback on Pillar:
1. sec has alot of empty space in it
2. Bridge looks a little like a fortress, which is cool but it kinda sorta isolates at least one person to guard it (not sure if intended)
3. Medbay is very very cramped if you compare it to medbays like Packed or Saltern(maybe add 1-2 extra rooms for cloning?)
4.Engineering seems pretty tucked away and will probably always be forgotten about most of the time since it's waaaaay of from where the action happends, but at least if grav gets cut early on we will know that traitor is most likely an engineer.
5. I love the empty rooms in maints, gives a lot of fun interactions later on with "underground" chem labs and such
6.Cargo confuses me and i dunno why sorry
7. Science is bit and empty ( i know that more is planed for science). As of now the meta for science is always to go as far back into science and make backroom cloning and chems and keep it hidden from general sight, happends on packed and saltern too and no higher ranked officer stops it for some reason even though 9/10 potta bombs come from there.
8. Bar could maybe use one more bartender and another set of bar stuff, with a lot of players on it can get kinda messy and hard to keep up as lone bartender.
9. Maybe add some more bathrooms for the RP
10. eventhough i'm not a vivid boardgame or DnD player within this game i do like the lil game room in library, it's pretty cool
11. needs more hidden wall treasures :D
12. I like the amount of air locks and that almost every department has one.
13. Seeing how mostly all action is going to take place around the medical area, it's probably an issue having literally everyone around that area already with bar kitchen sci and close to bridge and what not.
14. something something the new lights are awesome

that's about it, other than that i would say holy shit nice map very well made and future proofed for new features i might add stuff later but cant ghost the map anymore.

PS, add mice to every map they are so fun to play :D

**Comment by asperger-sind** [comment]
I saw a lotta disposal pipe failures all around the map, some disposals lead deeper into your department, there are routers on the map without tags or taggers present before them, and more things that I can't really remember.

**Comment by Peptide90** [comment]
> I saw a lotta disposal pipe failures all around the map, some disposals lead deeper into your department, there are routers on the map without tags or taggers present before them, and more things that I can't really remember.

I'm addressing all issues on this thread in order however disposals is an odd one. Some being not wrenched down is just unsolvable since they're all placed the same way. All current disposals junctions are dumb, non are the taggable sort as there is no mailroom yet, but I could do a second pass from scratch anyway.

Regarding comments about it not being decorated, there are posters throughout the station as well as trash spawners, other spawners and plants. Lack of decoration comes down to not having tile painting to make the areas look distinct, and lack of content to fill some of the rooms (which I'm going to address by making some rooms abandoned).

I've already made big progress and pretty much resolved the first two lists of comments, I'm also redesigning most of engineering to have more spaces for the content we have and all future content, as well I will redo medbay however it being opposite bar is how it was on box para and I've not had issues, that's why it has a shuttered lobby. If anyone has an idea for what to do about that feel free but I'll be expanding medbay down to add another two rooms, moving chemistry to a bigger room and giving salvage a room or two among other things.

All in all it should hopefully be bug free and easily support large pop rather than medium after the changes. Will post my hackMD change log of all changes when I PR and do the updated shaded maps and a detailed map for certain areas like engineering.

**Comment by asperger-sind** [comment]
> Some being not wrenched down is just unsolvable since they're all placed the same way. All current disposals junctions are 
> dumb, non are the taggable sort as there is no mailroom yet, but I could do a second pass from scratch anyway.

If I understand it all correctly the unanchored disposals might be a product of someone with a spare crowbar and wrench playing on that 110 people server during the testing proccess on Lizard.

On a somewhat related sidenote, I'd love to contribute to making the map by working with the disposal system there (If possible).

**Comment by Peptide90** [comment]
> > Some being not wrenched down is just unsolvable since they're all placed the same way. All current disposals junctions are 
> 
> > dumb, non are the taggable sort as there is no mailroom yet, but I could do a second pass from scratch anyway.
> 
> 
> 
> If I understand it all correctly the unanchored disposals might be a product of someone with a spare crowbar and wrench playing on that 110 people server during the testing proccess on Lizard.
> 
> 
> 
> On a somewhat related sidenote, I'd love to contribute to making the map by working with the disposal system there (If possible).

Just pushed all the fixes to the map now so closing this issue list for now. The disposals seemed to work fine on local testing so you may be right in that it was players causing it.

Disposals includes no routers currently so also not an issue but can be added later when a mailroom is done.

There's some content PRs pending that will need to be added to this map so I'll come back to it in a week or so when they have been merged to make any changes.

Any other issues or suggestions feel free to reopen this issue or tag me on discord :)

**Comment by BasedUser** [comment]
Oh and, the station consumes 40 more kilowatts than the default AME can manage. We have to spend 10000 cargo credits just to get a new AME crate (which takes a long time)

**Comment by Peptide90** [comment]
> Oh and, the station consumes 40 more kilowatts than the default AME can manage. We have to spend 10000 cargo credits just to get a new AME crate (which takes a long time)

Thanks, pushing an update in a few hours so will stick a second crate in.
