### ISSUE TITLE
Examine tooltip issues when quickly examining two objects.

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#6633]
## Description
Shift click on an object then quickly shift click on another object
the description of the first will show under the name and picture of the second
**Screenshots**

![image](https://user-images.githubusercontent.com/47410468/153500725-67893be6-dfd8-4f03-9c71-61f0e002f503.png)

![image](https://user-images.githubusercontent.com/47410468/153500783-8fab184d-9eae-41fb-aff7-30be1c002268.png)

**Comment by ElectroJr** [comment]
This specific issue was fixed by #6489, but quickly examining two things with some network latency is still a bit weird, see this video:

https://user-images.githubusercontent.com/60421075/153803555-88459ca3-3929-4f8b-a4d8-e4a122250a5c.mp4


Ideally if a server requested examine info on some entity, but then closed / cancelled that request somehow, it should be able to ignore the data it receives from the server relating to that request.

**Comment by ShadowCommander** [comment]
@mirrorcult is this fixed?

**Comment by mirrorcult** [comment]
the one electro mentioned hasn't been yet

**Comment by mirrorcult** [comment]
believe i fixed this at some point
