### ISSUE TITLE
Recycler shouldn't instagib

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6822]
While it was funny in ss13 it's hilariously unbalanced for something that can instantly take you out of the round. Ideally it would apply damage over time and if your total damage exceeds <whatever> threshold then you gib but just making it recycle mobs is a decent stopgap for now.

**Comment by Lamrr** [comment]
I don't know, if you run into the stationary death machine it's kind of on you. 

But in a more serious note, I reckon it was balanced in SS13 because of robotics / surgery meaning you could get your brain recycled. I propose we return the instagib once one of those paths are implemented, if we do remove it.

**Comment by Fishfish458** [comment]
So this is kind of a weird balance, previously I believe it was made such that you couldn't just move a recycler just by wrenching it and even though I don't think merely touching it caused death, as in you had to move across the whole thing like a tile and the very rear end of it would gib.

If there's effort made into reducing the killbox range and making sure it doesn't work without power and you couldn't just wrench it somewhere else I think it would be fine.

**Comment by Elijahrane** [comment]
Make it permanently anchored and unwrenchable, I think that was the main problem with it

**Comment by DogZeroX** [comment]
They don't afaik
