### ISSUE TITLE
Doors can get people stuck in walls

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#6849]
## Description

this has been happening quite a bit, need to TP them out constantly

https://user-images.githubusercontent.com/19853115/155044106-b1bbaff6-3457-4f09-a4ca-d79b3fcad588.mp4

**Additional context**

**Comment by Peptide90** [comment]
Do doors have crush safety and if not, shouldn't door crushing knock you down then reopen the door to avoid this issue.

**Comment by Fishfish458** [comment]
I think if door has crush safety, it shouldn't close at all if something is blocking it.

**Comment by mirrorcult** [comment]
that is already the case, but i believe the issue is that if the door is already closing then it doesn't make that check

**Comment by ElectroJr** [comment]
So how its supposed to work for normal/un-hacked airlocks:
- Door checks for entities in the way. If there are any, it doesn't start closing
- Door starts closing visually, but is still transparent and collision-less
- The door then checks again if there is currently a entity in the way
- It then becomes "solid" (collision + airtight + maybe opaque)
- It then eventually finishes closing and can be opened again.

If a mob enters before the half-way check, it should never become "solid" and should just start opening again.
Previously there was a bug where it would properly start opening again but after having prematurely made itself solid, leading to #6841, which should have been fixed by #6836. 

> shouldn't door crushing knock you down then reopen the door to avoid this issue.

If safety is disabled, it should close on entities, become "solid", and stun+damage colliding entities. It then stays solid for the same amount of time that it stuns, and should then become collision-less again and start visually opening. While entities are being crushed, their collision with the door is actually disabled so that they don't get shoved aside or into walls.

There are still some issues I'm aware of:
- Collision is based on world aabbs (i.e., affected by rotation), which they really shouldn't be
- For an entity to be considered 'colliding' the aabbs need to intersect by more than 20%.
  - This should mean if you're just at the edge of the door, it will still close and just nudge you to the side  
- If an entity gets in the way while closing, causing the closing to abort, the animation seems to lurch? Basically is a bit wonky with the animation or client-prediction.
- And then there is whatever is happening here, where I'm really not sure. Can someone confirm that this is still happening, or was this related to #6841, where the door correctly "aborts" but still becomes solid and shoves the player into walls?
