### ISSUE TITLE
Add resizable UI indicator

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#690]
![image](https://user-images.githubusercontent.com/49448379/74291588-309ee780-4cea-11ea-9efd-93e658f5ea5e.png)

Add this little thing to the bottom right of all windows in game to let people know subtly that they are resizable.

**Comment by PJB3005** [comment]
Personally I'd rather the mouse cursor change when hovering over resize areas so you implicitly figure it out after a few minutes.

**Comment by Sindorman** [comment]
> Personally I'd rather the mouse cursor change when hovering over resize areas so you implicitly figure it out after a few minutes.

That's terrible UX. User should not assume things, they should be obvious

**Comment by tentekal** [comment]
Not sure if I would consider that terrible UX, but I can see a few people being confused. 

Changing the cursor when hovering a resizable container should be trivial after I get my PR in. Considering that the UI containers know their dimensions/root corner by nature I think adding a small carrot like that wouldn't be too bad.

**Comment by PJB3005** [comment]
> That's terrible UX. User should not assume things, they should be obvious

I mean, basically every desktop platform nowadays does it like this. That said I do suppose there is an argument to be made here because not every window is resizable.

Actually fitting in the resizable indicator shouldn't be the end of the world, since the UI design mockups I made (and still have to implement) don't have window contents be a simple box anymore anyways, so fitting them in shouldn't be too annoying.

**Comment by SweptWasTaken** [comment]
I guess i'll just assign this to PJB so he remembers to add this when he gets around to implementing the UI changes.

**Comment by SweptWasTaken** [comment]
Eh, fuck you Feb 18 Swept
