### ISSUE TITLE
Thrown objects can go forever

### ISSUE THREAD

**Issue by collinlunn** [space-wizards/space-station-14#705]
Thrown objects keep moving until they collide with something, they should probably decelerate during movement or otherwise stop on their own after some amount of time or distance when not in space.

**Comment by partyaddict** [comment]
#686 probably related

@Qustinnus

**Comment by Zumorica** [comment]
> #686 probably related

It's not related. This issue has been there for a long time.

**Comment by ancientpower** [comment]
I'm working on this as part of the physics engine not having inertia.

**Comment by PrPleGoo** [comment]
How should the max distance you can throw an item be determined? 
Something something mass and throw force?
I can figure out some arbitrary values for that.

>they should probably decelerate during movement

Decelerating the item might make the throw feel really weird to use, since you'll have to estimate non-linear movement which can be especially difficult when trying to hit moving targets.

>stop on their own after some amount of time or distance when not in space

I suggest just making the item just touch the floor after that distance and let the friction handle it.
Space doesn't have friction so all of that should solve itself.

**Comment by collinlunn** [comment]
A throw distance field in yaml would likely be sufficient - a mass value may obfuscate the point, unless we use "item mass" in multiple systems in the future.

**Comment by GameMaster85** [comment]
Newtons law of physics states that this is an intended feature.

Jokes aside, it's more the throwing force of a mob that limits the throw when the item hits the "ground" normally. We should probably check our floor (or gravity on area) once we reached a throw force limit to see if we should keep moving. If we're in space? Let newton take over.

**Comment by AJCM-git** [comment]
Fixed by #872
