### ISSUE TITLE
Wall decon time needs nerfing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#7065]
Airlock decon time got increased because airlock hacking time increased (which got increased because armoury rush was too fast). I asked if airlock decon was too slow and was told it's fine hence walls need to take a little bit longer to decon to compensate.

**Comment by HoofedEar** [comment]
Walls as in, normal walls? Or reinforced? Or all walls in general. Just want to clarify 😅

**Comment by Emisse** [comment]
R walls are in a good spot imo, normal walls you can disassemble super fast

**Comment by HoofedEar** [comment]
> R walls are in a good spot imo, normal walls you can disassemble super fast

So would just adding more time to the welding be a good fix?

**Comment by Fishfish458** [comment]
This will get some balancing later on when welding walls without protection gives people eye damage, just adding in a second or so should help for the timing.

Not sure if this is a separate issue but I've seen building walls being abused as well since there's no delay when putting metal onto a girder.
