### ISSUE TITLE
Bed Buckling into Crematorium exploit

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#7234]
## Description

If you place a bed in front of a crematorium, you can use it to buckle someone into place long enough to instakill them in the crematorium. When combined with any kind of stun mechanic + being bound (handcuffs, makeshift cuffs, etc.), you are essentially dead from the moment you have been cuffed unless stopped.

Steps to repro exploit:

1) build bed in front of crematorium
2) find target, cuff them
3) buckle them to bed, they cannot escape
4) toggle cremation tray
5) ignite crematorium

**Screenshots**

Something better than screenshots. Video: https://www.youtube.com/watch?v=_Hze0GuydMc

**Additional context**

** Originally sent in an ahelp regarding this b/c powergaming, tried reaching out to admins directly, got told it was a github issue so here **

The player (Character name: White // Username: White) showcased in this video did it about a half dozen times. He did not use a bed the first time but was using a stun baton/cuffing to keep people still while he shifted them around in front of the crematorium, then evolved to using a bed which is what prompted the recording. I was a spectator only in this round, did not participate in any capacity other than observing. After watching him do this multiple times, I asked in Discord if it something along these lines was powergaming, and that's when a trialmin (Todd Howard) reached out via DM since he saw the ahelp I filed about it.

**Comment by RandomDeathMatch** [comment]
I don't think this is an exploit since you can also just push the person over/stun baton/whatever else then pull them in. Which seems intended. There are infinite ways to murder someone you have cuffed.

The reason to do this is it is faster than shift right-click dragging them into the position in the narrow area. It isn't less foolproof though since they can unbuckle instantly if they prepare to to click unbuckle, and become undragged. I haven't watched the video yet but the chaplain for example nearly escaped 3 times this way.

If anything the problem is cuffs are too foolproof? And stun batons can stun lock people while down and being dragged? Iirc the CE didn't even get cuffed was just stunned a bunch. And in at least a case or two the bed wasn't even used.

**Comment by retequizzle** [comment]
The issue isn't the cuffs being a death sentence, it's more the fact that the bed being used as a force-to-prone method, then being pulled into the crematorium with the tray despite being buckled to the bed. The cuffs really just guarantee that you aren't breaking out of it for about 90 seconds.

**Comment by RandomDeathMatch** [comment]
But you can do it without the bed. If the person is cuffed you can just move them in front of it, push them down then cremate them. No counterplay there either.

**Comment by Fishfish458** [comment]
Could counter this by claiming making crematoriums detect living players and refuse to cremate unless it's emagged.

**Comment by dmnct** [comment]
This no longer seems to be reproducable. I couldn't find why, but buckled mobs are not picked up by the crematorium when it closes

**Comment by Visne** [comment]
Indeed I can't seem to reproduce this anymore. Feel free to re-open if you find a way to exploit this again.
