### ISSUE TITLE
suit sensor / device network performance issue

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#7317]
On the recent stress test suit sensors is stupidly expensive (over half of tick time was on it!) and scales poorly for many players. Not entirely sure why it's happening but Mirror was investigating.

Ideally suit sensors would only send payloads whenever anything besides map pos changed (instead of an update loop) + the other funnies going on is found out (e.g. if it's broadcasting on the same frequency as everything else or something).

**Comment by ElectroJr** [comment]
AFAICT one of the problem is that `ConnectionsForFrequency` will iterate over all devices on a network (e.g. all wired or all wireless devices) every time any message is sent. Instead of a `FindAll(connection => connection.Frequency == frequency)` it should probably be a dictionary or something.

But the bigger problem is probably that they do all just use the default frequency, so the cost of the updates goes like N^2, because every device on the network will raise at least two events at every other device on the network, which also results in many wireless range checks.

Given that nothing stops a device from sending on a frequency that differs from the one it is receiving on, the medical monitors should probably just be put on a separate frequency from the sensors. And to prevent stuff like this in future, the default frequency (0) should probably just be considered invalid? Would also make it easy to disable receive capability, which (so far) is completely unused by things like suit sensors. That would also prevent people from killing the server by finding and pinging the sensor frequency, or the frequency of whatever other high-quantity send-only devices get added.

**Comment by juliangiebel** [comment]
I'll implement your suggestions @ElectroJr. 
Preventing entities from receiving any device messages when you only want to send is a good idea.
