### ISSUE TITLE
Implement more modular grenade triggers / payloads

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#7318]
## Description

#7138 has been merged, but this only adds timer triggers. More should be implemented (voice activated, proximity, health sensor, remote signallers)

Most of these have **already been implemented** in #4980, but this PR was too large and the author stopped working on it. The code can still be easily salvaged, though.

**Comment by ElectroJr** [comment]
Several of the new triggers require some sort of configuration UI. E.g. device-net frequency, voice-analyser key phrase, health sensor toggle, proximity sensor range. A good chunk of the older PR was just about adding all those BUI, BUI events & UI handling.  So it might be worth considering just extending `ConfigurationComponent` to get rid of much of the UI boilerplate and allow people to easily give components a basic UI for inputting simple configuration information (name + text field, spinbox, or enum-dropdown).

Alternatively, one idea that was previously discussed (2022-01-22 maintainer meeting) was to directly add an input pop-out to the verb menu, AFAIK that would work for all of these components, but that should probably still go though some sort of configuration system/component in order to keep things general. The timer-trigger time-selection verbs should probably also use something like that.

Then again, this is scope-creep. So someone could just port over all the existing UI stuff for now, and the triggers could be moved to a more standardized configuration interface after being added.

**Comment by Emisse** [comment]
this exists now
