### ISSUE TITLE
The void still exists 

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#7462]
The void still just deletes entities from the current plane of existence. 
How to reproduce:
 -set up a disposals line and have the end of it be a pipe at the edge of a grid
 -send something through disposals
-when it hits the end of it it won't get spit out into space
-the entity gets sentenced to eternity in the void
-profit???

**Comment by Veritius** [comment]
Took some screenshots for a report on this I made and then closed because I neglected to check if anyone had actually reported it (shame on me)


A body went into each of these chutes. The right and middle chutes emptied onto an occupied tile, and allowed the body to leave. The left chute, however, tried to eject into empty space.

![image](https://user-images.githubusercontent.com/45957058/163708075-bc288af0-0d8c-46ac-9f9a-a7adf35ae3b9.png)
