### ISSUE TITLE
Food/drink balance is not good

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#7604]
## Description

eating several whole pizzas sometimes doesn't even fix your hunger

hunger/thirst is usually completely ignored until you start dying of it, mostly because of how slow it is to matter

**Comment by mirrorcult** [comment]
aside from tweaking nutriment count may want to look at tweaking vitamin/protein count in certain foods, though IDK if that is balanced badly at all

**Comment by retequizzle** [comment]
i would just make it so the moment you hit red gauge for food/water you just start taking toxin damage that ramps up over time, as a result of your body literally trying to consume itself for resources. at that point the toxin build up would eventually slow you down the more you ignore it and address a movement debuff at the same time. also accruing damage interrupts do-afters which addresses that too, so only think you'd have to account for is how often you want that toxin tick to hit (every 30 seconds? 15 seconds?) in order to keep it balanced. would suck if you died because too many ticks were interrupting food do-afters

as far as nutriment/vitamin/protein goes we could do with more of it in prepped meals. i rarely ever notice that my health gauge improved after a meal and i'm regularly hurt in some fashion.

**Comment by Elijahrane** [comment]
Vitamin/protein is fine IMO, I didn't really touch nutriment much if at all in that pass though. For me the main problem is satiety is both unresponsive and doesn't seem to actually properly stop you from eating like 5 entire pizzas unless you hit the 250u chem limit

**Comment by Fishfish458** [comment]
Just putting in some context: In most ss13 servers (ones that I know of anyhow) when you start to get hungry you start slowing down, to the point where when you are absolutely starving you're practically ss14 critical speed slow. When you're full as long as you're eating 'healthy' foods you actually slowly heal minor injuries passively (imagine like 10 brute over 3-4 minutes).

I think that we should stray away from hunger/thirst causing damage but make it give other passive debuffs:
weaker punches
more susceptible to knockout drugs
slower speed
slower to perform actions such as construction/deconstruction/action bar stuff.

They're not fatal for neglecting but they bring attention to the need for upkeep.

**Comment by mirrorcult** [comment]
its Fine now should make separate issue thats better
