### ISSUE TITLE
Player vehicle issues

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#7753]
- [x] They're not predicted because ???
- [x] Damage goes to the vehicle instead of the player which is overpowered.
- [x] There's issues with space movement (not sure on specifics).
- [x] Mask + layer need fixing.

**Comment by Elijahrane** [comment]
> Damage goes to the vehicle instead of the player which is overpowered.
No it doesn't?

https://user-images.githubusercontent.com/60792108/164985252-281b4b9b-b5b5-44c8-8ae4-8a96aa140d17.mp4

**Comment by Elijahrane** [comment]
Took a look, wasn't able to get a fix but I have some info on these issues:

> They're not predicted because ???

They're not predicted because they're really reliant on buckling stuff that only the Server BuckleComponent has. The movement SHOULD be predicted since it's handled by the movement systems all other movement is rather than vehicle sysem.

>  Damage goes to the vehicle instead of the player which is overpowered.

Haven't been able to reproduce this at all, I think people are just missing and blaming the vehicle.

>  There's issues with space movement (not sure on specifics).
There are 2 seperate bugs.

#1: https://github.com/space-wizards/space-station-14/issues/7752 . This one is extremely bad but it's not related to the vehicles directly and it happens in other places 2

#2: Vehicles ignore gravity. This is because only MobMovers are affected by weightlessness. I made an attempt to get vehicles to use that, but it's really, *really* not designed to be used with anything but mobs.

**Comment by Dragunovi** [comment]
There is also a problem that causes wide swings done by the vehicle rider to hit the vehicle they're riding, its a bit awkward.

**Comment by Peptide90** [comment]
> There is also a problem that causes wide swings done by the vehicle rider to hit the vehicle they're riding, its a bit awkward.

Solution: vehicles should take up your hand slots so you can't attack while riding them. Seems possibly OP? 

If cargo want to pull crates or whatever maybe we need to put rope in now to stick stuff together.

**Comment by Elijahrane** [comment]
> > There is also a problem that causes wide swings done by the vehicle rider to hit the vehicle they're riding, its a bit awkward.
> 
> Solution: vehicles should take up your hand slots so you can't attack while riding them. Seems possibly OP?
> 
> If cargo want to pull crates or whatever maybe we need to put rope in now to stick stuff together.

This deliberately takes some of the fun out of them. They already take one hand slot, and after some more of the gun refactors are in I was going to make wielding guns increase accuracy. You wouldn't be able to wield guns on a vehicle since the vehicle adds a virtual hand slot. Also, all projectiles pass through the vehicle and hit you directly. I'd rather just fix or disable wide attacks on vehicles.

**Comment by Elijahrane** [comment]
> Vehicles also don't have collision with stuff like lockers.
Locker collision groups are fucked up, bullets pass through them too

**Comment by ElectroJr** [comment]
- [ ] Drawdepth and offset is based only on local rotation.

This causes issues when in space or watching someone on a rotated grid. Really this needs to take into account the players local eye rotation to determine the draw-depth and offset. To fix this, this probably needs to be moved client-side, and the offset should probably be a sprite-offset, rather than a position offset. Though this might cause issues with fixtures/collisions?

**Comment by Peptide90** [comment]
All vehicle related issues: #7755 #7803 #7810

**Comment by Elijahrane** [comment]
> * [ ]  Drawdepth and offset is based only on local rotation.
> 
> 
> This causes issues when in space or watching someone on a rotated grid. Really this needs to take into account the players local eye rotation to determine the draw-depth and offset. To fix this, this probably needs to be moved client-side, and the offset should probably be a sprite-offset, rather than a position offset. Though this might cause issues with fixtures/collisions?

Why is the offset grid-dependent when it literally changes their position?

**Comment by metalgearsloth** [comment]
> * [ ]  Drawdepth and offset is based only on local rotation.
> 
> 
> This causes issues when in space or watching someone on a rotated grid. Really this needs to take into account the players local eye rotation to determine the draw-depth and offset. To fix this, this probably needs to be moved client-side, and the offset should probably be a sprite-offset, rather than a position offset. Though this might cause issues with fixtures/collisions?

I agree on sprite offset having looked at it, they look very wrong when viewed offgrid due to the current jank code trying to offset its position when this won't work for sprites.

**Comment by metalgearsloth** [comment]
Still issues with vehicles I've been told, e.g. collision with mobs mispredicting.

**Comment by mirrorcult** [comment]
Vehicle Gone
