### ISSUE TITLE
Cargo Console can hang the server when ordering too many items

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#789]
This can be fixed by setting the starting points lower and also limiting the amount of items that can be ordered.

**Comment by JiimBob** [comment]
I think this issue might be related to the crates colliding, it seems I can order a large amount of items if I'm not directly next to the console, but as soon as I bump the stack of boxes the server hangs. Maybe this could be fixed by having some sort of cargo receiving bay that queues up the crates, only spawning one at a time.

**Comment by remove32** [comment]
i'm working on this one - i was going to just set the max order size to 20, and i think something similar might be suitable once the shuttle gets implemented, but JiimBob's comment about spawning one at a time is a decent point. might look into that later
