### ISSUE TITLE
Putting an activated stun baton in a security belt makes you invisible.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#7893]
## Description

This bug was originally reported by Old Dance Jacket#1112 on Discord. I have reproduced it on live as of 05/01/22 at 7:30 PM EST.

How to replicate:

- Spawn (or obtain) a security belt.
- Take out the stun baton.
- Turn the stun baton on.
- Put the stun baton back on the belt.
- You will now be invisible until you move or are pulled out of position.

**Screenshots**

**Additional context**

**Comment by BlitzGunner225** [comment]
So that’s what happened

**Comment by mirrorcult** [comment]
probably something to do with trying to add mapped layers that dont exist ?? and then it blows up?

**Comment by OldDanceJacket** [comment]
Worth noting about this bug is if you quick move it to the belt (SHIFT E), you do it normally, but if you MANUALLY click on the belt  to but the live baton away it makes the baton swing icon on yourself and you go invisible.

It's difficult to tell when this behavior came up because of this, as I almost always SHIFT E, but suddenly stumbled across this when failing to put the baton into my belt

![image](https://user-images.githubusercontent.com/98985560/166184135-126d88e3-abe2-45b8-b608-eef00402cbc0.png)

This is the intended behavior, and on the other servers this IS what happens as demonstrated here.

However on the main...

![image](https://user-images.githubusercontent.com/98985560/166184522-a59b5d09-334d-47ba-8052-d8e7fe7daec4.png)

Documented here is the new behavior where, if a bag is full, instead of giving you a _"cannot insert"_ message and keeping the item in your hands, it drops to your feet instead. This is why I assumed this behavior was linked to the belt being full originally, but it seems as though it's not the case and is just a manual input with the baton on the belt. Again this is recent behavior and **seems** linked to whatever changed to have items drop at your feet when belt/bag is full.

**Comment by Fishfish458** [comment]
> It's difficult to tell when this behavior came up because of this, as I almost always SHIFT E, but suddenly stumbled across this when failing to put the baton into my belt

Probably happened because of storage container ECS , though that's such an insane deviation from other storage related bugs.

**Comment by moonheart08** [comment]
Fixed.
