### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by BozoDel** [space-wizards/space-station-14#7942]
Hi.

I have sparked a discussion on the FreeGameDev forums about whether mixing CC BY-SA and CC BY-NC-SA assets is possible. I argue that it's not possible for the assets that go into the game. The details of how I came to that conclusion are in the threads. But I also believe that the songs and images that play in the lobby do not form a derivative work, and there is no conflict (Space Asshole is safe).

Others believe that there is no conflict whatsoever, claiming that CC copyleft is weak copyleft, but providing nothing to support that claim.

Others have brought up the issue of having NC stuff and receiving monetary support through Patreon. The concept o NonCommercial in CC licenses is left purposely vague, but I believe that, in this case, with the transparent accounting and all money going into hosting, it shouldn't be a problem. Still, there's plenty of room for disagreement.

https://freegamedev.net/d/186-what-are-you-playing/10
https://freegamedev.net/d/189-licenses-was-what-are-you-playing
https://freegamedev.net/d/196-space-station-14-uses-cc-by-nc-sa

I would really appreciate if you folks could take your time to consider this issue. Thank you.

**Comment by ike709** [comment]
I can't speak for the audio assets, but I can speak for all of the sprites. Usual IANAL included.

All of these sprites are taken from Space Station 13, where the exact same arrangement occurs (except, believe it or not, sprites don't even have license information or author attribution immediately available like RSIs) and all parties (authors included) are completely fine with the arrangement regarding both license mixing and patreon with NC assets.

Frankly, it doesn't really matter if the licenses conflict nor if patreon is commercial if the rightsholders are completely fine with it. It's not like anyone's ripping random internet sprites from random authors, everyone is knowingly contributing to SS13 in this state.

**Comment by ike709** [comment]
Also if you really want to get upset about something, go done the actual SS13 licensing drama rabbit hole (which SS14 is not responsible for).

**Comment by mirrorcult** [comment]
> 
> I argue that it's not possible for the assets that go into the game. The details of how I came to that conclusion are in the threads. 
> 

Your argument seems to be that SS14 somehow counts as a derivative work of all of its individual assets--meaning that it would indeed count as an adaptation and thus there would be conflicts because BY-SA and BY-NC assets. On the other hand, we have no idea how the individual assets we use somehow don't count as individual assets just because they are packaged together later. 

Who is correct here? No one will ever know, because none of us are lawyers, and this is never going to court--remember, this community has a 19 year history (far messier license-wise than you could ever know). We know who the rightsholders are, and we know they could not care less about dumb semantics like this.

> Others believe that there is no conflict whatsoever, claiming that CC copyleft is weak copyleft, but providing nothing to support that claim.

You are the one that has to substantiate the claim. CC licenses never claim to be infectious; the terms they are distributed under only mention that you must attribute the work and give proper credit. There is literally nothing supporting the claim that CC licenses are hard copyleft.

> 
> Others have brought up the issue of having NC stuff and receiving monetary support through Patreon. 
> 

CC's description of NC draws the line at "[works] primarily intended for or directed toward commercial advantage or monetary compensation." We are transparent with our Patreon funds, and it's clear that they do not give us a commercial advantage nor are they used to compensate anyone. Is there room for legal games with this? Sure, but they're never going to happen.

Anyone without a law degree who tries to make these points should be laughed out of the room. Please don't bring your pointless license LARPing to our repository and expect us to care about it in any capacity.
