### ISSUE TITLE
Can't open backpack storage when wearing it

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#810]
The button registers the event as UseOrAttack, and the code checks for Use.
You can open the backpack normally when on your hands

**Comment by FL-OZ** [comment]
Shouldn't this use a modifier key? e.g. shift + click. Ideally an input profile system for rebinds to avoid hardcoding shift would be nice.

**Comment by PJB3005** [comment]
We already have input profiles like that. Using a modifier key click is kind of hard because most of them are already reserved:

1. Shift click is examine.
2. Control click is throw.
3. We need a key for pulling (ctrl click in most code bases?)
4. I would like to have an alt button similar to SS13 alt click too.

**Comment by FL-OZ** [comment]
Maybe middle click?
