### ISSUE TITLE
Jaws sometimes dont pry flooring

### ISSUE THREAD

**Issue by AugustEymann** [space-wizards/space-station-14#8255]
## Description
Jaws of life randomly choose to not pick up flooring

**Reproduction**
no idea completely random
**Screenshots**
https://i.gyazo.com/32de79bfa0d2872ad8fd1780949a1a9f.gif

**Additional context**

**Comment by AugustEymann** [comment]
also seems to be an issue with the omnitool

**Comment by themias** [comment]
Steps to reproduce:
1) Hold a tool with multiple modes, Jaws of Life or Omnitool
2) set to any mode besides prying
3) click a floor tile as if to pry
4) The tool now can't be used for prying

It looks like the ToolSystem.TilePrying gets stuck with a CancelToken never being removed, since it fails UseTool() -> StartToolUse() due to not having the right quality, and OnTilePryCancelled() and OnTilePryComplete() are never invoked to remove the token.

@metalgearsloth it looks like this is related to your change #8074 d7168fedd11287322507e806fa232938e34ade94

It might be as simple as clearing the CancelToken before returning in that first if statement, but I'm not sure if that would defeat the purpose of your change. I'll let you take a look.
