### ISSUE TITLE
EnsureComp<T> should be purged from component init

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8423]
Stuff like machine linking is very naughty with this.

**Comment by ElectroJr** [comment]
I'm not sure if there is a nice way of ensuring that components will be able to function when dynamically added to an entity without use of `EnsureComp`. E.g., there are many components that rely on the entity having a container, and not being able to ensure container (which also ensures `ContainerManagerComponent`). Removing all uses of EnsureComp during init would just make adding/ensuring components to existing entities a PITA because each time you'd have to verify that the component doesn't rely on other components to function.

If its just about minimizing the use of `EnsureComp` in init, thats probably fine. I don't expect people to ever really need to add things like `SignalSwitchComponent` to an existing entity. But if it ever does, it should probably log a warning or something then, because without any related machine link components it is completely useless and something has probably gone wrong.

Is the main reason for the performance tag because the init functions get slowed, or because when an entity prototypes doesn't have all components that get added on add/init/start, it results in bloating map files & server states?

**Comment by PJB3005** [comment]
The solution is very simple: just have something like `[RequiresComponent(typeof(ContainerManagerComponent))]` that you can slap on whichever component needs containers.

**Comment by wrexbe** [comment]
yeah, but adding component with VV

**Comment by ElectroJr** [comment]
Or just use both that attribute + ensure comp?

**Comment by PJB3005** [comment]
> yeah, but adding component with VV. I guess VV could do something special, and look for that

This is for **initialization**. This has nothing to do with adding components later.

> Or just use both that attribute + ensure comp?

No. Any amount of half-assing here will keep us in the current situation where entity creation logic is a spaghetti nightmare because it has to account for all kinds of bollocks going on during init.

**Comment by ElectroJr** [comment]
> This is for initialization. This has nothing to do with adding components later.

The whole point is that some components rely on other components to function, and currently use ensure comp to make sure they can work. So getting rid of ensure comp  during init would sill break adding some components via VV after the entity has been initialized.

Unless the plan is to also just update the component adding so that dependent components are always also added before init/startup events get raised.

**Comment by PJB3005** [comment]
> Unless the plan is to also just update the component adding so that dependent components are always also added before init/startup events get raised.

Of course.

**Comment by mirrorcult** [comment]
this is pretty much fixed by #10274
