### ISSUE TITLE
You can reset the announce cooldown by unscrewing and screwing the comm computer

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#8506]
## Description

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Jrpl** [comment]
Looking into this. This bug is still valid.

### **Description**
Announcement cooldown can be bypassed by unscrewing and then re screwing the communications computer.

**Reproduction**
1. Make an announcement.
2. Use a screwdriver on the comm computer to unscrew it.
3. Use a screwdriver on the comm computer to re-screw it.
4. Make an announcement.

**Additional Context**
It looks like the reason for this happening is that when the comm computer is unscrewed, the comm computer becomes a computer frame and therefore is a new entity entirely. When the computer frame is re-screwed, it becomes a comm computer again and is a new entity. Each entity has a different `_netId` and `_uid` because of this.

**Comment by deltanedas** [comment]
it should be stored on the station or map rather than the console
even without reconstructing people can use multiple consoles to spam announcements

**Comment by Jrpl** [comment]
> it should be stored on the station or map rather than the console
This seems like the most reasonable solution. Some sort of global variable that tracks the announcement cooldown.

**Comment by Jrpl** [comment]
After re-thinking this issue, I think a better alternative would be to have an initial cooldown anytime a comms computer is created. The initial cooldown can be separate from the normal announcement cooldown of 1 min 30 seconds if desired. A side effect of this would be that on map init, all comms computers would be on a short cooldown.

For example, round starts and someone tries to access a comms computer to make announcement. They have to wait 30 seconds before they are allowed to make an announcement. Once they make an announcement, they have to wait the normal 1 min 30 seconds before making an additional announcement. If they unscrew and re-screw the console, they will still have to wait at minimum another 30 seconds since this now counts as a new comms computer entity.

I already have the code for this written and tested. Thoughts on this solution?

**Comment by VasilisThePikachu** [comment]
> After re-thinking this issue, I think a better alternative would be to have an initial cooldown anytime a comms computer is created. The initial cooldown can be separate from the normal announcement cooldown of 1 min 30 seconds if desired. A side effect of this would be that on map init, all comms computers would be on a short cooldown.
> 
> For example, round starts and someone tries to immediately access a comms computer to make announcement. They have to wait 30 seconds before they are allowed to make an announcement. Once they make an announcement, they have to wait the normal 1 min 30 seconds before making an additional announcement. If they unscrew and re-screw the computer, they will still have to wait at minimum another 30 seconds since this now counts as a new comms computer entity.
> 
> I already have the code for this written and tested. Thoughts on this solution?

In my opinion 1m30s sounds like too much, 30 second sounds good. You should be able to make an announcement at round start. Otherwise I think the solution is good. If you have a solution already pr it

**Comment by deltanedas** [comment]
they can also just take the board

**Comment by VasilisThePikachu** [comment]
> they can also just take the board

They can, I'm talking about powergame joney here. Takes one of the boards. Hides in maints. Keeps screwing and unscrewing the console and now all command can't use their coms console at all. Since this value will be added every time a new coms console is created

Why don't you make this a global cool down, making an announcement will need you to wait 30 second on all of them? No need to make it take 30 seconds for every new coms console created

**Comment by deltanedas** [comment]
that would be 30 seconds for the console thats just built, not globally
if its stored globally ignore construction

**Comment by Jrpl** [comment]
> They can, I'm talking about powergame joney here. Takes one of the boards. Hides in maints. Keeps screwing and unscrewing the console and now all command can't use their coms console at all. Since this value will be added every time a new coms console is created

My proposed solution still tracks announcement cooldown per coms console. So even if someone steals a board and keeps screwing and unscrewing the console, all other consoles will still work normally.

**Comment by Jrpl** [comment]
The only issue I see with my solution is that you can't use the console immediately on round start but I think that's a reasonable trade off to not have announcement spam all round.

**Comment by Jrpl** [comment]
PR https://github.com/space-wizards/space-station-14/pull/21681 fixes this. It can be closed.
