### ISSUE TITLE
Sec can't quickly access departments during emergencies

### ISSUE THREAD

**Issue by youarereadingthis** [space-wizards/space-station-14#8519]
In SS13 it was common to give security access to various departments so they could do their job better, however this was understandably disabled on other servers considering how much it enables abuse. And it seems a decision has been firmly made not to have this in SS14(at least by default).

Something that could bandaid this issue is a Warrant system. Would let sec send temporary access requests that need to be approved by HoS/command. If approved then for a short time any sec ID can access a specific department regardless of what access the cards normally have. Once the time is up they lose the emergency access.

1. (easy) Having sec make a request over the radio or in person for command to put it in a console themselves.
2. (proper) A "Request Warrant" UI in an authorized sec PDA that requires a reason and department(s) to be input. Sends the request for command approval. Approval is done either within a command PDA or at a console.

**Comment by Peptide90** [comment]
“To give access to security”, reads a little weird how it is now as if you want to give security access, to other department. Anyhow I got the gist.

In ss13 this is fixed by having an AI that can open doors for the crew in order to prevent harm to other crew members. 

However submitting warrant requests would be neat. It should go to the wardens criminal records computer for approval and print a paper warrant for any lawyers to use. Once approved it should give sec the appropriate access level to investigate and arrest for say 5 minutes.

**Comment by ike709** [comment]
I like the second option a lot, but it'd probably be better to do it after someone has rewritten PDAs to suck less. Could be a feature of security PDAs to request department warrants and command PDAs to reject/approve.

**Comment by mirrorcult** [comment]
not actionable enough
