### ISSUE TITLE
Non-default maps have broken physics

### ISSUE THREAD

**Issue by InquisitivePenguin** [space-wizards/space-station-14#861]
Steps to reproduce:
1. Load a new map by typing `addmap 2 false` and then `loadbp 2 Maps/stationstation.yml` in the server console after launching the server.
2. Type `tp 0 0 2` in the client console.
3. You won't be able to move, and nothing collides with anything.

**Comment by SweptWasTaken** [comment]
Replicated

**Comment by PJB3005** [comment]
That's because you loaded the map pre-mapinit (second argument to `addmap`). This means everything on the map should be paused. You need to run `runmapinit 2` first.

That said, there is a somewhat related bug, namely that if you move an entity between maps it doesn't correctly update the physics tree on the new map (or remove it from the trees on the old map) meaning collision checks won't find it. Working on that one though.

**Comment by InquisitivePenguin** [comment]
That makes sense. I first discovered this while trying to do map editing, and I guess it makes sense that the map should be 'paused'; guess I didn't realize that was intentional. I'll add that to the map editor documentation just so nobody else gets confused like I did.
