### ISSUE TITLE
Cargo design rework

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8645]
## Description

Problems: 
- Cargo can pretty much indefinitely supply itself as long as it has a way to break open crates
- Cargo has zero incentive to ever interact with the rest of the crew
- Cargo has essentially zero gameplay

Mirror brand short term plan:
- [ ] Make cargo unable to order department-specific crates without access, and ~~remove access locks from ordered crates~~ (probably unnecessary). If cargo wants to order engi equipment/guns/whatever they need help from someone with access, or someone with access needs to request it at the console in the cargo lobby
- [ ] Implement cargo selling using the new pricing system. Make goodies from other departments (high-end and potent produce, rare gases, medicine) worth a lot, so that cargo is incentivized to seek out and form mutual relationships with other departments
- [ ] Vastly increase the cost of most recquisitions orders to incentivize construction or salvaging over direct purchases, and to make  cargo points valuable

Mirror brand Five Year Plan:
- [ ] Move salvager duty from cargo to RND: better facilitates interaction with xenoarch, gives RND more of a purpose, forces salvagers (big potential money influx) away from the convenience of cargo
- [ ] Implement 'Station as a logistics hub' from Peptide's doc https://hackmd.io/@Peptide90/Cargo. Little neat gameplay for them to do and earn money passively
- [ ] Port mail delivery from Nyanotrasen and originally from /tg/. Forces player interaction in a fun way
- [ ] Remove the notion of 'cargo points' and just integrate it directly with credits/money
- [ ] Implement a galactic market system alongside the normal NT recquisitions, for random items that can be ordered. This is to serve as an influx for various departmental goodies that would otherwise be limited to only one source (like salvage) including xenoarch artifacts, materials like diamond or uranium, and rare circuit boards.

**Comment by Veritius** [comment]
Short term solution: Trying to break a secure crate will destroy the contents. Or explode. Exploding is funnier.

**Comment by Kromabae** [comment]
with the secfab being a thing, why not just keep it as it is but all gun crates come with no ammo, only empty mags and the guns. Secfab just never gets used at all i feel like

**Comment by TimrodDX** [comment]
Okay, I need to comment here, because I think this is an idea that is thoroughly in the wrong direction. 

If cargo is a non-job right now, how is a system where they effectively need direct approval from a head to do anything going to make it more of a job? At that point, you might as well replace cargo with a fully automated system that doesn't have anyone working in it, because if cargo can't do anything by themselves no one is going to have a reason to play cargo. 

I also don't understand where the incentive is for cargo to sell anything if they can't do anything by themselves. No one is going to want to play a job that consists of sitting outside science and begging them for things to sell so that the heads can continue to order things. 

Another thing I don't quite understand is what moving salvage to R&D would accomplish. Salvage already spends their entire round building shuttles instead of doing anything useful, and you want to put them with a department that would further enable them to do that? 

Honestly, if anything, this feels like the old /tg/ system where R&D was completely dependent on mining to do anything - you know, that system absolutely no one liked - except inverted so that Cargo is now in that position.

**Comment by wrexbe** [comment]
It won't be heads only, it'll be restricted across the different access levels.
Cargo won't need to beg anyone. Other departments are going to have things they want from cargo. I think the intent of moving salvage is to prevent cargo from being able to generate their own income. Im not sure if thats a good solution either, but it might be easier to balance salvage if it's attached to R&D.

**Comment by Peptide90** [comment]
Mfw non of the comments are actually about the issue that was posted.

This isn't a thread about nerfing cargo it's about giving them stuff to do. Go make your own discussions on balance.

**Comment by ike709** [comment]
>  Make cargo unable to order department-specific crates without access, and remove access locks from ordered crates.

Not a fan of this one, dept crates should always be locked IMO.

The other bits are good ideas though.

**Comment by mirrorcult** [comment]
yeah I guess they can stay locked anyway it doesn't make much of a difference

**Comment by ike709** [comment]
Does porting mail from Nyano also include porting the actual Mailman role? Or is that just under the purview of cargo techs?

**Comment by mirrorcult** [comment]
i think I'd keep it as a cargo techie thing. they don't have much to do on their own

**Comment by DogZeroX** [comment]
Bumping this if someone wanna add a comment about cargo stuff. I know bounties are in.

**Comment by Emisse** [comment]
convert this to a doc
