### ISSUE TITLE
Revert netfakeloss

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8823]
At least until the 2 connection issues are sorted. I get the point was to highlight issues but half the time my game crashes now. This may also need the fake random lag reverted. FakeLagMin is fine.

**Comment by wrexbe** [comment]
I agree
- It ruins the experience of anyone new to the project
- It makes testing PRs a mystery, did the PR break something, or was it a fake network issue?
- Content feels like the wrong place to be trying to deal with duplicate, or missing packets

**Comment by ElectroJr** [comment]
> Content feels like the wrong place to be trying to deal with duplicate, or missing packets

The whole problem was that the majority of people never bothered to test PRs with the networking cvars, and issues due to lag or packet loss just got ignored. So IMO it definitely should be enabled by default.

But until the connection issues are fixed the fake loss & duplicates should probably be temporarily disabled.

**Comment by ElectroJr** [comment]
Actually it still seems to crash even without loss & duplicates

**Comment by PJB3005** [comment]
> Actually it still seems to crash even without loss & duplicates

Lagrand is the thing you want.

**Comment by ElectroJr** [comment]
space-wizards/RobustToolbox/pull/2949 and space-wizards/RobustToolbox/pull/2950 should hopefully make the revert unnecessary. 

> Lagrand is the thing you want.
Is this some issue due to lag rand causing messages to be received out of order or something?
