### ISSUE TITLE
Health analyzer partial removal / Interactive diagnostics

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8884]
## Description

Health analyzers present too much information to the player and are extremely readily accessible. As a result they end up stifling what could be interesting medical gameplay in favor of 'person goes to medbay and stands around while the doc uses an analyzer and immediately knows what everything wrong with them is'. By scaling back their usage (removing them from doctor kits, gating them behind high-end research, only giving round-start to ERTs) we can introduce more varied and interesting doctoring gameplay--less info goes a long way, IMO. This is partially expounded on in one of my docs but not in detail or anything: https://hackmd.io/@rQ2pYSFtRl20YDfmkEtgzA/epic-fail. 

The basic idea is that the patients explaining what their injuries are and what caused them should be incentivized. Usage of varied tools to diagnose things based on what the patient tells you is good. Doctors can be differentiated skill-wise by how much information they require to diagnose certain things (patient is vomiting--must be sick or taking toxin damge). More subtle tells can be added for various effects (like what some diseases already have) so that diagnostics is less one-dimensional.

Of course, this means we now need tools to diagnose various things that health analyzers would normally tell you:

- [x] Brute/burn damage #6749
    - [ ] Doctors should have a better form of this, maybe using some item to enhance the examine. Or, skill system when.
- [ ] Toxin damage (partially diagnosable by vomiting, occasionally, but needs something better)
- [x] Asphyxiation damage #8228
- [ ] Chemstream issues (what was in their system?) #8883
- [x] Blood information #6788
    - [ ] Still needs a more indepth examine with numbers. Doctors should have some stationary tool for this
- [x] Disease info (we never added this to the analyzer to begin with, swabs are very good)

Future stuff we don't actually have yet:

- [ ] Organ damage. Should use some stationary machine that you put people into to determine internal damage, IMO. External organ damage like eyes/ears should just be info given by the patient or examinable directly.

**Comment by Elijahrane** [comment]
Would you be fine moving radiation from a type to a group? All of the stuff you could diagnose from it applies better to burn, toxin, or cellular damage, so why not make it a group of those and rebalance chems a bit for it? It's a lot rarer now too with rad storm gone.

**Comment by Peptide90** [comment]
> I'd like to say that I already examine people and ask them what happened whenever possible instead of health analyzer doafter scan, merely to save time. 

This should be the way. Part of a doctors job must be finding out the cause by checking signs and symptoms. Signs being what you can deduce from examination and symptoms being from the patient.

> patients fail to provide accurate information pretty frequently. 

welcome to doctoring! That guy who’s complaining he’s dying? Who would have thought it’s just a hangover and he’s wasting your time.


> I also like to monitor action of medicines with health analyzer. 

This should be relegated to a tool or analysis just for this, rather than a do everything cheat code. Blood analysis, scanners and actually seeing an improvement by signs or symptoms becoming treated.

> Also health analyzer is vital to differentiating cancer from other diseases early.

This is the sort of stuff full size body scanners and things like blood analysis should show. Not something handheld unless it’s an advanced late game scanner.

**Comment by Fahasor** [comment]
Maybe just remove poison group and give to existing poisons another one of existing type of damage(not only one type). I think in real life poisons have diferent behaivior, some make you paralized and then you die because you can't breath, another one destroy one of your organs (According to that logic we can remove burn damage group and make it part of brute, but i think this types realy differ from each other, but in real life poison damage is a couple of another types for my point of view). But maybe focus on diagnostics of poison and make some mechanic of blood analyze or, like you wrote analyze vomit, but i think we can't make it only by vomit, this is too simple. And also in that way we can make poisons buffed in some way to force people not healing entity until poison metabolized (not use medicine), but also make some mechanic to destroy that poison, like stelybine and amatoxin now works, make some medicine for each type of poison, and also we have a problem here if poisons be buffed by just increse damage, then they just kill him outside medbay, i want make gameplay looks like entity dies slowly, but doctors can't make anything without some antidote, they must know what is a type of poison inside entity to give right antidote, but also we can't easily heal him using medicine that heals burn, brut and etc. P.S. My english are bad and i can look rude on unpolite here, i just give you my ideas, you can make with them what you want. I think poison type brokes logic, this is why make good analyze mechanic is hard. Also my ideas too hard to make, you must destroy what you make before.

**Comment by mirrorcult** [comment]
closing since too generic + not very actionable or agreed on rn also newmed
