### ISSUE TITLE
Chem dispenser sugar can be eaten to replenish hunger

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8889]
## Description

bad

related to #7604

**Comment by Peptide90** [comment]
This was an old meta (sugar pills) I can see two solutions: make sugar nourish less when it’s by itself (hard since food and drinks use this still).

Or giving excess sugar a toxicity effect (basic, sugar > 10 apply 1 toxic damage) or, hell can we make that an inflicted disease )diabetes as a punishment for people abusing sugar? Requiring you to take injections for the rest of the round.

**Comment by PJB3005** [comment]
How does SS13 handle this?

**Comment by mirrorcult** [comment]
pretty sure sugar just doesnt replenish hunger in ss13. or no one cares about chem dispenser balance so it doesnt matter
