### ISSUE TITLE
Miasma is too unforgiving

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9148]
A bunch of feedback stating the title from game admins but I haven't sat down and tested figures in-game. Feedback specifically:
- Activates too fast from when someone dies.
- Miasma itself gives too many diseases and is too punishing if not dealt with. You can say "skill issue" but this is in practice.

**Comment by Elijahrane** [comment]
> Activates too fast from when someone dies.

The nuance here is that a rotting body doesn't accumulate enough miasma to cause problems for a very, very long time, over half the average round length. A body can start rotting and no one will get sick from it for at least 20 minutes in most cases, outside of extreme cases like being in a 1x1 ventilated room with it. Scrubbers, by default, handle about 1 1/2 corpses worth of miasma from the room they are in. If it weren't for the decomposition gibbing (which helps clean up entities no one has cared about for like 2/3 the average round length), then corpses could lie indefinitely without causing any problems in most rooms. Even after that, scrubbers tend to bring them under the disease threshold. 
If https://github.com/space-wizards/space-station-14/pull/8954 gets merged that will be closer to 2 (assuming they take my default suggestion increase). 
And that's just human corpses. The heaviest pets weigh 20 kg, compared to humans 70kg. Most pets weigh about 5 kg, meaning they produce 14 times less miasma than a human corpse. The one thing people cheesed was cows, but for entities like that you can specifically turn down the mols per kg (which I have already.)

> Miasma itself gives too many diseases and is too punishing if not dealt with. You can say "skill issue" but this is in practice.

This is actually somewhat of an issue, but it'd be harder to implement a more robust version of ChemCauseRandomDisease.
Maybe there can be a single disease, stored in miasma system, that randomly changes every 5 minutes or so? Most miasma outbreaks are over within <30 seconds, so that would stop the disease scaling with too many mobs in a room.
