### ISSUE TITLE
Waystation Cargo Shuttle docking

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#9187]
It's too tight to both the doors, the solars room on the right is one tile too big to make both doors of the shuttle fit

![5b438c9d117cc1f98d45e315f368ce61](https://user-images.githubusercontent.com/97402700/175815546-839c3139-41ce-4d2a-b675-b7629a29a810.png)

My quick fix mid-round

**Comment by Kromabae** [comment]
Also this map is missing a the Emergency docking port

**Comment by TimrodDX** [comment]
Can it still fit at least one dock? This is kind of a non-issue if it fits at least one dock, because ideally there will be per-map cargo and evac shuttles with auto-pilot.

**Comment by Kayek14** [comment]
The docking airlocks are also reversed on the cargo side. not sure if this is new but figured ill post it here since this issue is related to waystation cargo shuttle docking.

![waystation docking ports bug](https://user-images.githubusercontent.com/106507028/177220685-308346a3-3d3a-402d-ac5c-28856118d36e.png)

**Comment by EmoGarbage404** [comment]
irrelevant
