### ISSUE TITLE
Syndicate minibombs do not blow up.

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#9297]
Syndicate minibombs do not blow up.

Steps to reproduce
1. Arm a syndicate minibomb
2. Watch it not blow up

**Comment by Mirino97** [comment]
I tried it a bunch on a local server.
I managed to get a Fatal Exception in Explosions(something) but I could read nor screenshot the error due to using the runserver.bat.
After that, both on debug and release, through Rider or runserver.bat, I could not replicate the fatal error, and the minibombs worked normally.

@ElectroJr Pinging you since this is your area, methinks!

**Comment by ElectroJr** [comment]
I can't manage to reproduce it locally. It'd be good if someone found a reliable way to cause it.

I know there was [some entity lookup error](https://discord.com/channels/310555209753690112/790656972801572905/991828287158501406) recently, maybe its related?

**Comment by Mirino97** [comment]
![image](https://user-images.githubusercontent.com/52474532/176737033-57633f80-d240-4311-b50d-7ffd06bbfcc1.png)

**Comment by Stealthbomber16** [comment]
I have now seen this with C4 and this has allegedly happened with the nuke as well. Blankmann has reported this occurring with fireball too.

This is not a minibomb issue, this is an explosion issue. I do not know what is causing it but it is occurring semi-consistently on live and I will do my best to note it in discord whenever I get a report of it happening.

**Comment by Stealthbomber16** [comment]
Fixed with the entity lookup error fix presumably. Either way, haven't seen it in a month so this is squashed.
