### ISSUE TITLE
Following verb exception

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9496]
![image](https://user-images.githubusercontent.com/31366439/177587255-338c66b8-4236-42a5-a136-3fe736cbdfed.png)

I imagine the verb is predicted and the client doesn't know about it. Probably just have it early return if the entity doesn't exist.

**Comment by ElectroJr** [comment]
In order to predict a verb the client still has to know about the entity. My guess is that the client executed a verb at some point, then got a state from the server saying the entity (or user) had been deleted, but the way the predictive events work results in the predicted verb event still getting re-raised for a while longer.

Either way the right fix is to just add a deletion check, which should have been added anyways for the server to sanitize client inputs.
