### ISSUE TITLE
Resources/Audio/Machines/alarm.ogg is a bad sound effect

### ISSUE THREAD

**Issue by nfreader** [space-wizards/space-station-14#9583]
## Description
[This is a bad sound effect](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Machines/alarm.ogg). Using a sound effect from a real fire alarm will cause alarm fatigue, and could result in someone mistaking an actual fire alarm for just another false alarm in SS14. Or vice versa. There’s a reason you don’t hear this alarm in any other games.

(I made the same comment on[ a tgstation PR to add the same sound effect](https://github.com/tgstation/tgstation/pull/40919#issuecomment-429630046))

**Comment by PJB3005** [comment]
What even classifies as a "fire alarm" sound? Any fire drill I've ever been in and the building had at least 5 completely different sounding types of fire alarms all around it.

Also, what sets this sound apart from the alarms in, say, Alien: Isolation?

**Comment by moonheart08** [comment]
> What even classifies as a "fire alarm" sound? Any fire drill I've ever been in and the building had at least 5 completely different sounding types of fire alarms all around it.
> 
> Also, what sets this sound apart from the alarms in, say, Alien: Isolation?

This is the most common alarm sound used, i.e. it's the only fire alarm I've ever heard in the countless fire drills I've been in. I'm on the touchy side for audio so this also implicitly means I **hate** this sound.

**Comment by PJB3005** [comment]
I'm assuming it's a very common sound in North America or something then. At least changing the sounds to not be directly ripped from something common in real life seems like a good idea if only for artistic reasons.

I don't know if *just* changing the sound to not be a specific common sound is enough though for the whole fatigue thing. I don't know if fire alarm sounds are standardized in some countries, but that doesn't feel enough to rely on (if they are here in Belgium they sure didn't bother to retroactively tear down many generations of existing alarms in schools etc).

Maybe this is a great opportunity to take a page out of Alien: Isolation's sound design and have many distinct alarm sounds randomly chosen per fire alarm. This creates the awesome effect where moving around actually changes the alarm sound around you, which helps it feel much more varied. Crucially for this I believe it would more easily associate the sound as coming from "in game" rather than the real world.

**Comment by mirrorcult** [comment]
yeah I'm 100 percent fine with this being changed I just couldn't find anything better at the time

**Comment by wrexbe** [comment]
To be more specific, it sounds like a smoke detector alarm
https://www.youtube.com/watch?v=czyGmRXJ184

**Comment by Kimpes** [comment]
How does this alarm sound? I based it somewhat on the original while trying to make it easier for the ears to listen to. [https://www.mediafire.com/file/k8dc0lo9x45gnrx/Alarm_Sound.ogg/file](url)

**Comment by nfreader** [comment]
> How does this alarm sound? I based it somewhat on the original while trying to make it easier for the ears to listen to. [https://www.mediafire.com/file/k8dc0lo9x45gnrx/Alarm_Sound.ogg/file](url)

This is a stupendous improvement. Bonus points for making it a four-tone instead of three. Three blasts of sound from generally anything, a whistle, horn, alarm, etc is universally perceived as a distress signal. Using four helps subvert that and differentiate it from a real-world alarm.

**Comment by mirrorcult** [comment]
> How does this alarm sound? I based it somewhat on the original while trying to make it easier for the ears to listen to. [https://www.mediafire.com/file/k8dc0lo9x45gnrx/Alarm_Sound.ogg/file](url)

this is very good, I can PR to replace it if you're unable to

**Comment by Kimpes** [comment]
Thanks for the response! I've got git set up so I should be able to PR it myself if I can figure out how to do it correctly
