### ISSUE TITLE
Being at maximum thirst (red "Parched") makes your game mispredict movement or something

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9648]
## Description
Being at maximum thirst (red "Parched") makes your game mispredict movement or something. This seems to be noticeable only with high ping. If you reach "Parched", movement becomes extra painful. You are not only slow, but when you release movement key, you rubberband back a bit.

**Reproduction**
1. Do glorious 200 ms ping gaming
2. Ipecac self into "Parched" or just neglect your character
3. (Optionally) eat something to fix hunger just to be sure it's thirst slowdown to blame
4. Suffer as you move with game rubberbanding you back tiny bit whenever you release movement key.

**Additional context**
Does not seem to apply to hunger's slowdown. Only thirst.

**Comment by asperger-sind** [comment]
It's a weird bug, happened to me about 7 times total, but it's really inconsistent, some maps for some ungodly reason didn't have this whatsoever, and it's both hunger and thirst in my experience, and sometimes the bug just doesn't happen even if the conditions are met.

**Comment by metalgearsloth** [comment]
Probably fixed in https://github.com/space-wizards/space-station-14/pull/9656

**Comment by metalgearsloth** [comment]
hunger clientside was refreshing movespeedmodifiers but does nothing with the information so there's 2 issues:
1. Is that some of the movespeedmodifiers still aren't predicted. The server sends the modifiers as a "just in case" which was getting bulldozed because of hunger and never updated because the client didn't know about some modifiers.
2. Nutrition in general needs to be moved to shared.
