### ISSUE TITLE
Physics improvements

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#965]
- Adjust player strenght so that you cant push more than 3-5 lockers?
- Reduce objects elasticity a bit so that they dont blend too much
- Reactivate player collisions now that the mobs dont get stuck inside of eachothers
- If you try to go up next to a wall/table/obstacle your screen jitters a little
- Reduce sliding a bit
- If you push a locker into a wall and then open it it will go through the wall.
- Lockers get stuck/affect items

**Comment by InquisitivePenguin** [comment]
> Adjust player strenght so that you cant push more than 5 lockers?

I'm working on that.

> Reduce objects elasticity a bit so that they dont blend too much

Elasticity is pretty low already, the reason why objects clip through each other when you're pushing against the way is because I capped the collision handling iterations at a pretty low number. If you increase that number, you'll see less of that. Of course, performance takes a hit the higher you raise the iteration count.

> Reactivate player collisions now that the mobs dont get stuck inside of eachothers

Huh, didn't know those were disabled. I'll get on fixing that.

**Comment by PJB3005** [comment]
It's still possible to push into a wall and end up jittering on the edge of it too from what I can tell.

**Comment by AJCM-git** [comment]
Take a look at #626 for the players collision thing (just so you know, reactivating them should be enough for now)

**Comment by metalgearsloth** [comment]
If you push a locker into a wall and then open it it will go through the wall.

**Comment by metalgearsloth** [comment]
Fixed in physics refactor
