### ISSUE TITLE
Whole screen shaders/overlays sometimes get drawn incorrectly.

### ISSUE THREAD

**Issue by Zuzuk-null** [space-wizards/space-station-14#9657]
Artix linux, nouveau (NVIDIA GeForce 9600 GT), sway + XWayland

https://youtu.be/qNlsBWjcLB0

**Comment by ElectroJr** [comment]
For whatever reason the drunk effect seems to be breaking. Does the same thing happen with the drug-shader or when you are near the singularity? Are there any errors in the console when you connect to a server?

**Comment by ElectroJr** [comment]
> Yes

Then it just has something to do with whole-screen shaders that somehow get drawn to the screen wrong, causing it to seemingly zoom in on the lower left corner.

Its hard to fix without being able to reproduce it locally, cause I have NFI what causes it and AFAIK no one else has ever reported this issue. Unless others manage to reproduce it, fixing it might just require using you as a guinea pig at some point, which would require you to do [basic dev setup](https://docs.spacestation14.io/getting-started/dev-setup).

This should also maybe be an issue in engine/RobustToolbox if its a rendering issue, instead of content/ss14. But again I have no idea what causes it and maybe the problem lies with the shaders or overlays and not the rendering.

**Comment by Zuzuk-null** [comment]
The problem is still relevant for me. How can I help fix it?

**Comment by Zuzuk-null** [comment]
https://youtu.be/6riuenlMmCs

**Comment by ElectroJr** [comment]
I still can't figure out what's wrong, other than that that it looks like the `SCREEN_PIXEL_SIZE` shader uniform probably has the wrong value, but I have no idea how that happens. I don't even know how best to debug this other than throwing in sanity checks like `args.Viewport.Size == args.Viewport.RenderTarget.Size`

@PJB3005 help.

**Comment by ElectroJr** [comment]
After some [discussion on discord](https://discord.com/channels/310555209753690112/900426319433728030/1023760032405405736), unless other people start reporting similar issues with different hardware this might just be a case where your card/driver/setup is too old and/or cursed to fix.

**Comment by rene-descartes2021** [comment]
@Zuzuk-null I had minimal problems on Debian, nouveau (NVIDIA GeForce 9800 GT) and X11 not wayland. 8+ months ago. I bought a ryzen minipc since then.

Singulo shader worked then. Also flashbang. Viewport had something odd on startup, iirc view scaling setting in options was broken (game super slow iirc), had to jimmy it (set to far left and restart iirc) to get the game functional. I didn't have the weird effect you show in the YouTube video. I think the drunk and drug shaders were new since then, so maybe they wouldn't work for me either. Iirc sometimes the game would slow down in the same way and I just rejoined to get around that.

Aside from setting up Dev environment you could try using a tool like apitrace and see if you notice anything odd, but this would take a lot of time. I've been able to fix other games shader problems on the 9800 GT using just apitrace and editing shaders. Other suitable tools may exist.

**Comment by rene-descartes2021** [comment]
@Zuzuk-null Some ideas if the devs don't want to support your card, and I'm right about fragment shader a being the issue:
Out of curiousity I looked for what tool can be used to modify the Shader used by the application when using nouveau. gDEBugger doesn't support new enough OpenGL. CodeXL or GPU PerfStudio might work. Using such a tool to edit the fragment shaders in use. Such tools sees the shaders used by the application by tracing the API and has a front end to map those shaders in use to custom ones.
Another idea is to set `__GL_SHADER_DISK_CACHE=1` and `__GL_SHADER_DISK_CACHE_PATH=/tmp/nv` and see if it is as simple as replacing the shader files with ones that work on your card in that path. Might work with nouveau, you could ask on their IRC for tips.
One horrible thing I noticed is the default shader cache is on disk for the proprietary driver and it really slows down the fps or causes stuttering for some games on linux in my experience. Horrible oversight, is `~/.nv/` by default.
NVIDIA probably has a similar tool but IIRC it didn't support Linux and probably wouldn't support nouveau.

**Comment by PJB3005** [comment]
Renderdoc is *the* tool to use, but it doesn't make it easy to recompile shaders like something like NSight does.
