### ISSUE TITLE
Delta Atmos: What's missing

### ISSUE THREAD

**Issue by 5150Con** [space-wizards/space-station-14#9658]
## Description
Delta's atmospherics has had some issues for a while now, and I just wanted to submit an official issue so that it can be noticed. These issues mainly involve:

1. Delta's Mixer chamber is disconnected, there is a missing pipe under the window leading into the chamber.
2. Delta's missing several gas miners, such as H2O, Plasma, and I believe CO2. This really limits atmospherics to just setting up air mix and then having nothing to do the entire shift. Plasma chamber also is not connected at all, there is an output pump but not piping leading into the chamber, which doesn't have a miner either,
3. Delta's chambers are really hard to see into, and it makes new players confused as there is only a 1x1 window looking in, and the rest is blocked off with walls.
4. Some weird piping that have dead ends, or do not connect to anything.

**Reproduction**
Play Delta as an atmos tech.

**Screenshots**

![20220711192341_1](https://user-images.githubusercontent.com/104950325/178557603-d4c8606b-ad96-459c-9c9b-c8421a8f794a.jpg)
![20220711192400_1](https://user-images.githubusercontent.com/104950325/178557628-e44a140e-5f12-4ef7-b4e8-f0c4b5d8e171.jpg)

**Additional context**
Delta is a huge map, so it's understandable that some things will be missed. I likely missed a lot as well, but I can only stare at pipes so long.

**Comment by Peptide90** [comment]
Windows being small isn’t a huge issue imo.

Also we don’t map plasma miners because people will pipe them into distro. CO2 and water Vapor miners are also eh since they’re not used for much.

Other issues are legit.

**Comment by 5150Con** [comment]
Well, the window issue bothers me mostly because the tanks are far bigger then any other map, but the window is tiny comparatively. For the plasma miner, the only thing to do in downtime as tech is either map air alarms or make Tritium, and you can't really do one of those on Delta. CO2 and Water Vapor are indeed eh, but sometimes making a double airlocked steam room is a fun break. I really think that if you just shrink down some of the gas holding tanks, there would be plenty of space for the other gases, and make it future-proof once more gas mixtures are added in.

**Comment by TimrodDX** [comment]
Point 2 is intentional. Air alarms and fire alarms do not work correctly, so I have not mapped plasma in. That's also the reason the plasma tank is disconnected at round start.

In regards to Point 3, that's how the original map is. The reason there's no water vapor miner is because water vapor doesn't exist on the original map. The empty tank is for N2O, which isn't in the game yet.

The disconnected pipes you're talking about are likely the ones meant for the supermatter chamber, which are intentionally disconected because the supermatter engine is not yet in the game. I believe I labeled the pump going to that pipe "Mix to Supermatter (UNIMPLEMENTED)" for that specific reason.

The pipe for the mix tank is something I can fix.

**Comment by Peptide90** [comment]
> Well, the window issue bothers me mostly because the tanks are far bigger then any other map, but the window is tiny comparatively. For the plasma miner, the only thing to do in downtime as tech is either map air alarms or make Tritium, and you can't really do one of those on Delta. CO2 and Water Vapor are indeed eh, but sometimes making a double airlocked steam room is a fun break. I really think that if you just shrink down some of the gas holding tanks, there would be plenty of space for the other gases, and make it future-proof once more gas mixtures are added in.
> 
> But I appreciate your input, I can see the plasma miner being easily abusable, but isn't that why techs are non-antags only?

Techs can’t be antags correct but that doesn’t stop anyone getting atmos access and wrenching two pipes to ruin the round. That and even though atmos techs aren’t antags, they still manage to spoil rounds. 😭

**Comment by Kayek14** [comment]
Atmos not having a plasma miner on delta is intentional but why do some stations have one while others dont? I do agree with OP in the regard that having no miners makes atmos a really boring job. Not having something implemented because griefers could grief is a bad approach imo. Gutting half of the fun out of a job because it could be used by other players for nefarious reasons really sucks for those who want to play atmos tech and experiment (safely) with various gases. 

I do agree with the part where delta not having air/fire alarms would be REALLY bad if there was a plasma flood, but i dont think atmos techs should be punished for what other players might do. Same way with the armory existing and not having firing pins implemented yet. We simply punish those that self-antag by breaking into the armory to shoot leathals. 

Shouldn't it be the same way with atmos? Just punish those that intentionally self-antag by plasma flooding.  

Just my 2 cents and _slightly_ biased opinion.

**Comment by 5150Con** [comment]
> > Well, the window issue bothers me mostly because the tanks are far bigger then any other map, but the window is tiny comparatively. For the plasma miner, the only thing to do in downtime as tech is either map air alarms or make Tritium, and you can't really do one of those on Delta. CO2 and Water Vapor are indeed eh, but sometimes making a double airlocked steam room is a fun break. I really think that if you just shrink down some of the gas holding tanks, there would be plenty of space for the other gases, and make it future-proof once more gas mixtures are added in.
> > But I appreciate your input, I can see the plasma miner being easily abusable, but isn't that why techs are non-antags only?
> 
> Techs can’t be antags correct but that doesn’t stop anyone getting atmos access and wrenching two pipes to ruin the round. That and even though atmos techs aren’t antags, they still manage to spoil rounds. 😭

Of course if the wrong person is given access, they can cause havoc. Same goes for those given command or armory access, there are bound to be dangerous areas on the ship. Additionally, I don't know if the average atmos saboteur, which is usually frowned upon, would be able to inject it into distro fast enough or correctly before being spotted. Half the time atmos sabotage is just blowing it up, which is an easy fix for the most part. They have to do the whole pump boost>Adjust Gas Mixer>Insert into mix tank> start pump into distro. Most people I feel would get lost at the mix tank part, but I could be underestimating the community.

You don't even need atmos access to ruin a round, I can easily just do the space passive vent trick with external access and ruin the round that way. My point with that is that plasma fires, while obviously indiscriminate and nigh unfixable station wide, are frowned upon by the community. I've played Marathon, Bagel, and have had no plasma fires while I was playing however that is just my experience. Once plasma miners were added to those maps, there was a week or so of fires but then died down because it's honestly boring to do more then once or twice. Just like AME sabotage, the community will voice its displeasure at those who do so, and incidents will decline.
