### ISSUE TITLE
Vending machines can spam contents when damaged

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9879]
Wasn't exactly sure what happened but it ended with dozens of bottles and an "out of stock" popup coming up before we deleted the vending machine. Might be an issue with the eject logic?

**Comment by DoctorBeard** [comment]
So, I initially thought this should be entirely fixed by #10465 but sleeping on it, I think while that PR makes the general behavior a bit more robust it _technically_  doesn't stop vending machines from rapidly barfing out their entire stock on continuous damage. If that's undesired though it's probably less of a bug and more of a configuration issue.

This behavior (both before and after the PR) is entirely governed by the DispenseOnHitChance and DispenseOnHitThreshold fields on the vending machine component, and currently only 8 out of 45 vending machines have these values set. By default the chance is 0. The 8 that do have it are set up to have a 25% chance to throw an item from their inventory every time they receive 2 or more damage. Both reducing the chance or increasing the necessary damage per hit would ultimately reduce the spam.
