### ISSUE TITLE
Zombies are affected by IdentityBlocker

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9929]
## Description
Zombies are affected by IdentityBlocker. Not sure how plausible it's for zombie to hide gait and such, but it introduces severe gameplay issue - other zombies are more likely to friendlyfire claw you.

**Reproduction**
- Wear mask or helmet with `IdentityBlocker`
- Get zombified

**Screenshots**
![zombie_nukie](https://user-images.githubusercontent.com/108953437/180081712-7623fb24-e626-4c1e-84d3-1e83cf0ceb3b.png)

**Additional context**
Perhaps make zombies simply not friendlyfire? Something-something "You recoil from X, they smell like zombie!"?

**Comment by mirrorcult** [comment]
this is intended and is easily revealed by just seeing them use the claw or speak

**Comment by EmoGarbage404** [comment]
Realistically zombies would have a system for instantly identifying other zombies. But tbh it doesnt matter too much. I can decrease the friendly fire damage

**Comment by EmoGarbage404** [comment]
Closing this, as this is not only intended, adds extra coordination, is easily solved by speaking, and is also mostly negated as zombies have reduced damage against other zombies.

**Comment by mirrorcult** [comment]
if they're teamkilling you despite 500 obvious signs that you're a zombie then your name having 'zombified' in it isnt going to stop them either

**Comment by EmoGarbage404** [comment]
Damn, you're right. Uncoordinated players sloppily working together produces unfavorable results. How could i be such a fool. I'll just go make zombies do 0 damage to each other, no! I'll make them heal each other! I'm also going to make nukies be unable to cause harm to each other and make all syndies begin round start with a list of all other syndies and their objectives (balanced so that none of them conflict, or course)

The simple fact is that zombies are going to always hurt each other. That's the human element. If i didn't want that, zombies would be AI. Ultimately it comes down to the players to *play the game* and ultimately work together. Zombies are inherently worse than players, being slower, weaker to fire and burn, unable to use tools, and unable to even speak coherently.

And yet, every round with zombies, despite this supposed endless teamkilling, zombies manage to annihilate station crew every single time. Its almost like they are quite strong and a few friendly kills in the scuffle doesn't ruin their balance. If you get teamkilled by zombies, ahelp it. Beyond that, there's not much more i can do without dumbing down an already simple system. Play left 4 dead if you want to not hurt each other.

**Comment by moonheart08** [comment]
Zombies are literally fucking zombies

they don't have a working brain and don't give a shit about anything except murder

it's kinda expected they'd hit each-other on accident dontchathink?

This is a rather overpowered team-based antag already, and Emo is correct here design wise. Zombies are innately lesser to actual players in every way, _including coordination._

**Comment by moonheart08** [comment]
> Kinda odd to make point on coordination yet deny zombies proper communication. And Left 4 Dead game design is bad because?..

Left 4 Dead isn't SS14, it has it's own balance and design considerations that do not align with ours.

You can't just copy-paste a design from one game to another and expect it to work, that's not how game design works.
